### ISSUE TITLE
The tooltips clash with finger when graph tapped on iOS device in HASS app

### ISSUE THREAD

**Issue by wigster** [RomRider/apexcharts-card#115]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
On iOS, putting the finger on the graph shows tooltips with the data point values, but they appear in a location obstructed by the finger. This would probably be fine if they stayed after the finger is let, but they do not. 

**Version of the card**
Version: 1.8.0.dev7

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**
1) The tooltips on touch devices should appear further out.
or 2) the tooltips should remain when initiated by a touch event.

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.3
 - Browser HASS app
 - Version 2021.2.2

**Comment by RomRider** [comment]
There's not much I can do because that's how ApexChart works. You can however put the tooltip in a fixed position: https://apexcharts.com/docs/options/tooltip/

For eg:
```yaml
apex_config:
  tooltip:
    fixed:
      enabled: true
      position: topRight
```
