### ISSUE TITLE
Now: flag should be able to show values.

### ISSUE THREAD

**Issue by ivanlofgren** [RomRider/apexcharts-card#118]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Function now:, which shows a dashed vertical line at the current time, is not showing any real information. It does have great potential for doing so!

**Describe the solution you'd like**
The label: line should be receptible to custom data { ... } or at least being able to accept the newly introduced before_now/after_now magical tags (topic #86 ). This would enable the flag to show current value instead of a string.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by RomRider** [comment]
Good idea, but you could only display 1 entity data in there, is that what you are thinking?

**Comment by ivanlofgren** [comment]
Yes. For example, the now flag in the image should instead show current temperature.
![temp nu sen](https://user-images.githubusercontent.com/73953790/109858632-56cc5800-7c5c-11eb-9b8c-b8cf3601ace6.png)
