### ISSUE TITLE
when hovering over a datapoint, not enough decimals are shown

### ISSUE THREAD

**Issue by qbushome** [RomRider/apexcharts-card#119]
When you set the number of decimals on the y-axis (eg to 3), the number of decimals in the informationcard is still 1.

![Schermafbeelding 2021-03-04 om 09 58 59](https://user-images.githubusercontent.com/72740143/109938705-a2b8e480-7cd0-11eb-8fa2-eea2110784df.jpg)

The number is rounded to 1 decimal.

The data shown in this example is water usage in cubic liters
1382770 liters, or 1382.77 cubic liters

I think the informationcard should also show 1382.770 instead of 1382.8 liters

like this

![Schermafbeelding 2021-03-04 om 10 07 15](https://user-images.githubusercontent.com/72740143/109939646-8f5a4900-7cd1-11eb-9226-abec609249b2.jpg)

**Comment by RomRider** [comment]
There is a `float_precision` setting in each serie which will do what you want.

**Comment by qbushome** [comment]
Thank you very much !
It does the job.
