### ISSUE TITLE
Area chart fill range

### ISSUE THREAD

**Issue by wigster** [RomRider/apexcharts-card#122]
**Checklist**
- [x] I am running the latest version of the card
- [ ] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

Area charts start their shading fill from 0. When the data range goes into negative, this may or may not be the desired outcome. 

**Describe the solution you'd like**
An option to fill up from the bottom or up or down from the x-axis would be great!

An option to fill up from the bottom or up or down from the x-axis would be great!

![image](https://user-images.githubusercontent.com/10956987/110174800-f88caa00-7e00-11eb-940d-be3cb0818e9b.png)

**Comment by RomRider** [comment]
That exists already: https://apexcharts.com/docs/options/plotoptions/area/
```yaml
apex_config:
  plotOptions:
    area:
      fillTo: end
```
