### ISSUE TITLE
Range Bar Implementation

### ISSUE THREAD

**Issue by rgc99** [RomRider/apexcharts-card#137]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implementation of Range Bar Chart

**Describe alternatives you've considered**
Various other forms of chart types.

**Additional context**
I am the author of a custom component that manages irrigation systems. Essentially there are a number of valves or zones that are programmed to operate periodically. Each zone in the system has an associated entity in HA. I would like to display the upcoming and historical run times for each zone. Think of it as an appointment planner for a team of people.

I output the data for each zone/entity in an attribute as json formatted pairs of dates. It is straight forward enough to digest this information using the data generator. Each horizontal bar/row would represent the data from one of these entities. Something like the following.

![gag1fti2](https://user-images.githubusercontent.com/13636007/111892912-931cf800-8a53-11eb-9f27-26e015495731.png)

The javascript used to produce the above.

~~~javascript
var options = {
  series: [
  {
    data: [
      {
        x: 'Zone 1',
        y: [
          new Date('2019-03-06 05:30:00').getTime(),
          new Date('2019-03-06 05:40:00').getTime()
        ]
      },
      {
        x: 'Zone 1',
        y: [
          new Date('2019-03-07 18:40:00').getTime(),
          new Date('2019-03-07 18:45:00').getTime()
        ]
      },
      {
         x: 'Zone 1',
        y: [
          new Date('2019-03-07 05:35:00').getTime(),
          new Date('2019-03-07 05:40:00').getTime()
        ]
      },
      {
        x: 'Zone 2',
        y: [
          new Date('2019-03-06 07:30:00').getTime(),
          new Date('2019-03-06 07:50:00').getTime()
        ]
      },
      {
        x: 'Zone 2',
        y: [
          new Date('2019-03-07 05:40:10').getTime(),
          new Date('2019-03-07 05:50:10').getTime()
        ]
      },
      {
        x: 'Zone 3',
        y: [
          new Date('2019-03-06 05:50:20').getTime(),
          new Date('2019-03-06 06:00:20').getTime()
        ]
      },
      {
        x: 'Zone 3',
        y: [
          new Date('2019-03-07 05:50:20').getTime(),
          new Date('2019-03-07 06:00:20').getTime()
        ]
      }
    ]
  },
],
  chart: {
  height: 450,
  type: 'rangeBar'
 },
plotOptions: {
  bar: {
    horizontal: true,
    barHeight: '80%'
  },
},
xaxis: {
  type: 'datetime'
},
 stroke: {
  width: 1
},
fill: {
  type: 'solid',
  opacity: 0.6
 },
legend: {
  position: 'top',
  horizontalAlign: 'left'
},
};

var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();
 ~~~

Thank you.

**Comment by RomRider** [comment]
For now this format is not supported, but I'll see what I can do :)

**Comment by rgc99** [comment]
Brilliant, thank you.

**Comment by RoboMagus** [comment]
I'm definitely also interested in such a graph type. Though luckily I see the existence of the candlestick feature branch. That looks similar enough for me to make it work for my use cases.
