### ISSUE TITLE
Feature (config) request: Line Markers

### ISSUE THREAD

**Issue by pauln** [RomRider/apexcharts-card#138]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Only insofar as the lack of an ApexCharts config option I'd like to use is considered a problem ;-)

**Describe the solution you'd like**
Support for Line Markers to be configured: [see ApexCharts docs](https://apexcharts.com/docs/chart-types/line-chart/#line-markers)

**Describe alternatives you've considered**
N/A

**Additional context**
I'm plotting wind direction readings from my personal weather station, and would like to turn off the line (already possible with `stroke_width: 0`) and turn on the markers (dots) so that I have the discrete measurements plotted.

**Comment by RomRider** [comment]
I don't understand, you can already achieve all of that using `apex_config`, why duplicate?

**Comment by pauln** [comment]
@RomRider If it can be done already, please let me know what I'm missing - I tried it first, and wasn't able to get it to work, so I dug in to see whether I could implement it.  Could it be that the hardcoded `markers: {showNullDataPoints: false}` is preventing the `apex_config` from overriding it?

**Comment by pauln** [comment]
@RomRider Ah, I think I've figured it out: when I started trying to implement it, I thought that the `markers` config was part of the `series` config - so it wasn't working at all.  In a bout of late-night hacking, I managed to get it into the ApexCharts `series` config, only to find that it still didn't work - at which point I realised that although the path I'd taken through the ApexCharts docs went via series, the `markers` config isn't nested inside `series`, and moved it to where it should be.  I should've gone back and retested at that point with the `markers` in the right place...
