### ISSUE TITLE
Swedish language is missing?

### ISSUE THREAD

**Issue by rindlerblabla** [RomRider/apexcharts-card#143]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Have Swedish as frontend language but the apexcharts-cards are not following. There is a Swedish language json https://github.com/apexcharts/apexcharts.js/blob/master/src/locales/se but probably Home Assistant is not using 'se' but rather 'sv_SE' or something similar.

If I change frontend language to Norwefian bokmal och German it is working just fine. But in wrong language, hehe.

**Version of the card**
Version: 1.8.2

**Comment by RomRider** [comment]
You can force the locale in such cases:
`locale: se`

**Comment by rindlerblabla** [comment]
True that. Tried so many times adding it as different kind of apex_config values but it was supposed to be as a "root" value.

**Comment by rindlerblabla** [comment]
True that. Tried so many times adding it as different kind of apex_config values but it was supposed to be as a "root" value.
