### ISSUE TITLE
Climate display

### ISSUE THREAD

**Issue by flouck** [RomRider/apexcharts-card#153]
First of all, thank you! This has been a wonderful discovery, I definitly love this card!!!

**Describe the solution you'd like**
The basic history graph can display cliamte entities and highlight whenever the entity was heating up for instance. Likewise, it would be unbelievable to have the apexcharts card doing the same (or even better)

Below is an example of the current situation with the Lovelace history graph:

![image](https://user-images.githubusercontent.com/60158607/116621757-fac43e00-a943-11eb-817d-de52190c0bd2.png)
![image](https://user-images.githubusercontent.com/60158607/116621801-0879c380-a944-11eb-91cf-9577b8fe91c9.png)

**Comment by RomRider** [comment]
You can already do that, you just need to create 3 series out of your climate entity, 2 of them using some of the attributes instead of the state.
I won't support it natively.

**Comment by flouck** [comment]
Okay thank you @RomRider and again good job!
