### ISSUE TITLE
Example for using hass.states in transform:

### ISSUE THREAD

**Issue by rasssta** [RomRider/apexcharts-card#155]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I don't manage to understand how to use the hass.states object in the configuration for transform:

Can you please include a config example where the state from another object is used?

Thanks in advance.

**Comment by RomRider** [comment]
To access an entity state (it's the actual state, not the historical state): `hass.states['sensor.my_sensor'].state`
