### ISSUE TITLE
Download Menu Blank

### ISSUE THREAD

**Issue by DavidFW1960** [RomRider/apexcharts-card#16]
As per discussion on forum here https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/43?u=davidfw1960

The Hamburber menu is blank maybe because of styling/theme?

**Comment by DavidFW1960** [comment]
That fixed it ! I did have to manually d/l the js file though... HACS (set to beta) won't see it when I reload info etc....

**Comment by RomRider** [comment]
I can see the release in beta in HACS, strange

**Comment by DavidFW1960** [comment]
Never mind... I just checked and I am rate limited (5008 calls)
I wish Ludeeus would bloody fix this!
