### ISSUE TITLE
Only show today up until the last hour

### ISSUE THREAD

**Issue by akeslo** [RomRider/apexcharts-card#165]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Ability to show only today up to the last hour (00:00 —> Current Hour)

Is it possible to configure the above using the current span configuration? 

graph_span: 24h
span:
  start: day

**Comment by RomRider** [comment]
That is not an option at the moment. I'll see what I can do.

**Comment by RomRider** [comment]
Don't close it :)
