### ISSUE TITLE
Implementation of 100% Stacked Bars and Stacked Bars

### ISSUE THREAD

**Issue by cfabtp** [RomRider/apexcharts-card#168]
Checklist

- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the dev branch

Is your feature request related to a problem? Please describe.

Is it possible to integrate the 100% stacked bars ( [https://apexcharts.com/javascript-chart-demos/bar-charts/stacked-100/](url) ) and regular stacked bars ( [https://apexcharts.com/javascript-chart-demos/bar-charts/stacked/](url) )

Or is there a way to get it actually ? Nothing in the extremely-well documentation mention especially this type of chart

Thanks in advance!

**Comment by RomRider** [comment]
At the moment, that is not possible.

However, I'm wondering where would the data come from? Home assistant would only provide historical data with timestamps.

**Comment by cfabtp** [comment]
I monitor multiple power consumptions in my house, like heating, hot water, A/C, lights and plugs. So actually I've near 10 gauges horizontally stacked and vertically stacked and it's pretty shitty. The 100% stacked bars (with only 1 line) would be awesome to display the part of each type of consumptions in reference with the other ones

**Comment by RomRider** [comment]
At the moment you can use the donut or the radial chart to display that kind of information, if that helps :)

**Comment by katiuskt** [comment]
Exactly the same use case here. Right now with pie/donuts charts I can see the % consumption per day. No problem with that but If I can see the same information for the last 7 days, day by day, it means 7 graphs.

However, if the current "bar" graphics could represent the information as a "Stacked Bar" it would be really awesome!

So, in case it matters for future versions, +1 for this feature request 👍

**Comment by wtadler** [comment]
I would also like this feature, for the same use case: power monitoring, where it is nice to track the total over time as well as the proportional contributions.

Even better would be stacked area charts as in [this demo](https://apexcharts.com/javascript-chart-demos/area-charts/stacked/#). Setting `stacked: true` in the current version of the card with line plots does something different from this.

**Comment by wtadler** [comment]
Would still like to see this if possible!
