### ISSUE TITLE
Do not require the use of recorder when using a chart-type donut or pie

### ISSUE THREAD

**Issue by wipeout666** [RomRider/apexcharts-card#169]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Why does the card require enabling the recorder for an entity when only a pie or a donut is used?

**Describe the solution you'd like**
A pie or a donut only need the last value of a sensor, hence the chart pie or donut should work when recorder is not active on a specific sensor

**Describe alternatives you've considered**
I've tried setting up another sensor with a very very long scan_interval (999999 days) and force update of that sensor once in a while with homeassistant.update_entity, but that doesn't work for template sensors.

**Additional context**
```
type: 'custom:apexcharts-card'
chart_type: donut
series:
  - entity: sensor.energymonthlywatertank
```
The above won’t work if sensor.energymonthlywatertank is excluded from the recorder, even if only the last value of the sensor is needed for the chart.

![image](https://user-images.githubusercontent.com/71163149/121792967-efae3000-cbc8-11eb-8234-a639bbe1fde4.png)

The reason I’m asking for this feature is that I have over 15 “utility meter” that are updated every two seconds that basically count the kWh total of many different loads in my home. Enabling the recorder on those will chew up GB of data while I only need the last state; the integration total.

**Comment by energywave** [comment]
I have the exact same problem. Would love to use this wonderful card to show a pie of how I consumed my electricity daily and monthly. For that I'm splitting some cumulative sensors for different electricity use (kitchen, pool, lights, TV, laundry, etc) that are updated as energy is consumed and **I absolutely don't want to let them in the recorder** as they'll generate tons of not useful data!
So something like a general option or per serie option that tells if to use current state value or get them from recorder would be wonderful.
Until that I'll have to rely on the bad working pie-chart-card :(

I hope you'll implement this, would be so useful.

**Comment by RomRider** [comment]
I'm going to work on this soon!

**Comment by energywave** [comment]
> I'm going to work on this soon!

That would be awesome!!! If you want someone to give a test I'm in.

**Comment by RomRider** [comment]
It's released in beta, feedback welcome :)

**Comment by energywave** [comment]
> It's released in beta, feedback welcome :)

I've tested version 1.10.0-dev.2 with my configuration. It works very well! Good work! Here a screenshot of how I'm using it
![image](https://user-images.githubusercontent.com/2051567/124381770-88b20180-dcc4-11eb-965a-fb70d9348c4e.png)

The only thing I could not understand if there is a way to do it is to show data labels as values and not in percent. For instance in the left pie on the left big slice shpw 3.7 kWh and not 43.7 (or at least show 43.7%)
I've tested the datalabels in the show options of the series but I think to have found a bug: "true" is working, "false" is not working (same behavior than true) and "total" is doing what I was expecting from "false".

Details. But I hope to have helped you in refining :) Keep on the good work!

**Comment by RomRider** [comment]
@energywave, the latest beta should address your new request. It's not supported by ApexCharts by default but I've managed to hack something together :)

**Comment by energywave** [comment]
Hey @RomRider you're too fast! I've updated to dev 4 and hey, wonderful work! I love that pie chart!!! Thank you so much for your invaluable work!

**Comment by wipeout666** [comment]
Thanks @RomRider for fixing this issue & EnergyWave's issue mentionned just above, these were the two missing pieces from my point of view!
