### ISSUE TITLE
Sliding Window Moving Average group_by function

### ISSUE THREAD

**Issue by lanrat** [RomRider/apexcharts-card#178]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

Currently the `avg` function splits the time into buckets. If there is an extreme on one of the edges of the bucket ranges, the resulting line may have a spike/dip earlier or later than the underlying data would suggest.

Here is an example graph:
![image](https://user-images.githubusercontent.com/164192/124860251-309a2a00-df66-11eb-9061-6240cb316c0a.png)

**Describe the solution you'd like**
A [sliding window moving average](https://en.wikipedia.org/wiki/Moving_average#Simple_moving_average) function for in use by `group_by` would be a helpful alternative to the existing `avg` function.

**Describe alternatives you've considered**
Writing my own transformation. I'm sure this would work,. but it would be a lot of code to include in each graph for what should be included in the library.

**Comment by RomRider** [comment]
Would you want SMA to work over buckets of time (ie. avg over last `duration` **for each point**) or number of points (Like SMA50 = last 50 points)?

I believe buckets of time is better because data can be spread unevenly over time (for non-regular timeseries) but it's also going to be slower to compute...

In both cases, the result would have the same resolution (number of points) as the data in the original series, you'd still see the "lag" you're seeing both before and after the spike.

**Comment by lanrat** [comment]
I was also thinking of using buckets of time, but in order to fix the "lag" issue, allow the user to provide two variables, one for the window size (duration to average over) and another for window update interval (duration). See the ESPHome [sliding_window_moving_average](https://esphome.io/components/sensor/index.html#sliding-window-moving-average) as an example. (However this uses data points instead of duration, which should also be fine)

I think that allowing the sliding window to be larger than the sample duration should remove the lag.

**Comment by lanrat** [comment]
Bump.

**Comment by lanrat** [comment]
bump again.

**Comment by lanrat** [comment]
bump

**Comment by lanrat** [comment]
Bump.

**Comment by lanrat** [comment]
bump...

**Comment by lanrat** [comment]
Bump
