### ISSUE TITLE
Option to hide legend

### ISSUE THREAD

**Issue by haddood** [RomRider/apexcharts-card#180]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch: not sure how to do that, not a programmer

**Describe the solution you'd like**
boolean option to hide legend in header section
show_legend: false

**Comment by RomRider** [comment]
You can already hide the legend:
```yaml
apex_config:
  legend:
    show: false
```

**Comment by haddood** [comment]
thank you ... I looked for it, but it seems not documented in the read me. 
thank you for the amazing work
