### ISSUE TITLE
Stroke line always on top

### ISSUE THREAD

**Issue by haddood** [RomRider/apexcharts-card#181]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
with multiple area series and low transparency, some graphs disappear under other graphs. or there color gets affected by other areas. currently there is no Z control over the graphs.

**Describe the solution you'd like**
boolean option to set stroke to be always on top

always_on_top: true

**Comment by RomRider** [comment]
I believe the order of the series is based on the order you define them in the configuration.
There's no such control in the library I use unfortunately so if the above solution doesn't work, I won't be able to do anything to fix it.

**Comment by haddood** [comment]
understood. thank you for the great work
