### ISSUE TITLE
Feature request: remove state info in legend

### ISSUE THREAD

**Issue by CDRX2** [RomRider/apexcharts-card#20]
I would like to remove the state information shown in the legend. The goal would be to be able to show only the series name.

**Comment by RomRider** [comment]
Just wondering if I should make this a global parameter (i.e. affecting all entities in one shot) or a per series parameter.
What do you think?

**Comment by CDRX2** [comment]
I'd go with per series, gives more flexibility in my opinion.

**Comment by CDRX2** [comment]
Just tested it, works perfectly, thanks!
