### ISSUE TITLE
Remove x-axis title?

### ISSUE THREAD

**Issue by geidorei** [RomRider/apexcharts-card#207]
...or am I being thick? lol

Want to move the X-Axis titles for the data - can this be done?

**Comment by RomRider** [comment]
By default there's no "title", so I'm not sure what you are talking about.

**Comment by geidorei** [comment]
My fault lol - where it says at the bottom Lounge 43.20% etc - that's what I want to remove - the names of the data, many thanks.

![Capture](https://user-images.githubusercontent.com/4543895/132326439-b2d00931-86e3-472a-913f-0a3c94389896.PNG)

**Comment by RomRider** [comment]
That's with:
```yaml
apex_config:
  legend:
    show: false
```

**Comment by geidorei** [comment]
Fantastico! Many thanks for your help!
