### ISSUE TITLE
Weekly Usage from a sensor that resets daily - sum of daily max

### ISSUE THREAD

**Issue by snagytx** [RomRider/apexcharts-card#218]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I have a sensor that resets daily, like - bandwidth usage. This sensor is updated multiple times a day, maybe 5-6 times.

I can build a chart with:
```
group_by:
   func: last
    duration: 1d
```
to get a daily usage. I can also use the max func, but I guess last requires less processing cycles.

**Describe the solution you'd like**
A way to graph weekly usage. I would need a sum of daily max.

I guess I would use:
```
group_by:
   func: XXXX
    duration: 1w
```
but I don’t find a XXX function to do sum of daily max - or I’m missing another approach? 

**Describe alternatives you've considered**
I would try to stay away from creating another sensor to keep the usage for that week and resets every week.

**Additional context**

**Comment by Gollam** [comment]
I also ran into this, would greatly appreciate it :)

**Comment by RomRider** [comment]
I'm going to implement support for custom functions for `group_by` so that you can do whatever you want with the data in each bucket. You'll have to build your own function for that because what you ask is a 2 step group_by in some ways:
1. group_by day -> take the max
2. group_by week -> sum all the max of each day

**Comment by snagytx** [comment]
I think this is something acceptable.
