### ISSUE TITLE
Update Interval not working after update to v1.10.0

### ISSUE THREAD

**Issue by jorgestima** [RomRider/apexcharts-card#227]
After yesterday making the upgrade of apex to version v1.10.0 in my Home Assistant, my graphs that had the command update_interval to refresh the graph at defined time intervals, stopped or become fronzen, that is, do not update anymore automatically according to the given time.

**Comment by Swiftnesses** [comment]
+1, downgrading to 1.9.0 fixed it.

**Comment by RomRider** [comment]
That is fixed in the latest beta

**Comment by tomasrudh** [comment]
I can confirm that in version v1.10.1-dev.2 do 'update_interval' work.
