### ISSUE TITLE
Display values as a duration using different Formats

### ISSUE THREAD

**Issue by ee02217** [RomRider/apexcharts-card#228]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Describe the solution you'd like**
Be able to change the format of the duration displayed when using "as a duration".
![image](https://user-images.githubusercontent.com/60232595/139445892-d8cec6fa-4562-4b11-af67-e5002b9ef615.png)

Currently displayed as HH:mm:ss and could be defined in card configuration to be as an example just HH:mm.

**Comment by ee02217** [comment]
Am I the only want that wanted this? ;(

**Comment by RomRider** [comment]
Don't close 😊
