### ISSUE TITLE
Header_actions on radial bar chart

### ISSUE THREAD

**Issue by CDRX2** [RomRider/apexcharts-card#230]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

Using `header_actions` does not work with radial bar chart. Clicking on the title has no effect. Tested with `action: navigate` and `fire-dom-event`.

Version: 1.10.1-dev1

This is the configuration I used:
```
    type: 'custom:apexcharts-card'
    config_templates: radial_bar
    header:
      show: true
      title: CDRXStation1
    all_series_config:
      header_actions:
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            card:
              type: 'custom:swipe-card'
              cards: 
                - !include ../frontend/station1.yaml
                - !include ../frontend/station2.yaml
                - !include ../frontend/station3.yaml
                - !include ../frontend/stationB.yaml
            style: |
              ha-dialog {
                --mdc-dialog-max-width: 100vw !important;
              }
              :host .content {
                width: 98vw !important; 
              }
              ha-card {
                border-radius: 0.8vw;
                opacity: 0.9;
              }
            title: Synology NAS        
    apex_config:
      title:
        margin: 0
      legend:
        horizontalAlign: left
      plotOptions:
        radialBar:
          dataLabels:
            show: false
    series:
      - entity: sensor.cdrxstation1_volume_1_volume_used
        name: Volume 1
        color: '#03a8f4'
      - entity: sensor.cdrxstation1_volume_2_volume_used
        name: Volume 2
        color: '#ffa31a'
    card_mod:
      style: |
        :host {
          height: 100%;
        }
        ha-card {
          box-shadow: none !important;
          height: 100%;
        }
        .wrapper.with-header {
          height: 100%;
        }
        .apexcharts-inner.apexcharts-graphical {
          transform: translate(-22.5%, -5%);
        }
        .apexcharts-legend {
          width: 50%;
        }
        div#graph-wrapper {
          transform: translate(0, -5%);
        }
```

**Expected behavior**
Action should be triggered by clicking on the header (e.g. the card title)

**Desktop:**
 - Browser: Chrome
 - Version: 95.0.4638.69 64bit

**Smartphone:**
 - Device: Realme X2 Pro
 - OS: Android 11
 - Browser: Home Assistant Companion App
 - Version: 2021.10.0-full

**Comment by CDRX2** [comment]
Nope, not stale, just dormant ;-)

**Comment by CDRX2** [comment]
Up, still not resolved.

**Comment by RomRider** [comment]
I'll fix that soon, sorry, been quite busy lately 😊

**Comment by CDRX2** [comment]
No stress, just keeping the issue alive ;-)

**Comment by CDRX2** [comment]
Up ;-)

**Comment by CDRX2** [comment]
Up!

**Comment by CDRX2** [comment]
Not stale, just dormant!

**Comment by RomRider** [comment]
I can't reproduce this issue, it works for me whatever the chart and whatever the action is (including browser-mod).
I'll soon publish a new version with updated dependencies which might have fixed the issue in my test env.
Please report once it's released :)

**Comment by CDRX2** [comment]
Interesting! Looking forward to testing the new release. In the meantime, a quick question: I only show the chart title in the header in this particular use case. Could it be that the title does not accept the header actions?

**Comment by RomRider** [comment]
It's released as beta, please let me know :)

**Comment by CDRX2** [comment]
Thanks for the clarification. But if the title doesn't support actions, which part of the header does in a radial bar chart? As far as I've experienced, the states are not shown in the header in this type of chart, so basically that would mean there is no "actionnable" element in a radial bar chart.

Actions work fine in all bar/line/area/hybrid charts. Opening a FR for header actions to be supported on the title ;-)

**Comment by RomRider** [comment]
You can activate the states in the header for all the charts.
```
header:
  show_states: true
```

**Comment by CDRX2** [comment]
Thanks! I can confirm it works in radial bar as well. Closing this issue, as it has now become a FR, see #323. Thanks @RomRider for your help.
