### ISSUE TITLE
Chart type "polarArea" implementation

### ISSUE THREAD

**Issue by rufik** [RomRider/apexcharts-card#232]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No `polarArea` value for option `chart_type` :(

**Describe the solution you'd like**
I'd like to have option `chart_type = polarArea` for visualization of wind direction from my weather station.
https://apexcharts.com/javascript-chart-demos/polar-area-charts/basic/
https://apexcharts.com/docs/options/chart/type/

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by rufik** [comment]
Any chance to get it implemented?

**Comment by RomRider** [comment]
This is planned in the future but it's a complete different implementation

**Comment by rufik** [comment]
Keeping it open.

**Comment by cooltings** [comment]
Any update on this?
