### ISSUE TITLE
String type sensor not show in header

### ISSUE THREAD

**Issue by gualandd** [RomRider/apexcharts-card#234]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
A string sensor can no more be displayed in Header with setting "RAW", it is visualized as NaN instead of String Text.

**Version of the card**
Version: last

**To Reproduce**
Create a string type sensor (with changing text) and set it to be displayed only in header with RAW method.
Instead of the string it will display NaN.

**Expected behavior**
Visualize the string instead of NaN

**Desktop (please complete the following information):**
 - Browser: Chrome & Firefox
 - Version Last

**Comment by KairuByte** [comment]
Was just about to report this. Latest stable does not have this issue from what I remember, latest beta does.

**Comment by KairuByte** [comment]
Still relevant, hence commenting.

**Comment by KairuByte** [comment]
Please no stale.
