### ISSUE TITLE
Add "Extend to now" similar to "Extend to end"

### ISSUE THREAD

**Issue by ThoStaKa** [RomRider/apexcharts-card#238]
**Checklist**
- [ X] I am running the latest version of the card
- [ X] I checked if there isn't another feature request opened with the same request
- [ X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Some data are missing the latest value in the chart, such as current power price or current value of a binary transform shown as area.

**Describe the solution you'd like**
Some data are best represented in an "Extend to now" manner, such as current power price or current value of a binary transform. Rather then extending graphically "to End", it would sometimes be preferable to only extend to Now

**Additional context**

Relevant forum post here:
https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1266?u=thostaka
![image](https://user-images.githubusercontent.com/34090557/141463725-a5f69569-619b-40fd-b5fa-6c90d72d8164.png)

**Comment by RomRider** [comment]
Don't close :)
