### ISSUE TITLE
Offset x-axis labels? 

### ISSUE THREAD

**Issue by Gollam** [RomRider/apexcharts-card#239]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

Our electricity company is pushing the utility meter values with a 2 day delay :( I've managed to plot it with your lib, using the offset value of +2d. It now aligns with other data I want to display, but of course the x-axis date labels stay intact, and I want to offset those as well. So I just want to ask, is the x-axis label modification possible somehow, or is it a library limitation?

**Comment by RomRider** [comment]
Is the data available trough attributes of a sensor or is it available through the value of the sensor itself?
