### ISSUE TITLE
Stacked columns not stacking

### ISSUE THREAD

**Issue by solmoller** [RomRider/apexcharts-card#240]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console (no, I did an in place file upgrade, and restarted HASS)
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
Vanilla test by changing the default example to a stacked bar chart… , no stacking, all columns are separated

**Version of the card**
Version: downloaded today, can't find version number

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
apex_config:
  stacked: true
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.power_consumption
    type: column
    data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();
  - entity: sensor.power_generation
    type: column
    data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();


```

**Screenshots**

**Expected behavior**
Bars to be stacked instead of placed next to each other

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 95.0.4638.69

**Smartphone (please complete the following information):**
 - Device: Huwaei P30 lite
 - OS: Android 11
 - Browser Chrome

**Comment by RomRider** [comment]
That's because your config is wrong. `stacked` is a main config option:
```
type: custom:apexcharts-card
stacked: true
[...]
```

**Comment by solmoller** [comment]
Sigh - that solved all my problems, thank you very much!
