### ISSUE TITLE
Extending the chart to the boundaries of card

### ISSUE THREAD

**Issue by orestesgaolin** [RomRider/apexcharts-card#244]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

The minimal layout of the card allows to extend the chart to the boundaries of ha-card like this:

<img width="498" alt="CleanShot 2021-11-23 at 23 58 52@2x" src="https://user-images.githubusercontent.com/16854239/143142168-e2983222-395d-4a7f-9cd8-612ee4c3c9a6.png">

This was also possible in mini-graph-card
<img width="434" alt="CleanShot 2021-11-23 at 23 54 58@2x" src="https://user-images.githubusercontent.com/16854239/143141822-246876c6-bb56-4a0a-896a-367b278581b9.png">

However, in case of normal layout the graph has a transform of 14 px to the right

<img width="433" alt="CleanShot 2021-11-23 at 23 54 25@2x" src="https://user-images.githubusercontent.com/16854239/143141800-65b53cd1-97f4-4da0-b12c-5d78f256b48d.png">

**Describe the solution you'd like**

I would like to:
- either define the padding around the chart
- or use full-width charts with layouts different than `minimal`

**Describe alternatives you've considered**
I tried manually to override the css style, but the transform seems to be applied on the SVG level. I don't know how to customize that.

**Comment by RomRider** [comment]
I believe you can use: https://apexcharts.com/docs/options/chart/offsetx/ to modify that.
