### ISSUE TITLE
Transform is concatenating rather than adding

### ISSUE THREAD

**Issue by trevortrevor** [RomRider/apexcharts-card#249]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Transform holds ```x``` as a string, and the ```+``` operator concatenates rather than sums the values.
```js
return x + 10;
```
Returns x, not transformed, possibly has .10 added to value, haven't checked.
```js
return x - (-10);
```
Returns ```x```, increased by ```10```, the desired behaviour.
```js
return 10 + parseInt(x);
```
Returns ```x```, increased by ```10```, the desired behaviour

**Version of the card**
- Version: 1.10.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
series:
  - entity: sensor.cooker_hood_mean_humidity
  - entity: sensor.cooker_hood_mean_humidity
    transform: "return (x+10);"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/37073298/144453463-83058abb-f44e-4d5f-ab07-e88bf10da583.png)

![image](https://user-images.githubusercontent.com/37073298/144453384-10f701b1-9a3e-4fbf-a37c-bc9e0e0266e4.png)

![image](https://user-images.githubusercontent.com/37073298/144453300-30b39bd1-d73a-4323-9104-aa7330a0db30.png)

**Expected behavior**
```return x + 10;``` and ```return parseInt(x) + 10``` should return the same value.
Either the documentation needs to state that the transform function parses the entity state as a string or the default behaviour need to be adjusted.

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version 96.0.4664.45

**Comment by RomRider** [comment]
If the card receives a state as a string it is because it is stored as a string by Home-Assisant. That means your sensor is wrongly configured or your integration is bad.
The correct solution is the one you mentioned using `parseInt` or `parseFloat`
