### ISSUE TITLE
now - display current sensorvalue

### ISSUE THREAD

**Issue by sorentorp** [RomRider/apexcharts-card#258]
**Checklist**
- [x ] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [-] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
**I would love to display the current value, instead of a text. In my usecase, the current powerprice.**

**Describe the solution you'd like**
**Add the possibility to display a sensor value instead of text in "now"**

**Describe alternatives you've considered**
None.

**Additional context**

![Screenshot 2021-12-16 13 43 42](https://user-images.githubusercontent.com/4117997/146374328-81d7f565-f0fb-4ea4-8929-060d0782e40b.png)

**Comment by kpoppel** [comment]
This seems useful to me too.  Allow the now: label: to access the entity status (or attribute status actually in the case above) at the current time.

**Comment by kpoppel** [comment]
Still valid.

**Comment by supersej** [comment]
I agree. If "Now" is enabled in the card, it will show the latest value of a sensor, not the current "now" value.
And this is problematic when showing kWh prices for a hole day but "now" is midday.
Then hovering over "now" will show the correct price for kWh right now.
But the value in the header will show the price from 23-24 (00) since this is the last value on the chart. But not the actual value.

**Comment by sorentorp** [comment]
Is there any more information needed for this feature request?

**Comment by RomRider** [comment]
@supersej, for your use case, there's the `before_now` or `after_now` option. Please look at the documentation.

For the initial request, I'm going to implement it next week.

**Comment by sorentorp** [comment]
Yay! Thank you @RomRider

**Comment by sorentorp** [comment]
@RomRider  did you get around to implementing this feature? Or did I miss something?

**Comment by RomRider** [comment]
No I didn't yet

**Comment by sorentorp** [comment]
Fair enough :-)

**Comment by sorentorp** [comment]
Still relevant :-)
