### ISSUE TITLE
lines thick

### ISSUE THREAD

**Issue by terminet85** [RomRider/apexcharts-card#26]
What about let customize lines thick?

**Comment by RomRider** [comment]
That you can already do, see [here](https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/12?u=romrider)

**Comment by terminet85** [comment]
Thanks! May I suggest you to emphasize this in the doc? 'cause I've read it but missed :/

**Comment by RomRider** [comment]
There are literally thousands of options in ApexCharts, see [here](https://apexcharts.com/docs/options/annotations/) the whole menu! Those go into the `apex_config` object.

I can probably show an example for this specific use case but there is no way I'm going to document the `apex_config` object. 🙂

**Comment by deepcoder** [comment]
Yes, it's some more work for you, but you might considering turning on 'Discussion' here in Github. The HA forums, as are most forums are a poor place for tips, formulas and such. The whole 'Blueprint' thing with the HA forums is a nightmare IMHO.

**Comment by RomRider** [comment]
I'll consider it, thanks. But I already have a lot of work ;)

**Comment by RomRider** [comment]
Fixed in fd4a49542ea2fc7ebee10969c73bcbe26c73b68a
