### ISSUE TITLE
Wrong Sensor Value

### ISSUE THREAD

**Issue by maxambro** [RomRider/apexcharts-card#267]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [x ] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
Wrong sensor value

**Version of the card**
Version: last

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  title: Clima Bagni
  show_states: true
  colorize_states: true
series:
  - entity: sensor.bagni_temperature
    data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();
  - entity: sensor.bagni_humidity
    type: column
    data_generator: |
      // REMOVE ME
      const now = new Date();
      const data = [];
      for(let i = 0; i <= 24; i++) {
        data.push([now.getTime() - i * 1000 * 60 * 60, Math.floor((Math.random() * 10) + 1)])
      }
      return data.reverse();


```

**Screenshots**

![ValueIssue](https://user-images.githubusercontent.com/67421050/148372919-433e3f62-ca65-4cce-9253-8f3132d3aea1.jpg)

**Expected behavior**
Right sensors value

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - chrome
 - Version [e.g. 22] - last

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
It says `REMOVE ME`, so remove it :)

**Comment by Cyoxite** [comment]
You need in sensor section link your sensor id like this:

```
series:
  - entity: sensor.100021212111
  - entity: sensor.1000667675_t
```

**Comment by maxambro** [comment]
> It says `REMOVE ME`, so remove the whole datagenerator section.

Done...now it's ok...THX
