### ISSUE TITLE
Feature request: dynamic y-axis upper/lower across multiple charts based on HA entity

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#27]
Your thoughts on an idea for dynamic y-axis based on some entity and formula.

Being able to have a fixed upper and lower limit on the y-axis lets you show the detail and subtleties of data. But two frustrations often occur. 

First, you have multiple graphic panels with fixed axis values. You want to change them all to a different common set of values. It's a search and replace in YAML, and since I do not use GUI to manage my Lovelace, I don't know how you would do this in GUI.

Second, if you have a y-scale that can either move up and down or expand and contract based on some dynamic input. For example, outdoor temperatures can range from very low (below 32 or 0) to very high ( 100+ or 40+)  . Having the whole range in this all the time, yields charts without detail. So being able to set the upper and lower y-axis value based on some formula on a Home Assistant entity, would allow for this. For example, month of year, a lagging moving average, or any other entity that you could expose in HA with a formula applied.

The issue with a fixed 'min' and 'max' option is that, 1st you cannot have a common one across charts, and 2nd this is not a really good way to understand change if your y scale is changing without your control.

It seems like ApexCharts allows a formula for the min and max values, but I am still trying to figure it out. And, if possible at all, some kind of 'decorator' to bring in a Home Assistant 'input_number' or 'entity' to a ApexCharts 'function' would be needed for what I am trying to describe.

```
min: Number || Function
Lowest number to be set for the y-axis. The graph drawing beyond this number will be clipped off
You can also pass a function here which should return a number. The function accepts an argument which by default is the smallest value in the y-axis. function(min) { return min }

```

Thanks for your thoughts.

**Comment by RomRider** [comment]
By default the Y-scale is dynamic if min and max are not specified in `apex_config` (You can also define only min or only max). Not sure I understand the purpose here.

You solution seems to defeat the purpose of automatic dynamic scaling or maybe I don't understand.

**Comment by scooper1** [comment]
I have similar issues  I have data values that I want to show as the correct values and demand values that can be scaled to fit

in my case I have temperatures I want to show as real values and heat demand values that go 0 to 100%  which I am happy to scall to fit in the temperature range 

I also have a separate issue that zero demand value is not plotted

**Comment by RomRider** [comment]
If I allow functions to be defined in `apex_config.yaxis.min/max`, would that be enough?

**Comment by scooper1** [comment]
this is the scaling issue am having - I could fix it by generating  another template value for the 10 cards I would like to do 
<img width="395" alt="newgraph" src="https://user-images.githubusercontent.com/14822945/106511869-c36efe00-64c8-11eb-9ea4-02b8199616e2.png">

**Comment by RomRider** [comment]
Did you try with a second `yaxis` just for `Demand` (You'll have to put it at the beginning of the series' list)? Then it would scale independently.
```yaml
apex_config:
  yaxis:
    - show: true # or not :) That is for Demand
      opposite: true
      min: 0
      max: 100
    - show: true # that is for all the others
series: # Order is important!
  - entity: DEMAND
  - entity: CURRENT_TEMP
  - entity: TARGET
  - entity: OUTSIDE
```

**Comment by scooper1** [comment]
thanks missed that

**Comment by RomRider** [comment]
@deepcoder, if the value is not changing every 2min, I think you could use: https://github.com/iantrich/config-template-card to achieve what you want.

**Comment by deepcoder** [comment]
@RomRider if you are saying that by using 'Config Template Card Card' to change the values for 'ymax' and/or 'ymin' in : 
```
apex_config:
  yaxis:
    min: 40
    max: 100
```
based on some HA entity state or attribute, but only at a maximum of every 2 minutes, they yes that should meet the use cases I was considering:

1) change y axis range based on day vs. night
2) change y axis range based on month of year

Can you give me an idea of how you think that would be templated?

**Comment by FreshlyBrewedCode** [comment]
Possibly related: I would like to use "soft bounds" for `yaxis.min/max`. So generally, I would like the y axis to range from 0-30°C, however, setting min/max explicitly would cut off any values above/below that range.

Basically I want to set `yaxis.min = (min_value) => Math.min(min_value, 0)`. As far as I know this is currently not possible. I think an option could be to accept a [template](https://www.home-assistant.io/docs/configuration/templating/) for min/max?

**Comment by etnoy** [comment]
> Possibly related: I would like to use "soft bounds" for `yaxis.min/max`. So generally, I would like the y axis to range from 0-30°C, however, setting min/max explicitly would cut off any values above/below that range.
> 
> Basically I want to set `yaxis.min = (min_value) => Math.min(min_value, 0)`. As far as I know this is currently not possible. I think an option could be to accept a [template](https://www.home-assistant.io/docs/configuration/templating/) for min/max?

Did you find anything? I would also like this since I always want the 0 to be included in the energy charts, but we sometimes have negative pricing messing up my graph!

**Comment by 18107** [comment]
This would be very useful to me.

I am trying to display energy price forecasts. Most of the time, the prices are in the range 0 - 40. Occasionally the predictions go as high as 2000.

I'm currently using `max: ~40` to auto-scale the graph when higher prices appear, but I would like to limit it to 200, so values higher than 200 don't make the rest of the graph unreadable. I don't particularly care what the higher values are, so having them off the top of the graph is fine for my use case.

**Comment by martin3000** [comment]
For the y-axis, I would like to see something like
min: 0
max: 40+
which means that max is 40 if all values are below 40. If there are higher values, the y-Axis should switch to dynamic scaling.

As far as I understand it, ~40 does the opposite: the axis is dynamic, but always clipped at 40.

**Comment by gregorko** [comment]
I'm also missing the possibility to define a function for min and max. Also it seems its not possible to use `yaxis.apex_config.min/max`
