### ISSUE TITLE
Legend update on hover instead of tooltip

### ISSUE THREAD

**Issue by Damix48** [RomRider/apexcharts-card#270]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Describe the solution you'd like**
Instead of showing a tooltip when hovering a point on the graphs, it would be nice to update the legend.

**Describe alternatives you've considered**
In order to achive this, it is possible to use `tooltipHoverFormatter` properties of `legend`. Here the documentation [https://apexcharts.com/docs/options/legend/#tooltipHoverFormatter](https://apexcharts.com/docs/options/legend/#tooltipHoverFormatter).

**Comment by RomRider** [comment]
That's not possible with the library I use but I'll think about building my own legend that might bring this possibility in the future
