### ISSUE TITLE
Problem with graph Offset -1 day

### ISSUE THREAD

**Issue by Mick51** [RomRider/apexcharts-card#273]
**Checklist**
- [x] I updated the card to the latest version available, YES
- [x] I cleared the cache of my browser, YES
- [x] I verified that I'm really running the lastest version in my browser console, YES
- [x] I checked if there is another issue opened with the same problem, YES

**Describe the bug**
Hello, I have a problem with the graphics of the old one which do not correspond to my history, so I deduce that the problem comes from this mod. I you but the photos of the problem and my code right after. Thank you

**Version of the card**
Version: v1.10.0

**To Reproduce**
This is the configuration I used:
```type: custom:apexcharts-card
graph_span: 1d
apex_config:
  chart:
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: true
        zoomout: true
        pan: true
        reset: true
header:
  show: true
  title: Consommation Journalière
  show_states: true
  colorize_states: true
series:
  - entity: sensor.energie_journaliere_kwh
    name: Consommation Aujourd'hui
    stroke_width: 2
    group_by:
      func: avg
      duration: 15min
  - entity: sensor.energie_journaliere_kwh
    name: Consommation Hier
    stroke_width: 2
    offset: '-1d'
    group_by:
      func: avg
      duration: 15min

```

**Screenshots**
https://ibb.co/QMnSm6h
https://ibb.co/FzG8wHv

**Expected behavior**
Normally it should be based on the history, except the captures show that this is not the case. Besides, the figures came out of nowhere, these figures do not even exist in reality ..... I do not know where these aberrant figures come from.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 97.0.4692.71 (Build officiel) (64 bits)

**Smartphone (please complete the following information):**
 - Device: Galaxy S21
 - OS: Android 12
 - Application Home assistant
 - Version 2022.1.1-full

**Additional context**

**Comment by RomRider** [comment]
Can you remove the average function and see what the result is please?
Also you can paste screenshots directly here, no need to use an external service to host them.

**Comment by Mick51** [comment]
![Capture d’écran 2022-01-20 184513](https://user-images.githubusercontent.com/40418405/150393265-f1cec993-b840-4d6d-97f2-449e1d4e9ec4.jpg)

removing the average function didn't change anything, he did the same thing yesterday at 10 p.m. with the same wrong numbers.
