### ISSUE TITLE
Charts using data generator donot materialize on iPhone

### ISSUE THREAD

**Issue by vingerha** [RomRider/apexcharts-card#276]
I am using the data generator for a (relatively) small set of data (5 dates and 5 values) and on the laptop / desktop all is fine
However on iPhone I only see the empty graph with 'Loading'
Apexcharts  Version: 1.1
Device: iPhone 12, iOs 15, using HA app

---example in apexcharts conf
type: custom:apexcharts-card
header:
  title: Gas 3yr
  show: true
graph_span: 3y
span:
  start: year
  offset: '-3y'
apex_config:
  dataLabels:
    enabled: true
series:
  - entity: sensor.gazpar_mon_logement_pce_period
    name: EnedisGateway2MQTT
    data_generator: |
      return entity.attributes.periodreg.map((periodreg, index) => {     
                return [new Date(periodreg).getTime(), entity.attributes.periodcon[index]];
              });
    group_by:
      func: avg
      duration: 200d

---- data in the sensor
periodreg:
  - '2019-03-21 06:00:00'
  - '2019-09-19 06:00:00'
  - '2020-04-06 06:00:00'
  - '2021-03-17 06:00:00'
  - '2021-09-20 06:00:00'
periodavg:
  - 56
  - 20
  - 59
  - 49
  - 16
--- end example

Note that I have other charts with data-generator as well, similarly in not showing in full on iPhone

**Comment by RomRider** [comment]
I believe there are some issues with Apexcharts on iphones unfortunately. I plan to update the library to the latest version over the weekend and publish a new version soon with that, it might fix it, or not.
I don't own apple devices, so I can't even test.

**Comment by vingerha** [comment]
I am happy to help testing nut not sure if that is efficient with the time to respond to you sending updates and me testing it. Also...I would not know (not just right now) how to get logs out of the iPhone...if any. 
Anyhow...just let me know
