### ISSUE TITLE
Extend "transform" with ability to transform date of entity status

### ISSUE THREAD

**Issue by kpoppel** [RomRider/apexcharts-card#277]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
The [transform](https://github.com/RomRider/apexcharts-card#transform-option)-option offers the ability to transform the entity value throught he 'x' value.
For sensor date which registers e.g. utility data which are consistently at least 24h old, it would be very convenient to be able to skew the date of the series to the correct one by using transform.

**Describe the solution you'd like**
I would like what would amount to a 'date' parameter in addition to the 'x' parameter of the tranaform-option such that the following is possible (I am not sure of datetime calculations in JS, so bear over with that detail here):

```
type: custom:apexcharts-card
series:
  - entity: sensor.water_day_data
    transform: "delta=<timedelta(1d)>; return (date, x) === (d-delta, x);"
```

**Describe alternatives you've considered**
I am the author of a couple of integrations where the returned data is at least 24h delayed - yesterday's consumption basically.  So far I put the data in the attributes of the last state and use data_generator to chart the data at the correct point in time.   It would however be a lot more convenient if the true sensor data could be used instead.

**Additional context**
As an example.  The sensor data is updated when the data becomes available:
![image](https://user-images.githubusercontent.com/4174578/150659778-65012342-1ee5-459b-ac4d-188bdd9b35a6.png)
However this number is actually valid for the day before.  Which is done with the apexchart and attribute data in the data_generator option:
![image](https://user-images.githubusercontent.com/4174578/150659804-2b1783e7-7c2c-4012-a543-a81a77cf1b70.png)

Because attribute data is solely present on the latest sensor status the integration will have to fetch historical data as far back as seems reasonable.  This is not as elegant as just skewing the history data one day using a transform.

**Comment by RomRider** [comment]
Good approach, however to avoid a breaking change, I'll introduce a new parameter instead of reusing `transform`

**Comment by kpoppel** [comment]
Still valid.

**Comment by kpoppel** [comment]
Bump.
