### ISSUE TITLE
Why isn't this card anywhere in my HACS ?

### ISSUE THREAD

**Issue by oywino** [RomRider/apexcharts-card#28]
I have HACS 1.10.1 installed in HA-Docker 2021.1.5
This card isn't anywhere to be found.
Please help ?

**Comment by RomRider** [comment]
Because I'm waiting for this PR to be merged for it to appear by default: https://github.com/hacs/default/pull/790 :shrug:

In the meantime you can add it manually using the repository URL 😉

**Comment by oywino** [comment]
Thank you 😊

**Comment by RomRider** [comment]
Seems resolved, I'll close this

**Comment by schmurtzm** [comment]
It could be nice to edit the main page because this sentence is misleading : "This card is available in HACS"  ;)

**Comment by jurgenhaas** [comment]
Looks like I was able to add my review which should help to get this across the finish line if a couple more of us did the same thing.

**Comment by oywino** [comment]
> Looks like I was able to add my review which should help to get this across the finish line if a couple more of us did the same thing.

Do you have a link to your review?

**Comment by RomRider** [comment]
Just go the PR https://github.com/hacs/default/pull/790 and approve it :)

**Comment by oywino** [comment]
I'd love to - but I don't think have write access (?)

**Comment by RomRider** [comment]
Seems like @jurgenhaas has write access, but I don't know why :)

**Comment by jurgenhaas** [comment]
I have no idea why, I'm not associated with HACS AFAIK but I see the link "Add your review" next to the "Review required" in red:

![Screenshot from 2021-02-03 10-07-09](https://user-images.githubusercontent.com/1475675/106723658-a1c86080-6607-11eb-867f-586dd9c013f7.png)

Maybe because I once contributed to HA core?

**Comment by RomRider** [comment]
https://github.com/hacs/default/pull/790 has been merged 🎉 (give it some hours until it is really available)

I can close this now.
