### ISSUE TITLE
Feature request: Hide legend when more than one series

### ISSUE THREAD

**Issue by magnusoverli** [RomRider/apexcharts-card#281]
Hi!

I cannot find an option for this, so I am going to assume it is not currently supported.
When I inject a second series to be shown in the chart, it automatically shows the legend as a footer in the card. Nothing wrong with that, but I would love to be able to hide it.

**Comment by magnusoverli** [comment]
I found the way to hide the legend through the `apex_config` option! Sorry! 
Closing.

**Comment by PulsarFX** [comment]
for reference:
```
apex_config:
  legend: 
    show: false
```

**Comment by Kickbut101** [comment]
Can this just be baked into the "normal options"? or put in the readme? I was looking for this option and it's odd that it's not listed on the readme page.
