### ISSUE TITLE
Wrong input_number visualization

### ISSUE THREAD

**Issue by gabrio79** [RomRider/apexcharts-card#287]
hello,
I'm trying to visualize an input number in a chart, but chart is not correctly displayed (both area and column type

apex-cahrt
![Schermata 2022-02-08 alle 11 23 58](https://user-images.githubusercontent.com/65911264/152968948-adce0cc1-60b5-4491-a539-ec9f6f467261.png)
![Schermata 2022-02-08 alle 11 30 08](https://user-images.githubusercontent.com/65911264/152969512-8141d968-e055-453d-bbfd-21b544643b7e.png)

input_numner value
![Schermata 2022-02-08 alle 11 24 22](https://user-images.githubusercontent.com/65911264/152968973-51875c47-0441-4cb3-b8d7-5e45bc3f57d4.png)

many thanks

**Comment by RomRider** [comment]
You'll have to use `curve: stepline` to display it the way you want.

**Comment by gabrio79** [comment]
you are right!
many thanks!!!!
