### ISSUE TITLE
Chart not updating when update_interval is set

### ISSUE THREAD

**Issue by Cynar** [RomRider/apexcharts-card#293]
**Checklist**
- [Y] I updated the card to the latest version available
- [Y] I cleared the cache of my browser
- [Y] I verified that I'm really running the lastest version in my browser console
- [Y] I checked if there is another issue opened with the same problem

**Describe the bug**
Graph does not auto update when update_interval is set. A page refresh works fine, and it updates with state change when update_interval is not set. Seen in both firefox and chrome browsers.

**Version of the card**
Version: 1.10.0

**To Reproduce**
This is the configuration I used:

type: custom:apexcharts-card
show:
  last_updated: true
update_interval: 5s
graph_span: 15m
series:
  - entity: sensor.air_quality_sensor_temperature

**Expected behavior**
Graph update at update_interval rate

**Desktop (please complete the following information):**
 - Browser Firefox (and Chrome)
 - Version 97.0.1 (64-bit)

**Comment by lloydbayley** [comment]
I've the same thing happening here. Are there any further updates about this?

**Comment by davidolrik** [comment]
Also seeing this in Safari and the Mac App

**Comment by RomRider** [comment]
Fixed in version 2.0.0
