### ISSUE TITLE
Chart Daily data being added from previous day without apparent reason.

### ISSUE THREAD

**Issue by Oretoh** [RomRider/apexcharts-card#300]
Chart keeps summing data from the previous day.

The green bar, consumed energy from panels, should have been reset when a new day.

However it summed the final value of the previous day twice and also summed the new value.

![image](https://user-images.githubusercontent.com/34142950/155853405-970f9f46-3302-4edc-b23f-8561bddee45d.png)

The sensor state and attributes being summed:
![image](https://user-images.githubusercontent.com/34142950/155853415-23418c5d-7eab-4456-af55-c2af6289dc79.png)

**Comment by miguelfreitaspt** [comment]
How can you know the energy consumed by your panels?

**Comment by Oretoh** [comment]
This appears to have fixed itself the next day, so I'll close it.

**Comment by Oretoh** [comment]
It happens from days to days, the symptom is the same and the entities remain the same apparently.

![image](https://user-images.githubusercontent.com/34142950/156876932-f76c2eb4-21de-48c6-80d8-d657695f766f.png)

![image](https://user-images.githubusercontent.com/34142950/156876951-8bd84606-7318-45f8-b001-427f9cfdf232.png)

**Comment by Oretoh** [comment]
Found the issue, somehow at 12h01 the apis get screwed and double the values for a second.

![image](https://user-images.githubusercontent.com/34142950/156877391-896e82ab-33b9-428e-a0df-013b6c993397.png)
