### ISSUE TITLE
Show state in header instantly

### ISSUE THREAD

**Issue by Mr-Groch** [RomRider/apexcharts-card#301]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
It is frustrating to wait to load whole graph to see actuall outside temperature :)

**Describe the solution you'd like**
Current state in header should be shown instantly, without waiting for whole graph

**Describe alternatives you've considered**
I can add new card with just one entity to show current state, but this would be wasting space in dashboard

**Additional context**
![image](https://user-images.githubusercontent.com/20594810/155954785-f731cb80-8fb3-41c6-b9ae-43bcfd8a0da8.png)

**Comment by Mr-Groch** [comment]
Request still valid :)

**Comment by RomRider** [comment]
Given you're not using `group_by`, I think using:
```
all_series_config:
  show:
    in_header: raw
```

is going to produce what you expect.

**Comment by Mr-Groch** [comment]
Yes, this is what I want to achieve!

Sorry, I haven't noticed that option earlier... This feature request is not valid then, thanks!
