### ISSUE TITLE
Use long term statistics instead of state only

### ISSUE THREAD

**Issue by fabiobrolo** [RomRider/apexcharts-card#308]
**Checklist**
- [x] I am running the latest version of the card
- [ x I checked if there isn't another feature request opened with the same request
- [xI checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I would like to use the long term statistics data, that are not purged.
Nowadays we can just use the states data, that by default is purged in 10 days.

**Describe the solution you'd like**
As mentioned before

**Describe alternatives you've considered**
None

**Additional context**
I would like to have a consumption/generation kwh  graph with data more than 10 days.

**Comment by matteocorti** [comment]
After upgrading and clearing all the caches, I still get only the last 10 days. How do I switch to the long term statistics?
