### ISSUE TITLE
Support template for color_threshold values

### ISSUE THREAD

**Issue by Inrego** [RomRider/apexcharts-card#312]
**Describe the solution you'd like**
Template support for color thresholds. For many sensors, the color thresholds make more sense if the value go too far from the average. For example energy usage. I can't set a fixed threshold for red and green, because normal energy usage varies by seasons. Instead I want to color red if energy usage is 10% higher than the last 30 day average.

**Describe alternatives you've considered**
I've considered using https://github.com/iantrich/config-template-card
But it's been working not so reliably for me in other cases, so I'd prefer not.

**Additional context**
I think the intent is clear. Ask if you have any questions.

**Comment by RomRider** [comment]
Would you have a sensor holding the last 30 days average?

**Comment by Inrego** [comment]
> Would you have a sensor holding the last 30 days average?

Sorry didn't see your reply. Yes, I would use a statistics sensor to hold the average value.

**Comment by jippi** [comment]
I have this need as well - i have the low/min price of energy in a sensor along with the current price, and would love to use `color_threshold` for low/high/mean coloring

**Comment by jippi** [comment]
no

**Comment by jippi** [comment]
please stop your self lol

**Comment by jippi** [comment]
no

**Comment by Tom-ahawk** [comment]
I hope this feature will come so another sensor can dictate the threshold color like:

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 1d
span:
  start: day
series:
  - entity: sensor.nordpool_kwh_oslo
    data_generator: |
      return entity.attributes.raw_today.map((entry) => {
        return [new Date(entry.start), entry.value];
      });
    type: column
    float_precision: 2
    show:
      extremas: true
    color_threshold:
      - value: "{{ state_attr('binary_sensor.nordpool_kwh_cheapest_4_hours', 'cost_now') }}"
        color: blue
   - ....
```

**Comment by newlund** [comment]
I would also love to be able to assign colors more dynamically. Would make this a perfect card. :)

**Comment by kanttti** [comment]
I agree. Would be a perfect card if the colors could be assigned dynamically.

**Comment by frebergguru** [comment]
I would love that too! :)

**Comment by jippi** [comment]
this is kinda stupid at this point...

**Comment by Olum-hack** [comment]
I would also like to have that feature.
