### ISSUE TITLE
Second y-axis stops auto-scale from working (y-axis scale always starts with 0) #158

### ISSUE THREAD

**Issue by mohit-sojitra** [RomRider/apexcharts-card#313]
REFER: https://codepen.io/mohit-sojitra/pen/wvpWxZw

#158 still not solved

**Checklist**
- [x] I updated the card to the latest version available
- [ ] I cleared the cache of my browser
- [ ] I verified that I'm really running the lastest version in my browser console
- [ ] I checked if there is another issue opened with the same problem

**Describe the bug**

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
This is not the repo for the apexcharts library but for a home assistant card. You probably wanted to open an issue on the apexcharts library repo, no?
