### ISSUE TITLE
Implementation of external databases (e.g. InfluxDB)

### ISSUE THREAD

**Issue by AleXSR700** [RomRider/apexcharts-card#322]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
The database in HA does not store long term data e.g. for energy consumption or other data that needs to be evaluated over longer time periods. It is also not suited to do so.
Many, maybe most, users switch to additional databases such as InfluxDB.

Right now this data cannot be accessed in the ApexCharts without high levels of code adjustments (impossible for beginners and difficult to maintain for advanced users). These adjustments also prevent the user from using great additional add-ons such as auto-entities.

**Describe the solution you'd like**
Please, add an option to access InfluxDB data. Other add-ons like Grafana only need user name and password, plus database name and address.
Maybe this could be implemented in ApexCharts also? All one would need would then be an additional vairable at the beginning of the card such as "db" where you specify whether to use "db :HA" or "db: influxdb" and the respective entities will be searched for in that DB only.

I hope it is clear what I mean. Basically a variable that defines the source database and the rest stays the same. Variable names in both databases are the same anyway as the data is simply a permanent copy of the short-term HA DB data.

**Describe alternatives you've considered**
There are none :(
Grafana is an alternative, but it is faaaar less versatile and cannot be implemented into lovelace as easily and beautifully as ApexCharts.

**Additional context**
None.

Thank you for your consideration
Alex

**Comment by RomRider** [comment]
Yes, I'm planning to implement that. Not yet sure what it will look like though :)

**Comment by AleXSR700** [comment]
Thank you very much, that is great news!

By the way, PostgreSQL or whatever database you think is best, would be just as perfect. Maybe even simpler to implement given SQL.
Just saying: InfluxDB was just an example and not part of the wish :)

Looking forward to it :)

**Comment by RomRider** [comment]
It's going to be influxdb. Connecting to anything else with javascript is going to be a PITA

**Comment by melwinek** [comment]
Maybe you can do postgresql too. For those who use LTSS.

**Comment by RomRider** [comment]
So I gave some thoughts about this and I won't move forward for now with the request as it will require the browser to connect to the database directly and that wouldn't work remotely as most of us will not expose their influxdb (or whatever else) on the internet. So I will need to develop a custom_component for HA which will proxy requests to influxdb (or whatever else) while being authenticated to HA.

**Comment by AleXSR700** [comment]
Hello Jerome,
why would the database need to be exposed to the internet?
Influxdb is available to HA and without additional exposure of the database, the companion app can access the database (e.g. via Grafana).

An alternative would be MariaDB. It directly replaces the normal SQLite. So whenever the SQLite worked, MariaDB will also work.
I think it is also better integrated than InfluxDB.

**Comment by RomRider** [comment]
Grafana is exposed through home assistant and Grafana runs a proxy to access influxdb from the Grafana web interface (it's the same thing I'd have to implement as a custom component)

**Comment by AleXSR700** [comment]
Thank you @RomRider 
I am not running Grafana either. I much prefer working with ApexCharts. I was just wondering why the two are different (thank you for the explanation).

It would be best if this were implemented in HA core, but there is no chance of that ever happening. Guess it is Grafana or nothing right now for long-term data :(

**Comment by RomRider** [comment]
I might use Grafana's proxy instead of reimplementing it, but that means Grafana will have to be exposed over the internet which is not ideal.

**Comment by AleXSR700** [comment]
Does Grafana's proxy need to be exposed over the internet or just in the LAN?
I can only access my HA locally (unless I use a VPN to tunnel to my RPi), but Grafana etc. still works. Grafana is accessing the database locally via the internal IP (which is only accessible from LAN, not internet).

**Comment by RomRider** [comment]
**Your browser** will require **direct access** to grafana (the same way it would require direct access to influxDB or mariaDB if I implement direct connection without proxy). So if your home assistant is exposed over the internet, and  you access it remotely, your grafana would also require to be exposed over the internet.

**Comment by AleXSR700** [comment]
Is there a way to selectively not expose Grafana to the internet if the rest of HA is exposed? Or is Grafana not automatically exposed when HA is exposed?

**Comment by RomRider** [comment]
Grafana is not always part of HA as I told you above. It is exposed through HA when you installed it with HA. It's not my case for eg.

**Comment by AleXSR700** [comment]
Ah, okay, then I misunderstood. I thought the problem was, that Grafana needed to be exposed to the internet , i.e. not blocked. You meant "it has to be installed".
So you would not implement the same proxy approach but try to piggy-back off of Grafana directly.

**Comment by RomRider** [comment]
Yes, correct, consume grafana's proxy directly.

**Comment by AleXSR700** [comment]
Since ApexCharts can already access all databases without any modification by using JavaScript templating, would it not be possible to implement kind of an "automatic templating"? Kind of a code translation for the entity only?
Do you know what I mean?

**Comment by RomRider** [comment]
I'm not sure I get your point.

**Comment by AleXSR700** [comment]
@koying once posted some code that lets you access entities stored in influxdb from ApexCharts. So it does not require proxies or anything else.

```
type: 'custom:apexcharts-card'
graph_span: 36h
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.hue_sensor1_temperature
    data_generator: |
      console.log(start);
      var params = new URLSearchParams({
          pretty: true,
          db: "home_assistant",
          q: "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\" = 'mijia_out_temp' OR \"entity_id\" = 'exterieur_temperature') AND time >= '" + start.toISOString() + "' AND time <= '" + end.toISOString() + "' GROUP BY time(10m) fill(none)"
          });

      var myInit = { method: 'GET',
                      headers: {
                          'Accept': 'application/json',
                      },
                      mode: 'cors',
                      cache: 'default' 
      };

      const request = async () => {
          var result = [];
          const response = await fetch('http://influxdb.lan:8086/query?' + params, myInit)
          const json = await response.json();
          if (json["results"] && json["results"][0] && json["results"][0]["series"]  && json["results"][0]["series"][0] && json["results"][0]["series"][0]["values"]) {
              for(var val of json["results"][0]["series"][0]["values"]) {
                  result.push([new Date(val[0]), val[1]]);
              }
          } else {
              console.log("error: " + json)
          }
          return result;
      }
      return request();
```

This is too complex for the less experienced user (like myself), but maybe to an expert like you, it is possible to use the same approach to automatically "translate" the entity the user enters into this kind of database query code?

So if the user started his ApexCharts card with
```
type: 'custom:apexcharts-card'
graph_span: 36h
database: influxdb    #or MariaDB or whatever)
```
then 
```
series:
  - entity: sensor.hue_sensor1_temperature
```
gets re-written internally to the above code with the data generator.

Sorry, maybe the above code is not a good example. I do not fully understand all parts of it yet. So maybe it does much more than simply get the entity data from influxdb.

**Comment by RomRider** [comment]
I know this code, but again, this requires direct access to influxDB from your web browser. Javascript runs in your web browser. Si that won't work remotely over the internet unless InfluxDB is also exposed directly to the internet which no-one will want to do !

**Comment by AleXSR700** [comment]
Okay, this is something I have no experience with since I tunnel using Zerotier and that way I do not need to expose anything because I am essentially accessing locally.
I assume these limitations also apply to the companion app as it (at least used to) be basically a browser packed into an app.

But I do wonder, who has their HA exposed to the internet but somehow does not have his database exposed.

As soon as I can access my HA setup, I can access every setting, every addon etc., so I can also access my database. Be it directly or indirectly, makes no difference security wise.

**Comment by RomRider** [comment]
As I told you, for eg. I don't run influxDB as part of HA. It's running separately on a separate machine so it's not "protected" by HA's ingress mechanism on which you need to be authenticated.

**Comment by AleXSR700** [comment]
Could this be solved if HA core implemented its own database proxy? If Grafana is doing it already and Grafana code is available, would this not be a relatively straight forward dedicated add-on?

**Comment by RomRider** [comment]
No, it's not easy.

**Comment by koying** [comment]
> The database in HA does not store long term data e.g. for energy consumption or other data that needs to be evaluated over longer time periods.

I've been pulled here by the tag ;)
This has a wrong assumption. HA now DO store long-term statistics, and @RomRider just merged support for it in apexchart.

Going through influxdb is no more mandatory for long term, and charting of those should go to grafana

**Comment by AleXSR700** [comment]
Not sure I understand the new implementation in of long-term statistics in ApexCharts.
[https://github.com/RomRider/apexcharts-card/tree/dev#statistics-options](url)

So I have to manually set whether the chart is using long-term or short-term data?
I, e.g. use input_select and the span option to adjust the period to display on-the-fly. If I have to define whether the data is coming from LTS or STS, then this will not work, correct?
Or can I simply always set the statistics option and that will then take any data (be it the last 5 min or the last 500 days) from my MariaDB instead of SQLite?
Because there should be no SQLite data to which to align if I am using either/or database.

**Comment by RomRider** [comment]
I think you're mixing up quite a lot of different things.

Long term statistics support is the same as the statistics card consuming HA statistical data. Statistical data are computed by HA automatically for most of the sensors. 

And just FYI, MariaDB and sqlite can't coexist as a data backend for HA. It's one or the other.

**Comment by AleXSR700** [comment]
Okay, then I do not want long term statistics. I want my long term data.
I want to plot all the data I have generated, independent of whether HA considers it to be a statistic or not.
That to me is the goal in having a database. Having all data ready for access, independent of what the system thinks is important or not.

**Comment by koying** [comment]
> I want to plot all the data I have generated, independent of whether HA considers it to be a statistic or not.

Then set `auto_purge` to false in `recorder:`. But HA stores a lot of data, so your db size will explode.

HA came up with aggregated long-term statistics to mitigate the need for long-term data. The use-cases for going back to a specific value in history are rather limited,.

Even Influxdb recommends to set retention policies and to aggregate historical data with continuous queries, so infinite detailed data is not really a thing...

**Comment by AleXSR700** [comment]
I am not yet woried about the db size as I am only tracking very few and limited data sources.
But I do want to be able to track short time frames within these sets. So I want to be able to see e.g. drop-outs in signal (which are usually only seconds or minutes) and similar abnomalies.

Anyway, I will set auto_purge to false. This should then only track what I included.

But since I am then using MariaDB as sole database, all this data should always be available to ApexCharts without any json or javascript, correct? And only statistics card will be unable to handle data that it finds corrupt (e.g. missing state attribute). But ApexCharts should ignore it and use any available data?
