### ISSUE TITLE
Support for actions on title

### ISSUE THREAD

**Issue by CDRX2** [RomRider/apexcharts-card#323]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Not a problem, but currently the header actions are only supported on the states in the header.

**Describe the solution you'd like**
I'd like the header actions to be extended to the title of the card as well, for use cases where states in the header are not displayed.

**Describe alternatives you've considered**
None.

**Additional context**
Screenshot of a few cards where header actions on title would be convenient (from the card docs actually):
![image](https://user-images.githubusercontent.com/35002821/162609400-db4537cd-cb65-47f9-a1e0-f21c0b0c648d.png)
radialBar, pie, donut don't have states in their headers, so supporting header actions on the titles would be great.

**Comment by CDRX2** [comment]
Thank you for the release. However, it seems that there is a bug, here's what I get when adding title_actions to all_series_config:
![Untitled](https://user-images.githubusercontent.com/35002821/164950394-1896bef0-c49d-4e04-8d8c-8b8b48b8a196.png)
Running v 2.0.0 of apexcharts-card according to Chrome Dev tools. Did I miss something?

**Comment by RomRider** [comment]
That's not where it's supposed to be, title_actions is in the header config section

**Comment by CDRX2** [comment]
Right, wrong syntax in the middle of the night, not a good mix. Works very well, thank you!
