### ISSUE TITLE
2.0 Broke a previously working chart implementation

### ISSUE THREAD

**Issue by KairuByte** [RomRider/apexcharts-card#331]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
```
/// apexcharts-card version 2.0.1 /// value.series[1] is not a ChartCardSeriesExternalConfig
    value.series[1].extend_to_end is extraneous
    value.series[1].extend_to_end is extraneous```

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
header:
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 150px
  xaxis:
    labels:
      show: false
    crosshairs:
      show: false
    axisBorder:
      show: false
    axisTicks:
      show: false
  legend:
    show: false
    showForNullSeries: false
    showForZeroSeries: false
yaxis:
  - id: temperature
    show: false
    min: '|-1|'
    max: '|+1|'
    apex_config:
      labels:
        show: true
      forceNiceScale: true
  - id: heating
    min: 0
    max: 1
    show: false
    apex_config:
      labels:
        show: false
      forceNiceScale: false
      showForNullSeries: false
      showForZeroSeries: false
series:
  - entity: sensor.office_temperature
    yaxis_id: temperature
    type: area
    fill_raw: last
    show:
      name_in_header: false
  - entity: binary_sensor.office_heating
    yaxis_id: heating
    transform: 'return x === ''on'' ? 1 : 0;'
    type: area
    curve: stepline
    color: red
    extend_to_end: true
    stroke_width: 0
    show:
      in_header: raw
      legend_value: false
      name_in_header: false
```

**Expected behavior**
Previously, this worked. The chart rendered. Though, as mentioned in #234 (which seems to have staled out) there was a slight issue with the final output.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: A handful of the latest versions. Assume latest available.

**Comment by RomRider** [comment]
Read the release notes and you'll see that this option is deprecated and replaced by another one.

**Comment by KairuByte** [comment]
Ah, that solved it. Apologies, I read extraneous as "not needed" not as "will break". And I did miss the breaking change alert in the release notes somehow.
