### ISSUE TITLE
series: float_precision: rounds off last digit if '0'

### ISSUE THREAD

**Issue by GitHubGoody** [RomRider/apexcharts-card#334]
The title says it all, but as an example, with a float_precision of 3, the value of 0.420 is displayed as 0.42. Please don't remove the final digit.

**Comment by blackburn77** [comment]
I would also very much like this to be fixed. For example my solar panels "Daily Generation" now goes 8.9 -> 9 -> 9.1 while the builtin Entity Card keeps the decimal and shows "9.0".

**Comment by RomRider** [comment]
Just for the sake of completeness, where does this happen?
Header? Legend? Tooltip?

There's a template to complete when you file a bug, it's there to help me... Please don't remove it.

**Comment by GitHubGoody** [comment]
When the Database grows to 0.430GB, it will display as 0.43 in both of these locations. I could not verify what displays when hovering over the line because it only displays for the primary y-axis (another bug?).
![image](https://user-images.githubusercontent.com/46235745/166145054-5cfbc8cc-4ada-497f-be5d-48ed2de29ce2.jpeg)

**Comment by blackburn77** [comment]
It's the same in both the header and legend. I created a dummy apex card of the load on my main fuses just to compare it to the "Gauge" card which shows "5.0" (all built-in cards like "Entity", "Entities" and "Glance" show 5.0)

![apex](https://user-images.githubusercontent.com/6384288/166162258-1cf77940-06a6-4110-b731-59669cbb0394.jpg)

![gauge](https://user-images.githubusercontent.com/6384288/166162267-cb0a9458-1b2e-4418-89cd-1b99e78e074e.jpg)

**Comment by GitHubGoody** [comment]
I don't think this has been addressed yet since the last release (4/24) predates this post. Silly robot.
