### ISSUE TITLE
apexcharts-card error: no graphs are available 

### ISSUE THREAD

**Issue by enricocelegon** [RomRider/apexcharts-card#335]
**Checklist**
- apexcharts-card version 2.0.1
- [ ] I cleared the cache of my browser
- [ ] I verified that I'm really running the lastest version in my browser console
- [ ] I checked if there is another issue opened with the same problem

**Describe the bug**
/// apexcharts-card version 2.0.1 /// value.all_series_config is not a ChartCardAllSeriesExternalConfig; value.all_series_config.extend_to_end is extraneous

**Version of the card**
Version: 2.0.1

**To Reproduce**
After upgrade from apexcharts 1.0.0 to 2.0.0 or 2.0.1 all graphs disappear and only source code are visible.
This issue is present with any browser (after cache clear also)
```

**Desktop (please complete the following information):**
 - Browser: chrome, firefox
 - Version: all version

**Smartphone (please complete the following information):**
 - Device: Samsung S6 edge +

**Comment by RomRider** [comment]
Please read the release notes and you'll see that extend_to_end has been deprecated and replaced.
