### ISSUE TITLE
Display a different sensor value in the center of the Donut?

### ISSUE THREAD

**Issue by krasatos** [RomRider/apexcharts-card#338]
**Checklist**
- [ x ] I am running the latest version of the card
- [ x ] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Describe the solution you'd like**
I have a donut chart showing all my devices' live power consumption.
I would like to add the total power consumption in the center of the donut.

This is a sensor that is not included in the donut.
I saw it is possible in the radial bar, but only in values that are included in the chart.

Is that possible?

**Additional context**

![image](https://user-images.githubusercontent.com/1773624/168416314-3ace5c4c-bc7c-4a1b-b09b-253fa9ebfb5e.png)

**Comment by EmJay276** [comment]
You can already do this by adding a apex configuration
```
    apex_config:
      legend:
        show: false
      dataLabels:
        formatter: |
          EVAL:function(value) {
            return value.toFixed(1) + "%";
          }
      tooltip:
        enabled: false
      plotOptions:
        pie:
          expandOnClick: false
          donut:
            labels:
              show: true
              total:
                show: true
                color: var(--accent-color)
                label: Gesamt
                fontWeight: bold
                formatter: |
                  EVAL:function(w) {
                    return w.globals.seriesTotals.reduce((a, b) => {return a + b}, 0).toFixed(1) + " kWh";
                  }
              value:
                formatter: |
                  EVAL:function(value) {
                    return parseFloat(value).toFixed(2) + " kWh";
                  }
```

**Comment by itsboo07** [comment]
> formatter: |
>                   EVAL:function(w) {
>                     return w.globals.seriesTotals.reduce((a, b) => {return a + b}, 0).toFixed(1) + " kWh";
>                   }

how does this work for you. I tried the same exact code with my sensors but it shows only the total in center rather than 1st sensor state. can you help?
`type: custom:apexcharts-card
chart_type: donut
header:
  show: true
  title: RescueTime
  show_states: true
  colorize_states: true
apex_config:
  dataLabels:
    enabled: false
    formatter: |
      EVAL:function(value) {
        return value.toFixed(0) + " %";
      }
  legend:
    show: false
  plotOptions:
    pie:
      donut:
        size: 65%
        background: transparent
        labels:
          show: true
          total:
            fontSize: 18px
            fontWeight: 79
            color: '#009dff'
            show: true
            label: Productivity Score
            formatter: |
              EVAL:function(w) {
                return w.globals.seriesTotals.reduce((a, b) => {return a + b}, 0).toFixed(1) + " kWh";
              }
            value:
              formatter: |
                EVAL:function(value) {
                  return parseFloat(value).toFixed(0) + " kWh";
                }
series:
  - entity: sensor.unfinished_tasks
    name: Productivity Score
    color: rgba(255, 255, 0,.7)
    show:
      in_header: true
      in_chart: false
  - entity: sensor.very_productive_time
    name: Very Productive
    color: rgb(0, 85, 196)
  - entity: sensor.productive_time
    name: Productive
    color: rgb(61, 128, 224)
  - entity: sensor.neutral_time
    name: Neutral
    color: rgb(177, 193, 191)
  - entity: sensor.distracting_time
    name: Distracting
    color: rgb(220, 104, 90)
  - entity: sensor.very_distracting_time
    name: Very Distracting
    color: rgb(214, 24, 0)
style: |
  :host {
    font-size: 14px !important;
    line-height: 18px !important;
   }
  #state__value > #state {
    font-size: 2.2em !important;
  }
  #state__value > #uom {
   font-size: .9em !important; 
  }
  #state__name {
    font-size: .7em !important; 
  }
`
it should show 1 but its showing the total
![image](https://user-images.githubusercontent.com/87331871/190927099-41fc5682-d7d9-4ca6-937b-ce33027d6266.png)

**Comment by EmJay276** [comment]
> - entity: sensor.energy_total
>         show:
>           in_chart: false
>         name: Gesamt

I additonally have a sensor with the total value which is not shown in the Donut graph to display it in the legend

**Comment by itsboo07** [comment]
> > * entity: sensor.energy_total
> >   show:
> >   in_chart: false
> >   name: Gesamt
> 
> I additonally have a sensor with the total value which is not shown in the Donut graph but displayed it in the legend


i think its not possible to add a custom sensor value in center as of now and looks at your donut chart again. i could see its not displaying value of `entity: sensor.energy_total` rather its showing total

**Comment by EmJay276** [comment]
The value in the middle of the chart is created by this code

> plotOptions:
>         pie:
>           expandOnClick: false
>           donut:
>             labels:
>               show: true
>               total:
>                 show: true
>                 color: var(--accent-color)
>                 label: Gesamt
>                 fontWeight: bold
>                 formatter: |
>                   EVAL:function(w) {
>                     return w.globals.seriesTotals.reduce((a, b) => {return a + b}, 0).toFixed(1) + " kWh";
>                   }

What is not possible is to add an additional sensor in the legend by this method.

**Comment by itsboo07** [comment]
Yes but this shows only the total of all value ...does not show specific value of any entity ...can you once again check with your donut chart ?

**Comment by EmJay276** [comment]
@itsboo07 Ah I see. I don't know how to display a completly different sensor value of another entity.
