### ISSUE TITLE
offset not working in data_generator

### ISSUE THREAD

**Issue by htmltiger** [RomRider/apexcharts-card#34]
I want to use the same data to compare with previous 7 days.
Changing offset of a series to any value other than 0 makes the series stop displaying.
Also tried changing graph_span  and span.offset data but no luck.
Am I doing it correctly?

v1.4.0-dev.4
![offset](https://user-images.githubusercontent.com/1429451/106481500-695c4180-64a4-11eb-94cb-469401d661db.gif)

```
type: 'custom:apexcharts-card'
series:
  - entity: sensor.daily_energy
    name: A
    type: column
    offset: '-0day'
    data_generator: |
      return entity.attributes.json.map((entry) => {
        return [new Date(entry.d), entry.s];
      });
  - entity: sensor.daily_energy
    name: B
    type: column
    offset: '+0day'
    data_generator: |
      return entity.attributes.json.map((entry) => {
        return [new Date(entry.d), entry.s];
      });
graph_span: 20day
span:
  start: day
  offset: '-20day'
apex_config:
  plotOptions:
    bar:
      columnWidth: 70%
  dataLabels:
    enabled: false
```
I am using https://github.com/crowbarz/ha-sql_json to fetch the data from sql

Thanks for making a great addon.

**Comment by RomRider** [comment]
That is kind of expected with `data_generator` and `offset`. Maybe I should update the doc.

I'll see what I can do, but for now, you should offset the value yourself in data_generator and not rely on `offset`:
Eg to display yesterday's data on the current timeframe :
```js
      return entity.attributes.json.map((entry) => {
        return [new Date(entry.d).getTime() + 1000*60*60*24, entry.s];
      });
```

**Comment by htmltiger** [comment]
Works great, thanks for the quick support.
