### ISSUE TITLE
Brush selection span is ignored, startup with zero length

### ISSUE THREAD

**Issue by Heppi911** [RomRider/apexcharts-card#342]
[ x] I updated the card to the latest version available
    [x ] I cleared the cache of my browser
    [x ] I verified that I'm really running the lastest version in my browser console
    [x ] I checked if there is another issue opened with the same problem

Describe the bug
brush:
  selection_span: 2h
is ignored in newest version (v2.01) Bug was not present in v2.0
Now the display length is something about zero. Without draging a span unusable. 

Version of the card
Version: 2.01

Expected behavior
old behaviour. ;-)

Desktop (please complete the following information):

    Browser firefox

Smartphone (please complete the following information):

    Device: [e.g. iPhone12]
    Homeassistant App

**Comment by argoon38** [comment]
this bug seems still present in v2.1.2

`experimental:
  brush: true
brush:
  selection_span: 24h
graph_span: 160h`

In the preview, it looks correct.
But when I leave lovelace edit mode, the selection_span is considered as 0.
