### ISSUE TITLE
enhancement header size

### ISSUE THREAD

**Issue by scooper1** [RomRider/apexcharts-card#35]
thanks for adding the header to the card
could add the h1 tag so that it picks up the standard Lovelace card size

**Comment by RomRider** [comment]
A bit more explanation with maybe a screenshot of what you expect would be helpful, thanks :)

**Comment by scooper1** [comment]
thanks for good work on this card 
the original graph that I am updating
<img width="374" alt="origgraph" src="https://user-images.githubusercontent.com/14822945/106511047-9e2dc000-64c7-11eb-9a23-d074f9b4f781.png">
example showing normal lovelace header size
<img width="386" alt="header" src="https://user-images.githubusercontent.com/14822945/106511049-9ec65680-64c7-11eb-97d9-a68d0ea61481.png">
new card showing small header - which i can not change even with apex config 
also shows the scaling problem and zero value dropout raise in another issue
<img width="395" alt="newgraph" src="https://user-images.githubusercontent.com/14822945/106511051-9f5eed00-64c7-11eb-9e55-a22cb59ecede.png">

**Comment by fa-ve** [comment]
Would be also nice if we can modify the font size in the header, like in mini graph card..

**Comment by RomRider** [comment]
I'll add that to the next release
