### ISSUE TITLE
Display label is cut

### ISSUE THREAD

**Issue by 03397** [RomRider/apexcharts-card#369]
When you move your cursor at the very beginning or the very end of the graph using your mouse the timestamp label is cut since it stops at end of the graph. See attached
![graph_label](https://user-images.githubusercontent.com/6150853/180179202-f1c6fca0-7b79-4b48-9b82-582529b31e58.JPG)

**Comment by 03397** [comment]
Still there

**Comment by 03397** [comment]
Still valid.
Is this still supported?

**Comment by 03397** [comment]
Still there

**Comment by RomRider** [comment]
I can either let it display and it will bug when on the right of the screen or keep it like that.
You can use card-mod to modify the css overflow property of the card if you want.

**Comment by 03397** [comment]
@RomRider 
Is this configurable?
Can I disable this label from the x axis since this displays the same information as the other label?
