### ISSUE TITLE
Horizontal paning (like in plotly charts)

### ISSUE THREAD

**Issue by AleXSR700** [RomRider/apexcharts-card#378]
**Checklist**
- [x ] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

I am using rigid input select to change the time span displayed. This is very unflexible and requires additional "coding" of input selects.

**Describe the solution you'd like**

Plotly charts for HA supports paning, zooming etc. Whilst both would be cool to have, paning horizontally on the fly would be the most important new feature for me :-)

https://github.com/dbuezas/lovelace-plotly-graph-card

**Describe alternatives you've considered**

Using plotly charts, but I love apexcharts versatility too much. 

**Additional context**

**Comment by AleXSR700** [comment]
I would like to update my request after finding that in theory it is supported.

So, this feature exists but it is disabled for mobile devices. I think the majority of Home Assistant users uses mobile/tablet devices.

Would it please be possible to disable tooltips (which seemingly are preventing the paning) and instead activate paning for mobile devices?

**Comment by nitobosch** [comment]
+1 any updates for this?
