### ISSUE TITLE
Charts disappear after HA update or restart

### ISSUE THREAD

**Issue by DavidFW1960** [RomRider/apexcharts-card#39]
OK some weirdness I noticed yesterday. Just installed latest beta of HA and it’s zeroed out (most) all of my graphs:
![image](https://user-images.githubusercontent.com/36390762/106675414-3089ad00-6609-11eb-9a81-a6ad02734cba.png)
The entities are in recorder and I can see states graphed for the entity eg:
![image](https://user-images.githubusercontent.com/36390762/106675467-3ed7c900-6609-11eb-93e7-03e292e5386f.png)
Latest 1.4 version

**Comment by RomRider** [comment]
For posterity:
* Happening following a HA reboot.
* states where `unavailable`
* HA draws a line between the last state and the next `unavailable`, ApexCharts doesn't
Solution is to fill missing values with the last valid one.

Fixed starting with 1.5.0-dev.1 (`fill_raw` feature) :)
