### ISSUE TITLE
question : best practice to determine version of apexcharts-card downloaded and running in browser

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#40]
This is probably only a problem for 'stuck in mud' folks like me that do things on command line. However, what is best practice to check the version of apexcharts-card that is downloaded to HA server and running in current browser?

I currently use a combo of:
```
user@ubuntu-macmini2012:~/homeassistant/www/custom-lovelace/apexcharts$ grep -o -P '.{0,20}1\.4\..{0,20}' apexcharts-card.js
ate,i.card_version="1.4.0",0!==i.data.length
hSpan,card_version:"1.4.0",last_fetched:new
pan:0,card_version:"1.4.0",last_fetched:new
APEXCHARTS-CARD %c v1.4.0 ","color: orange;
th("-raw")?t:ae(t);"1.4.0"!==i.card_version&
```

and check the chrome javascript console. But as is shown in the console out, again probably only for old fart yaml editors such as I, need to make sure the yaml is updated (see picture below), clear the browser cache, exit chrome, restart chrome, reload resource in HA and yeah! I am current.

Tips? other than I am candidate for HomeKit? ;-)

If there was a clear unique version value to grep for in .js file, that would be a helpful tip.

Thanks for your great work, so useful!

<img width="786" alt="apex-version" src="https://user-images.githubusercontent.com/1409547/106687358-d6450980-6580-11eb-89e0-2316f4d9b68c.png">

**Comment by RomRider** [comment]
What you see on the right of the console is the URL you configured in your resources. That is irrelevant, it just help your browser to not use the cached version as soon as you change the value.
Changing the value `?v=1.2.0` in the resources then doing a "reload resources" will allow you to avoid clearing the cache. The value doesn't mean anything, you could put `?asdfeworiuweoi` and it would have the same result :)

Best way is still using HACS... as the files are served from an endpoint which is not cached.

The only one which is relevant is the one displayed on the left, this is the version actually running in your browser (this one only, other ones may still have an old cached version):
![image](https://user-images.githubusercontent.com/21064206/106687745-0914ef00-65cd-11eb-937c-d9d7ab264850.png)

There's no way to grep any version from the file (it would work once but not for the next version) as it is compiled so variable names will change every time.

**Comment by deepcoder** [comment]
Thank you for the info!

Sorry for my ignorance, does HACS support installing development releases?

'Best way is still using HACS... as the files are served from an endpoint which is not cached.'

**Comment by DavidFW1960** [comment]
there is an option when you go to reinstall a card in HACS to enable beta releases
![image](https://user-images.githubusercontent.com/36390762/106695274-5d03f000-662e-11eb-9cb6-6e5d7748d023.png)
