### ISSUE TITLE
Cant get Distributed Columns work

### ISSUE THREAD

**Issue by itsboo07** [RomRider/apexcharts-card#400]
**Checklist**
- [Y ] I updated the card to the latest version available
- [ Y] I cleared the cache of my browser
- [ Y] I verified that I'm really running the lastest version in my browser console
- [ Y] I checked if there is another issue opened with the same problem

**Describe the bug**
Cant get the Distributed Columns work and custom categories for x axis does not work either. 
Reference: [Distributed Columns](https://apexcharts.com/javascript-chart-demos/column-charts/distributed/) 

**Version of the card**
Version: v2.0.1

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**
What actually i needed
![image](https://user-images.githubusercontent.com/87331871/190926410-fd4f468e-55ce-42da-9f7a-c63d2208a741.png)

**Expected behavior**
Hoping to get this fixed or not sure am i doing someting wrong

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
Really thank everyone who made this project , this is really great and love this card. hoping to see distributed columns added

**Comment by RomRider** [comment]
This is not possible with the current implementation of the card.
What would be your use case?
