### ISSUE TITLE
Home Assistant - Dwains Dashboard - value.col_span is extraneous value.col_span_lg is extraneous value.col_span_xl is extraneous

### ISSUE THREAD

**Issue by josefzahner** [RomRider/apexcharts-card#402]
I know you are not involved in Home Assistant nor Dwains Dashboard. However may be you have a good idea to solve my issue, as I'm trying to add your card to the dashboard and the preview works, but after submitting the YAML code I'm getting the error

`/// apexcharts-card version 2.0.1 /// value.col_span is extraneous value.col_span_lg is extraneous value.col_span_xl is extraneous`

HA Links to Dwains Dashboard. I'm not alone with the issue...
https://community.home-assistant.io/t/dwains-dashboard-1-click-install-dashboard-for-desktop-tablet-and-mobile-v3-1-0/168593/2235

Do you have an idea how to fix this? In the dashboard I've to choose the column & row size, I don't know how to override that...

Error:
![Screenshot 2022-09-20 at 22 20 00](https://user-images.githubusercontent.com/33521474/191358430-d5ef7929-553b-4f32-bbff-88a4d74e65fb.png)

**Comment by RomRider** [comment]
You can disable configuration checks with:
```
experimental:
  disable_config_validation: true
```

**Comment by josefzahner** [comment]
Thank you so much - it works :-)!
