### ISSUE TITLE
Not able to put graph in front of column 

### ISSUE THREAD

**Issue by kimstor1435** [RomRider/apexcharts-card#403]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
Not able to put graph in front of column, if I switch to Area mode the graph will be behind
![image](https://user-images.githubusercontent.com/61433087/191672799-f601f018-2199-4bab-890e-009d390dcc74.png)

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
type: custom:apexcharts-card
update_interval: 1m
header:
  show: true
  title: Forbruk og pris
  show_states: false
  colorize_states: false
now:
  show: true
  label: Nå
graph_span: 96h
span:
  start: day
  offset: '-72h'
apex_config:
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 10
        - 50
        - 75
        - 1000
  dataLabels:
    enabled: true
  legend:
    show: false
yaxis:
  - id: kwh
    apex_config:
      opposite: false
      forceNiceScale: true
      decimalsInFloat: 1
      labels:
        show: true
      title:
        text: Forbruk (kWt)
  - id: price
    apex_config:
      min: 0
      opposite: true
      forceNiceScale: true
      decimalsInFloat: 2
      labels:
        show: true
      title:
        text: Pris (NOK)
series:
  - entity: sensor.accumulated_consumption_current_hour_glimmerhome
    yaxis_id: kwh
    stroke_width: 2
    opacity: 0.02
    name: Forbruk
    type: column
    color: rgb(3, 169, 244)
    extend_to: false
    show:
      legend_value: false
    group_by:
      func: max
  - entity: sensor.nordpool_kwh_oslo_nok_2_10_025
    yaxis_id: price
    stroke_width: 2
    opacity: 0.1
    name: Igår
    type: area
    curve: stepline
    extend_to: false
    offset: '-1min'
    show:
      in_header: false
      legend_value: false
      in_chart: true
      extremas: false
      offset_in_name: false
    color: tomato
  - entity: sensor.nordpool_kwh_oslo_nok_2_10_025
    yaxis_id: price
    stroke_width: 2
    opacity: 1
    name: Idag
    type: area
    curve: stepline
    extend_to: false
    offset: '-1min'
    show:
      in_header: false
      legend_value: false
      extremas: false
      offset_in_name: false
    color: tomato
    data_generator: |
      return entity.attributes.raw_today.map((p) => {
        return [new Date(p.start), p.value];
      });
  - entity: sensor.nordpool_kwh_oslo_nok_2_10_025
    yaxis_id: price
    stroke_width: 2
    opacity: 1
    name: I morgen
    type: area
    curve: stepline
    offset: '-1min'
    show:
      in_header: false
      legend_value: false
      extremas: false
      offset_in_name: false
    color: tomato
    data_generator: |
      return entity.attributes.raw_tomorrow.map((p) => {
        return [new Date(p.start), p.value];
      });

```

**Screenshots**
If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/61433087/191673122-ef2a999a-21b6-4b71-b737-715ac6bf42c3.png)

**Expected behavior**
The column should be able to be placed behind the graph, now I am not able to see the graph whwew the column are high.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by RomRider** [comment]
This is not possible with the ApexCharts.js library unfortunately.
