### ISSUE TITLE
Header value of current state for future forecasts

### ISSUE THREAD

**Issue by valexi7** [RomRider/apexcharts-card#404]
When showing charts for future e.g. forecast or future electricity price the header shows value of the last of the series.

I would like to see a feature to show current state of the sensor in header. This is what "now" setting does, but in header it would be nice too se value itself.
Here is the picture. I can see the "now" line there, but the header shows the electricity price for the last value of the series.
![image](https://user-images.githubusercontent.com/44439515/191914496-841adce3-f2dd-4395-a2e5-e2edb0c36424.png)

**Comment by IlmLV** [comment]
found solution:

        series:
          - entity: sensor.nordpool_current_eur_kwh
            show:
              in_header: before_now

**Comment by valexi7** [comment]
@IlmLV Wow. Thanks!
I actually also got around this by adding another series but didn't draw a graph for them and then hide header for the first one.
`
series:
      - entity: sensor.nordpool_current_eur_kwh
        show:
          in_chart: false
`
