### ISSUE TITLE
data_generator and graph_span and zooming

### ISSUE THREAD

**Issue by Culan** [RomRider/apexcharts-card#407]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I'm using data_generator to get my series data.
The xaxis is a datetime axis.
The data_generator is producing data timestamped in the future (prices of electricity of coming day).
I do not use graph_span as i want it to zoom to the data available.

The data are (probably) rendered correctly but the zoom of the graph starts from now (so it shows some columns in the end).
Then, i activated the toolbar and if i click on "Reset zoom" it zooms correctly to the area where my data is.

**Version of the card**
Version: 2.0.1

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
update_interval: 5s
apex_config:
  chart:
    zoom:
      enabled: true
    toolbar:
      show: true
      tools:
        zoom: true
        zoomin: true
        zoomout: true
        pan: true
        reset: true
    autoScaleXaxis: true
  xaxis.type: datetime
  yaxis:
    min: 0
    decimalsInFloat: 2
hours_12: false
now:
  show: false
series:
  - entity: sensor.nordpool_kwh_se4_sek_3_095_025
    name: Test
    type: column
    float_precision: 3
    data_generator: |
      let res = [];
      res.push([(new Date()).setHours(((new Date()).getHours() + 1)), 1]);
      res.push([(new Date()).setHours(((new Date()).getHours() + 2)), 2]);
      res.push([(new Date()).setHours(((new Date()).getHours() + 3)), 3]);
      res.push([(new Date()).setHours(((new Date()).getHours() + 4)), 4]);
      res.push([(new Date()).setHours(((new Date()).getHours() + 5)), 5]);
      res.push([(new Date()).setHours(((new Date()).getHours() + 6)), 6]);
      res.push([(new Date()).setHours(((new Date()).getHours() + 7)), 7]);

      return res;


```

**Screenshots**
Before reset zoom:
![image](https://user-images.githubusercontent.com/17331099/192553834-8088b663-9a9c-47f1-9087-0e008bd78432.png)

After zoom:
![image](https://user-images.githubusercontent.com/17331099/192554005-fdf9d91c-6e45-4708-bf94-98b3ee1bf2e2.png)

**Expected behavior**
I would expect the zoom to recalculate once the data_generator data has been added.

**Comment by Culan** [comment]
Anyone have any input on this?

**Comment by steinelg** [comment]
I am having the same issue when trying to plot a future values, the x-axis does not zoom properly, and data is often "out-of-view".

The partial workaround I am have found is to add "span" to the config, for instance 
```
span:
  start: day
graph_span: 1d
```

but this is not an ideal solution as this means the amount of previous  versus future  data shown varies throughout the day.  Ideally I would have liked to always look for instance six hours into the the past and six hours into the future, but it does not seem like this is currenlty supported. 

One way to remedy this would be to add support in "span" for "now" as a value of "start" or  end", so that 
```
span:
  start: now
  offset:  -6h
graph_span:12h
```
that way you would always have a "sliding window" with the same ratio of past to future  data  in your plot.

**Comment by steinelg** [comment]
I found that by combining  _span_ _offset_ and _graph_span_, this desired combination of historic and future values can be displayed in HA.

For instance to view 12 hours of historical data and 12 hours of  future data, specify
`graph_span: 24h
span:
  offset: +12h`

without  specifically specifying any "_start_"  or  "_end_"  in span. 

So this is the work-around, but  I agree it would be nice if the card figured this out on its own.

**Comment by Culan** [comment]
Nice find @steinelg !

In my case, i wan't graph_span to be dynamic to the dataset.
I do not know upfront how far ahead in the future my dataset holds.

I use it to plot electricity prices and at approx. 13:00 the prices of the coming day arrives.
So i want that until i get the prices of the coming day, the graph_span is from now until end of current day.
Then, when coming day prices arrive, i want it to zoom from now until end of day coming day.

Now, not defining any graph_span and having autoScaleXaxis to true seems to do what i want except it does not work with data_generator.

**Comment by BobC76** [comment]
Looking for a solution to this, have a dynamic electricity rate series coming from a data_generator which is for today, or today and tomorrow, depending on time of day (the new rates released after 4pm). Is there any way to make x-axis span dynamic? I wondered if using apex charts options might provide a workaround but I can't see a way.
