### ISSUE TITLE
Feature Request: Period count for statistics for greater control over period

### ISSUE THREAD

**Issue by michaelblight** [RomRider/apexcharts-card#408]
**Checklist**
- [y] I am running the latest version of the card
- [y] I checked if there isn't another feature request opened with the same request
- [y] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
The `statistics` option allows you to plot mean (etc) for each 5minute, hour, day, month interval. However, it doesn't let you have greater control, such as 12 hours, 5 days or 3 months.

**Describe the solution you'd like**
As well as the "period" option, if there was "period_count" (for example), so you could define:
```
statistics:
  type: mean
  period: day
  period_count: 7
```

**Describe alternatives you've considered**
You could possibly do the same thing with extra sensors in HA, but it would not be flexible to change.

**Additional context**
It might have an impact on the "5minute" period option, but does this actually work? I've not tried it, but given statistics are only written hourly, where would 5 minute data come from?

Would there be performance concerns if somebody requested a mean over 9999 months to effectively get "forever"?

**Comment by jackhax1** [comment]
I support this request. Looks like a great feature
