### ISSUE TITLE
Improve documentation for statistics

### ISSUE THREAD

**Issue by michaelblight** [RomRider/apexcharts-card#412]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Yes and no. The statistics option can be a bit confusing, and would benefit from further documentation.

Firstly, I've found that `state_class` of "measurement" stores min/max/mean but not state/sum; whereas "total" and "total_increasing" store the opposite. This is (sort of) indicated in [HA documentation](https://data.home-assistant.io/docs/statistics/#:~:text=Home%20Assistant%20has%20support%20for,a%20measurement%2C%20like%20current%20temperature.) but the ramifications for ApexCharts are not obvious.

Secondly, 'min' and 'max' are likely to relate to states from the previous period. For example, if state was 12 before the hour, and changes once in the next hour to 7, then the max for both hours will be 12 because it was logically 12 up until the exact time it changed to 7. So for the first part of the hour it was still 12 because there was no state change.

I was using type=max and period=day to show my step count. However, I wasn't getting anything because I set it up as "total", so "max" was not being stored. So I changed the sensor to "measurement", but then it was very confusing when today's max was the same as yesterday's when I hadn't walked yet. This is because the step count resets to zero just after midnight, so the max for the day up until that point is still the max from yesterday. Therefore in this sort of case, the max for the first hour of every day will be the max from the previous day, and it is likely to be the max for the whole day.

I drafted more than a few issues for both HA and ApexCharts before I released I was the issue :). So maybe further explanation would avoid future unwarranted issues?

I fixed it by changing back to "total" and using type=state and period=day, although this was less than intuitive.

**Describe the solution you'd like**
Maybe update the documentation to highlight this?

**Describe alternatives you've considered**

**Additional context**

**Comment by jsiemek** [comment]
Thank you, really helpfull!!
