### ISSUE TITLE
Add apex_config option for series

### ISSUE THREAD

**Issue by fedearne** [RomRider/apexcharts-card#413]
I would like to be able to use 'apex_config' on the series element just like on the chart and yaxis elements.

Specifically to create dashed lines. Direct support for this would of course be nice as well.

**Comment by steinelg** [comment]
seconded the desire for support of dashed line in one way or another.

**Comment by PutoPunko** [comment]
I already added dashed lines to my config by using at apex_config and dash_array.

My example:

type: custom:apexcharts-card
experimental:
  brush: true
brush:
  selection_span: 15d
graph_span: 365d
update_interval: 5min
yaxis:
  - id: Power
    decimals: 0
    apex_config:
      tickAmount: 5
      title:
        text: Voltaje (V)
all_series_config:
  stroke_width: 2
  fill_raw: last
header:
  show: true
  title: Entrada cuadro
  show_states: true
  colorize_states: true
apex_config:
  stroke:
    dashArray:
      - 0
      - 3
      - 3
series:
  - entity: sensor.smartlink_main_volt
    yaxis_id: Power
    name: Media
    statistics:
      type: mean
      period: day
      align: middle
    stroke_width: 3
    type: line
    opacity: 1
    show:
      in_brush: true
      in_chart: true
  - entity: sensor.smartlink_main_volt
    yaxis_id: Power
    name: Min
    statistics:
      type: min
      period: day
      align: middle
    type: line
    opacity: 1
    show:
      in_brush: false
      in_chart: true
  - entity: sensor.smartlink_main_volt
    yaxis_id: Power
    name: Max
    statistics:
      type: max
      period: day
      align: middle
    type: line
    opacity: 1
    show:
      in_brush: false
      in_chart: true
