### ISSUE TITLE
 WS API 'history/statistics_during_period' is deprecated and will be removed in Home Assistant Core 2022.12. Use 'recorder/statistics_during_period' instead 

### ISSUE THREAD

**Issue by zSprawl** [RomRider/apexcharts-card#417]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
The logs are filled with 100's of instances of:

 WS API 'history/statistics_during_period' is deprecated and will be removed in Home Assistant Core 2022.12. Use 'recorder/statistics_during_period' instead 

**Version of the card**
Version: Latest

**To Reproduce**
This is the configuration I used:

Anytime I bring up any of my many Apex Charts on a dashboard, this warning appears a few times in the logs. 

**Screenshots**

**Expected behavior**
Likely need to find/replace instances of history service call with the recorder version.

Thank you. This integration freaking rocks and I would hate to have to go back to the boring native graphs.

**Comment by midadami** [comment]
Same problem.

**Comment by tankdeer** [comment]
Piling on to say we only have 1 release cycle left  before this stops working all together. I have not seen any activity from @RomRider in this repo. Has this been abandoned?

**Comment by RomRider** [comment]
I'll review that in time for it to not break. Sorry, I'm off the grid lately.

**Comment by RomRider** [comment]
Could you please check if it still works?
This makes the card only work with HA 2022.10 and above I think.

**Comment by tankdeer** [comment]
Ok, so I removed the HACS version, and manually installed this new one. It does appear to have resolved the issue - no more warnings in my log files. I don't see any issues with the charts, they appear to all still work as intended.

Thank you for fixing this. I am not certain if this is backwards compatible or not. I suspect you are right and this would be a breaking change for older releases.

**Comment by RomRider** [comment]
You could just enable the beta on apexcharts-card in HACS, no need for manual installation ;)

Thanks for the feedback!

**Comment by tankdeer** [comment]
I suppose I should have though of that! 😆 

In either case, it works

**Comment by Kertz1954** [comment]
This is still an issue. Using v2.0.2-dev.1 locally. Updated resource and added ?v2.0.2-dev.1 to it.
Cleared cache and refreshed. Still getting the warning message in 2022.10.5

Logger: homeassistant.components.history
Source: components/history/__init__.py:85
Integration: History (documentation, issues)
First occurred: 10:28:16 (129 occurrences)
Last logged: 10:39:33

WS API 'history/statistics_during_period' is deprecated and will be removed in Home Assistant Core 2022.12. Use 'recorder/statistics_during_period' instead

apexcharts-card code snippet.

series:
  - entity: sensor.daily_electric_consumption
    statistics:
      type: state
      period: 5minute
      align: middle

**Comment by Kratax** [comment]
Hi,
For me still warning with the latest HA & release:

`Logger: homeassistant.components.history
Source: components/history/__init__.py:85
Integration: History (documentation, issues)
First occurred: 1:39:27 PM (42 occurrences)
Last logged: 1:40:12 PM

WS API 'history/statistics_during_period' is deprecated and will be removed in Home Assistant Core 2022.12. Use 'recorder/statistics_during_period' instead`
