### ISSUE TITLE
Stacked lines show great in edit mode ones done editing 1 line does not look stacked anymore another when look to be shifted on time axe

### ISSUE THREAD

**Issue by Yvesaha** [RomRider/apexcharts-card#418]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
When in Edit mode the graph shows as expected. When finished lines do not stacke or get moved on time axe
**Version of the card**
Version: V2.0.1

**To Reproduce**
This is the configuration I used:
type: custom:apexcharts-card
apex_config:
  chart:
    stacked: true
header:
  show: true
  title: ApexCharts-Card
  show_states: true
  colorize_states: true
series:
  - entity: sensor.sw_media_electrical_measurement
    stroke_width: 1
    group_by:
      func: last
      duration: 10min
  - entity: sensor.tz3000_g5xawfcq_ts0121_electrical_measurement
    stroke_width: 1
    group_by:
      func: last
      duration: 10min
  - entity: sensor.sw_syno_cur
    stroke_width: 1
    group_by:
      func: last
      duration: 10min
  - entity: sensor.sw_schuur_electrical_measurement
    stroke_width: 1
    group_by:
      func: last
      duration: 10min
  - entity: sensor.sw_achter_bank_electrical_measurement
    stroke_width: 1
    group_by:
      func: last
      duration: 10min

```

**Screenshots**
Dont know how to get them here?
![image](https://user-images.githubusercontent.com/76709827/195869611-aef49699-5a46-42c6-8753-fae8b3bcdd36.png)
![image](https://user-images.githubusercontent.com/76709827/195869939-65b576c2-cbae-4fc3-9ca6-9681f1d10f37.png)

**Expected behavior**
When in edit mode it does work and the grap shows stacked lines as axpecterd.
When done editing some line(s) do not loke stacked anymore, another get moved on the time axe

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Version Versie 106.0.5249.103 (Officiële build) (64-bits)
**Smartphone (please complete the following information):**
 - Device: iPhone11 pro
 - OS: 16.0
 - Browser [e.g. stock browser, safari]
 - Version 

**Additional context**
Add any other context about the problem here.
My first report, so go easy on me:)
I have some screenshots, but it seems imposible to upload rigth now.

**Comment by hmax-72** [comment]
I'm experiencing the same issue. I found out, disabling the caching (see main options) is a workaround.

**Comment by Yvesaha** [comment]
> 

Indeed not 100% fix.
I did not find any relation, it seems to appear and go unrelated to other events.

**Comment by friendlycrow** [comment]
![Markering_120](https://user-images.githubusercontent.com/104067245/211221677-8d59149a-7721-4b13-ab81-5ec43e8988a7.png)
Time shifting and even negative values.

**Comment by friendlycrow** [comment]
This is still a problem.

**Comment by GeoBau** [comment]
I am still experiencing the issue. Workaround with clearing the cache worked for me
