### ISSUE TITLE
Feature Request: Show extremas (min, max)

### ISSUE THREAD

**Issue by torkelsson** [RomRider/apexcharts-card#43]
Would it be possible to add an option to the main show option to show the extremas, mix/max values, below the legend? Similiar to what you can do int the mini-graph card:

![Mini Graph card screenshot](https://user-images.githubusercontent.com/6064917/106769876-ba536d80-663d-11eb-9038-9117fc9daca5.png)

**Comment by RomRider** [comment]
I don't think I could fit that into this card. How would that look with multiple entities?

On mini-graph-card it only applies to the first entity. I don't want to give specific treatment to the first entity vs the others.

**Comment by torkelsson** [comment]
Can't use the extramas of all entities, and then add an in_extrema option to include/exclude some of them? Just as you do with in_chart and in_header?

**Comment by RomRider** [comment]
Maybe, I'll think about it

**Comment by michalk-k** [comment]
Just a 2c from me. 
I'm using mini-graph mostly for showing temp and humidity on the same graph. While I can show max/min values for one of them, you can imagine I'm missing an option to show the same for the second one.
I admit it's impossible to show those data for all values in general, considering there might be more entities  (maybe in form table somewhere next to graphs but for sure not incorporated in graphs layout). But somehow I'm missing such the feature. 
Well.. At the end I used to not having it anymore ;)

**Comment by wormiedk** [comment]
Maybe min and max could be indicated by an annotated line at top/bottom?

**Comment by jchasey** [comment]
At a slight tangent is it possible to expose the min / max values so they can be used as parameters in the transform function?

**Comment by RomRider** [comment]
> At a slight tangent is it possible to expose the min / max values so they can be used as parameters in the transform function?

No, because transform is applied way before we can know what the min and max is.

**Comment by wormiedk** [comment]
Actually sort of already possible e.g
'''
  - entity: sensor.ude_zb_temperature
    curve: smooth
    color: blue
    name: Min
    type: line
    group_by:
      duration: 24h
      func: min
    stroke_width: 1
'''

Would be nicer if the line could be dashed and the value displayed inside the graph instead of in the legend though

**Comment by RomRider** [comment]
So I've been experimenting with some stuff. What do you think about showing min-max like this?
![image](https://user-images.githubusercontent.com/21064206/107888805-f1affd00-6f0e-11eb-8477-d9f70d75017a.png)

**Comment by Lunkobelix** [comment]
I think the top one looks amazing!

**Comment by DavidFW1960** [comment]
I prefer the top one as well. With logic so if multiple series they won't overwrite too?

**Comment by RomRider** [comment]
> With logic so if multiple series they won't overwrite too?

Not sure that is handled by ApexCharts, I'd have to investigate, but I have little hope.

**Comment by torkelsson** [comment]
Of the two I like the one on top best. 

I still think a footer would be be useful. 

Perhaps by adding a new footer option (similar to what you have in the entities card) supporting basically the same options as the header option, but it shows up below the graph. And adding an in_footer option to each serie in which you can specify what should be shown in the footer. Maybe something like:

in_footer:
 show: true/false/max/min/avg/"func" - not sure what true means
 title: "some text"
 time: true/false                                     - probably only for max/min or other single point values connected to a specific time

Not sure if it is doable though.

**Comment by kaizersoje** [comment]
I prefer the top one as well.

**Comment by RomRider** [comment]
I guess at some point I could add a non-ApexCharts legend with those features (min, max, avg, last) like grafana would do:
![image](https://user-images.githubusercontent.com/21064206/107937147-d501dc80-6f83-11eb-88ad-b91526b7cea1.png)

But it's going to take time and is going to be compute heavy :)

**Comment by RomRider** [comment]
So I've released a beta with extremas support like so:
![image](https://user-images.githubusercontent.com/21064206/107978306-d6033000-6fbc-11eb-8f88-0ddab1a8ecac.png)

I'll keep this issue opened to work later on the more advanced legend feature.

**Comment by torkelsson** [comment]
After running a few graphs with extremas turned on I am starting to like it (though my original feature request still stands :-). 
Would it be possible to add the time (and perhaps the unit) to the label, so that you don't have to hover over the point to see the time (hovering over the label does not do anything)? Or is that too much work?

**Comment by RomRider** [comment]
So I initially experimented with adding the time also, but the label doesn't support to be multi-line/I didn't find a way to make it multi-line so it gives you massive labels.

**Comment by RomRider** [comment]
So I found a way to do something like that. It takes quite some space though, so...
![image](https://user-images.githubusercontent.com/21064206/108392084-a3527500-7212-11eb-8dde-f046bb0bfa83.png)

**Comment by torkelsson** [comment]
I have not yet made my mind up what I think about multiline labels. It depends on what the graph are used to show I guess. 

Another Idea. ;-) 

Would it be possible to use strftime options to specify the time and/or the whole label? Maybe something like:

extremas: "Value: %#\n%H:%M:%S"

Where %# indicates the value (I don't think it is used by strftime) and "\n" for splitting the line in two. Using this method it would also be possible to add arbitrary strings to the label.
