### ISSUE TITLE
Graph not displayed on iPad/ iPhone companion app or Safari IOS

### ISSUE THREAD

**Issue by alexio70** [RomRider/apexcharts-card#434]
**Checklist**
- [✅] I updated the card to the latest version available
- [✅] I cleared the cache of my browser
- [✅] I verified that I'm really running the lastest version in my browser console
- [✅] I checked if there is another issue opened with the same problem

**Describe the bug**
A grap card that is displayed on Macbook/ Safari is not rendered on iPad or iPhone companion app. HW Rebooting does not resolve the issue

**Version of the card**
Version: V2.0.1

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Now
header:
  show: true
  title: Tibber vandaag (€/kwh)
series:
  - entity: sensor.entsoe_e_average_electricity_price_today
    name: kWh price
    stroke_width: 3
    float_precision: 2
    type: column
    curve: stepline
    opacity: 0.3
    color: green
    data_generator: |
      return entity.attributes.prices_today.map((record, index) => {
        return [record.time, record.price];
      });
```

**Screenshots**
![IMG_4C1D3B61F7A6-1](https://user-images.githubusercontent.com/83072298/202269827-0c4d8917-ed50-41c0-bc9d-8affe541300d.jpeg)
![Graph on Safari](https://user-images.githubusercontent.com/83072298/202269893-51f9702b-fb3d-4bf6-9870-20e11f72d352.png)

**Expected behavior**
Expected to have the card rendered on iPhone/iPad just as it was rendered on Macbook

**Desktop (please complete the following information):**
 - Browser Safari (✅)
 - Version 16.1 (18614.2.9.1.12)

**Smartphone (please complete the following information):**
 - Device: iPhone13 ‼️
 - OS: 15.6.1 ‼️
 - Browser [HA companion App] ‼️
 - Version [2022.10.1 - 424 ‼️]

**Comment by mhoogenbosch** [comment]
I'm experiencing the same issue on a Ios 15.7.3.

Card:

```
type: custom:apexcharts-card
graph_span: 24h
span:
  start: day
now:
  show: true
  label: Nu
header:
  show: true
  title: Stroomprijs vandaag (€/kWh)
series:
  - entity: sensor.nextenergy_average_electricity_price_today
    stroke_width: 2
    float_precision: 3
    type: column
    opacity: 1
    color: ''
    data_generator: |
      return entity.attributes.prices.map((record, index) => {
        return [record.time, record.price];
      });
yaxis:
  - id: Prijs
    decimals: 2
    min: 0
```

Also installed Chrome on the ipad (ipad air 2 in my case which is maxed at ios 15.7.3), but same issue.

Other charts are showing fine, for example:

```
type: custom:apexcharts-card
graph_span: 24h
header:
  title: Energie prijs vandaag (€/kWh)
  show: true
span:
  start: day
now:
  show: true
  label: Nu
series:
  - entity: sensor.nordpool_kwh_nl_eur_3_10_021
    type: column
    data_generator: |
      return entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
      });

```

HA running: 2023.3.6
Apex: 2.0.2
