### ISSUE TITLE
Feature Request: Show current time as a bar/thin line in the chart

### ISSUE THREAD

**Issue by torkelsson** [RomRider/apexcharts-card#44]
Would it be possible to add an option to show the current time as a bar or thin line in a chart? I may be useful when you have time series spanning past and current times, i.e span.end is in the future. Maybe as a global/main option where you can specify the width and color?

**Comment by RomRider** [comment]
Good idea, I think I can make this happen as ApexCharts provides a feature to display "annotations" on the chart like in this example:
https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/

**Comment by torkelsson** [comment]
Just realized that a more general annotation feature could be useful (both x and y), where current time is one case. Another use case would be if you have a multi day chart, adding an annotation at midnight would make the chart a lot easier to read.

**Comment by RomRider** [comment]
So today you can already do that, the only missing piece is the variable date part (for the x axis).
Let me start with this request and then we'll iterate from there.

**Comment by torkelsson** [comment]
I can? I just started playing with yesterday evening and have a lot to discover...
