### ISSUE TITLE
Feature Request: 12-hour time format

### ISSUE THREAD

**Issue by bdr99** [RomRider/apexcharts-card#48]
It would be nice if we could configure the chart to use 12-hour time instead of 24-hour time in the tooltips and x-axis labels.

**Comment by RomRider** [comment]
Right, I'll have a look!

**Comment by bdr99** [comment]
> 
> 
> Right, I'll have a look!

Thanks! Awesome library, by the way. I'm using it for a temperature chart, and it's working great.

**Comment by fa-ve** [comment]
You can set it manually:
https://apexcharts.com/docs/datetime/

for example

  xaxis:
    labels:
      format: dd-MM

**Comment by RomRider** [comment]
Tooltip would still be in 24h using this approach. I'll make it a global setting

**Comment by RomRider** [comment]
That would also close #53
