### ISSUE TITLE
Having stacked values in a horizontal bar

### ISSUE THREAD

**Issue by HermesHonshappo** [RomRider/apexcharts-card#488]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be interesting to display stacked bars horizontally. There are cases where there isn't many X-axis entries, but many Y-axis ones.
It is also a very quick way to see the distributions of variables out of a total of 100%

Example [here on the apexcharts website](https://apexcharts.com/javascript-chart-demos/bar-charts/stacked-100/)

<img width="221" alt="Screenshot 2023-01-24 at 12 13 29" src="https://user-images.githubusercontent.com/97752752/214277560-a64c7955-073e-418c-960e-88b12ad4dbe9.png">

**Additional context**
This request stems from the need to display the cost for heating, media, lights, etc. in a percentage of total cost, on a very synthetic and easy to read graph, that would not take a lot of space in lovelace
Ideally, i'd like to display this on the main lovelace dashboard, so that I can quickly see what I need to focus on to reduce energy costs. But There are other use cases I can think of (showing time spent home vs away, showing time for each heater spent in sleep mode vs heating mode)

**Describe alternatives you've considered**
So far I'm using donuts & pies. They are good, but the vertical space taken to visualize the distribution is too high in my opinion.
Ex. of what I'm displaying now (in costs, but I also have values in percent in the db)

<img width="247" alt="Screenshot 2023-01-24 at 12 16 56" src="https://user-images.githubusercontent.com/97752752/214278217-bfc59cb9-8e72-4eef-ab9b-188b69f171fd.png">

I've also tried grafana, but for some reason, the stacking of values produce errors. My dataset doesn't seem to work well with grafana stacks (even when specifying 100% and all in the same series)
Also, embedding a grafana display in lovelace is a bit more cumbersome

**Comment by Juchar** [comment]
Push, would be also highly interested in this chart type 😃
