### ISSUE TITLE
Start chart at specific datetime

### ISSUE THREAD

**Issue by PulsarFX** [RomRider/apexcharts-card#490]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I'd like to have the start of a chart at a specific date and time. Currently it seems this has to be done with 
```
span:
  offset: -20days
```

**Describe the solution you'd like**
Add an option at which date and time to start the chart, like
```
span:
  startpoint: 2022-12-30 15:24:36
```
This keeps a historical chart fixed and doesn't behave like a sliding window when used with `offset`

**Comment by mrmizu** [comment]
Would I be able to also use an entity (or attribute) state value as start/endpoint? such as sunrise/sunset from the sun integration?

**Comment by PulsarFX** [comment]
I still find this interessting.
