### ISSUE TITLE
Error: Problem parsing d="M 0 NaN"

### ISSUE THREAD

**Issue by ServusNL** [RomRider/apexcharts-card#498]
Checklist

[OK] I updated the card to the latest version available
[OK] I cleared the cache of my browser
[OK] I checked if there is another issue opened with the same problem
Describe the bug
After setting up a card on a sub view, loading takes ages and the browser freezes.
Error in console:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/42113454/218136505-d1e0ef5f-8aeb-4663-83d4-eaf0bb05a8c0.png">

To Reproduce
Install, set up card like:
`      - type: custom:layout-card
        layout_type: custom:horizontal-layout
        layout:
          width: 300
          max_width: 900
          max_cols: 1
        cards:
          - type: custom:apexcharts-card
            update_interval: 15min
            series:
              - entity: sensor.netto_energie_gebruik
                show:
                  datalabels: true
              - entity: sensor.power_usage
                show:
                  datalabels: true
              - entity: sensor.active_power
                show:
                  datalabels: true`
Go to view
(removing labels or changing the update interval does not change anything.

Additional context
using home assistant 2023.2.3 , cards was installed through HACS.

**Comment by Grumblezz** [comment]
Same here. Mine is also giving tons of errors in seconds. @ServusNL have you found a workaround?

At first I thought that it had to do with some incorrect configuration, but it already appears before trying to add the apex card:
![msedge_hH3AEQDEEV](https://user-images.githubusercontent.com/74052665/219876069-2149513a-1f8d-4c47-a98b-e485f3093d21.gif)

**Comment by ServusNL** [comment]
No unfortunately not. So open to suggestions!

**Comment by trydis** [comment]
Same as well for me, I believe it started when i upgraded from 2023.0 -> 2023.2, but not 100% sure. HA is super sluggish after the last update, which is why I noticed it in the dev tools.

**Comment by hiatsu0** [comment]
I can confirm this issue too. And from HA 2023.3.1 onwards it has resulted in not being able to do much edits in the card dialog because adding any cards often crashes the browser session, particulary on iOS companion app / mobile safari — macOS Safari just lists these errors but won’t auto-reload like iOS.

The errors seem to pop in the browser console regardless of other custom cards I have installed -- tried uninstalling bunch of them but the issues persist. Even deleted a bunch on old unused apexcharts-cards from old views I had stored but not using, no help.

The same errors appear in the log every time I try and add any card to any view and apparently these are enough to cause Mobile Safari to give up and reload the page. 

Logs from macOS Safari (HA 2023.3.3):
```
[Error] Error: Invalid value for <svg> attribute height="NaN"
	value (apexcharts-card.js:1:187074)
	value (apexcharts-card.js:1:538201)
	value (apexcharts-card.js:1:534493)
	value (apexcharts-card.js:1:640199)
	(unknown function) (apexcharts-card.js:1:646245)
	Promise
	value (apexcharts-card.js:1:646178)
	(unknown function) (apexcharts-card.js:1:649907)
[Error] Error: Invalid value for <foreignObject> attribute height="NaN"
	value (apexcharts-card.js:1:381752)
	value (apexcharts-card.js:1:385841)
	value (apexcharts-card.js:1:640808)
	(unknown function) (apexcharts-card.js:1:646245)
	Promise
	value (apexcharts-card.js:1:646178)
	(unknown function) (apexcharts-card.js:1:649907)
[Error] Error: Problem parsing d="M 0 NaN"
	attr (apexcharts-card.js:1:568741)
	value (apexcharts-card.js:1:177278)
	value (apexcharts-card.js:1:178847)
	value (apexcharts-card.js:1:259522)
	value (apexcharts-card.js:1:258551)
	value (apexcharts-card.js:1:536390)
	value (apexcharts-card.js:1:641224)
	(unknown function) (apexcharts-card.js:1:646245)
	Promise
	value (apexcharts-card.js:1:646178)
	(unknown function) (apexcharts-card.js:1:649907)
[Error] Error: Problem parsing d="M 0 NaN"
	attr (apexcharts-card.js:1:568741)
	value (apexcharts-card.js:1:177278)
	value (apexcharts-card.js:1:178847)
	value (apexcharts-card.js:1:514372)
	value (apexcharts-card.js:1:510827)
	value (apexcharts-card.js:1:536441)
	value (apexcharts-card.js:1:641224)
	(unknown function) (apexcharts-card.js:1:646245)
	Promise
	value (apexcharts-card.js:1:646178)
	(unknown function) (apexcharts-card.js:1:649907)
```

**Comment by kongjudas** [comment]
I noticed the same problem on 2023.5 hunting for a CPU eater in my setup.
