### ISSUE TITLE
If a column with generated data and  any other type of series is combined, the bars are plotted as thin vertical lines

### ISSUE THREAD

**Issue by wigster** [RomRider/apexcharts-card#503]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I am generating data for the next 24 hours from a rain forecast in one of my sensors' attributes. If this series is plotted alone, it looks fine. If any other series is added to the same plot, the bars become thin lines.

This doesn't happen if the data series is normal and not generated.

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:apexcharts-card
series:
  - entity: sensor.inpo_praha_forecast
    type: column
    data_generator: |
      return entity.attributes.forecast_time.map((time, index) => {
        return [new Date(time).getTime(), entity.attributes.forecast_precipitation[index]];
      });
  - entity: sensor.electricity_total_energy             #<---- remove this to see a good chart
graph_span: 24h
span:
  start: day
yaxis:
  - min: 0
    max: 1
```

**Screenshots**
Good chart -- one series:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/10956987/219636841-f8593ae1-38cf-497d-a4db-13712740c91a.png">
Bad chart -- two series
<img width="360" alt="image" src="https://user-images.githubusercontent.com/10956987/219636980-31fe8409-db64-4883-8104-f4742f9389db.png">

**Expected behavior**
The data generated series columns should remain unchanged.
**Desktop (please complete the following information):**
 - Browser Edge v111.0.1660.13 

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 16.3
 - HA app
 - Version: 2023.3

**Additional context**
State of the source sensor for data generation:
```yaml
forecast_time:
  - '2023-02-17T12:23:00.121309+01:00'
  - '2023-02-17T13:00:00+01:00'
  - '2023-02-17T14:00:00+01:00'
  - '2023-02-17T15:00:00+01:00'
  - '2023-02-17T16:00:00+01:00'
  - '2023-02-17T17:00:00+01:00'
  - '2023-02-17T18:00:00+01:00'
  - '2023-02-17T19:00:00+01:00'
  - '2023-02-17T20:00:00+01:00'
  - '2023-02-17T21:00:00+01:00'
  - '2023-02-17T22:00:00+01:00'
  - '2023-02-17T23:00:00+01:00'
  - '2023-02-18T00:00:00+01:00'
  - '2023-02-18T01:00:00+01:00'
  - '2023-02-18T02:00:00+01:00'
  - '2023-02-18T03:00:00+01:00'
  - '2023-02-18T04:00:00+01:00'
  - '2023-02-18T05:00:00+01:00'
  - '2023-02-18T06:00:00+01:00'
  - '2023-02-18T07:00:00+01:00'
  - '2023-02-18T08:00:00+01:00'
  - '2023-02-18T09:00:00+01:00'
  - '2023-02-18T10:00:00+01:00'
  - '2023-02-18T11:00:00+01:00'
  - '2023-02-18T12:00:00+01:00'
  - '2023-02-18T13:00:00+01:00'
forecast_temperature:
  - 9.3
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 11
  - 11
  - 11
  - 11
  - 11
  - 11
  - 11
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 11
  - 11
  - 11
  - 12
forecast_precipitation:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0.4
  - 0
  - 0
  - 0
  - 0.1
  - 0.2
  - 0.2
  - 0
  - 0.2
  - 0.3
  - 0.1
  - 0.2
  - 0.3
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0.1
  - 0.5
  - 0.5
  - 0.6
  - 0
  - 0.1
  - 1.3
  - 0.1
  - 0
icon: mdi:weather-sunny-alert
friendly_name: InPo Praha Forecast
```

**Comment by sivu** [comment]
I have the same issue when plotting electricity prices and I added a another entity that shows when a heater has been on. 
group_by solution does not make any difference for me.

**Comment by wigster** [comment]
Try also adding `stroke_width: 6` or something like that.

**Comment by sivu** [comment]
Here is a video of the behaviour. I am toggling the another series on and off.

https://user-images.githubusercontent.com/348411/224833710-a75201fe-8942-44fb-b3f1-ed1526602954.mov


> Try also adding `stroke_width: 6` or something like that.

Adding `stroke_width` seems to work quite nicely as a temporary fix.
