### ISSUE TITLE
“N/A“ value not resolved

### ISSUE THREAD

**Issue by BinnenBeest** [RomRider/apexcharts-card#504]
![BC459521-F09C-4F7C-A388-ADFB614CEF4F](https://user-images.githubusercontent.com/61503030/219683349-32170712-8348-45ac-b0a3-c0208004ff38.jpeg)

A sensor value is not displayed although it’s available (status checked via developer tools) and similar float as other values in this chart. 

What is ‘N/A’ and in which situation is this displayed.
When I reboot the system everything is correct until midnight, at that moment sensor ‘vandaag’ is set to zero. 

I’m using lasted version of Home Assistant (on raspberry pi with hassio).

**Comment by PolymerPrints** [comment]
This happens to me too, and I've found it's because the sensor is sending the same value for a certain amount of time. At least in my case.

If I understand correctly, Home Assistant will not save duplicate values (no "last_changed" event is triggered since the value did not change). Apexcharts will only check a values history for a certain timespan (say for example, 24 hours, not sure if that's accurate). If the last unique/changed value is >24h ago, Apexcharts will simply show "N/A".

**Comment by BinnenBeest** [comment]
Thanks @PolymerPrints I will try to use a helper input_number that is adapted via automation on change of the sensor.
Additionally I can run the automation at least once a day to resave the value.

**Comment by fkapostolidis** [comment]
I have same issue by using this component with sensors. Is there some way to resolve this issue? Mey be by using some math function?

**Comment by BinnenBeest** [comment]
I made an automatisation changing the value regulary -- changing but not changing
Snippet below
else:
      - service: input_number.set_value
        data:
          value: "{{ (states('input_number.kwartierwaarde_maand')|int) +1 }}"
        target:
          entity_id: input_number.kwartierwaarde_maand
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 1
      - service: input_number.set_value
        data:
          value: "{{ (states('input_number.kwartierwaarde_maand')|int) -1 }}"
        target:
          entity_id: input_number.kwartierwaarde_maand

**Comment by fkapostolidis** [comment]
I found solution that works on me: i used transform property on series where you can define if value is null replace it to 0.
But my problem was only with group_by so there I added fill: zero and it works... And now it works: like this
  all_series_config:
    stroke_width: 0.4
    opacity: 0.4
    curve: smooth
    #      type: line
    type: column
    group_by:
      duration: 1min
      func: avg
      fill: zero
  experimental:
