### ISSUE TITLE
'Year' Period for Statistics

### ISSUE THREAD

**Issue by BadgerLoaf** [RomRider/apexcharts-card#521]
**Checklist**
- [ X] I am running the latest version of the card
- [X ] I checked if there isn't another feature request opened with the same request
- [ X] I checked that the feature is not already available in the `dev` branch

**Describe the solution you'd like**
Would it be possible to add a "year" value to the Statistics > Period option?

Example usage:
```
statistics:
  type: state
  period: year
  align: end
```

**Additional context**
My use case is that I use Apex Charts to display my daily and monthly energy savings (from battery and solar usage) in two graphs. What I would like to do is a third graph that shows the yearly savings.

Thanks!

![Screenshot 2023-03-14 at 11 14 41](https://user-images.githubusercontent.com/108699847/224984631-f3e2c2cd-132b-4cd6-84ba-53722d34855d.png)
![Screenshot 2023-03-14 at 11 14 54](https://user-images.githubusercontent.com/108699847/224984638-463ccba4-f3fc-4acc-b561-7e70f3b46f42.png)

**Comment by rikmueller** [comment]
I´d also like to have this feature available.

**Comment by Loic691** [comment]
I´d also like to have this feature available.
