### ISSUE TITLE
Apexcharts breaks on 2023.4.0b0

### ISSUE THREAD

**Issue by hmmbob** [RomRider/apexcharts-card#527]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
All my apex charts error out on the beta for 2023.4

![image](https://user-images.githubusercontent.com/33529490/228769436-a24bb5d1-ffa0-4636-b30c-0cb7adb86057.png)

**Version of the card**
Version: 2.0.2

**To Reproduce**
This is the configuration I used:
https://github.com/hmmbob/HomeAssistantConfig/blob/fda9dd15951d69656aee717ef934901978f92e6e/dashboards/10-energy.yaml#L104-L123

**Screenshots**
See above

**Desktop (please complete the following information):**
Chrome v111

**Smartphone (please complete the following information):**
HA Android Companion app same result

**Comment by NickM-27** [comment]
are there only certain cases where this would break? this card continues to work for me on the beta
