### ISSUE TITLE
apexcharts_card_templates broken on 2023.4

### ISSUE THREAD

**Issue by hmmbob** [RomRider/apexcharts-card#529]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
I've figured out why my apex charts error out on the beta for 2023.4: they won't load the `apexcharts_card_templates` config anymore. I've updated my config to have the first card configured without templates, and the 2nd with templates as per my github link below.

![image](https://user-images.githubusercontent.com/33529490/229370888-8566f5f1-bb5f-4329-b28f-a5f64bb99bb3.png)

Console error:
```
create-element-base.ts:182 card custom:apexcharts-card TypeError: Cannot read properties of null (reading 'config')
    at apexcharts-card.js:1:158978
    at Array.forEach (<anonymous>)
    at ge (apexcharts-card.js:1:158942)
    at tr.setConfig (apexcharts-card.js:835:79010)
    at a (create-element-base.ts:97:11)
    at create-element-base.ts:111:12
    at u (create-element-base.ts:215:12)
    at d (create-element-base.ts:172:12)
    at w (create-card-element.ts:98:3)
    at HTMLElement.value (hui-stack-card.ts:102:21)
```

**Version of the card**
Version: 2.0.3

**To Reproduce**
This is the configuration I used:
https://github.com/hmmbob/HomeAssistantConfig/blob/fda9dd15951d69656aee717ef934901978f92e6e/dashboards/10-energy.yaml#L104-L123

**Screenshots**
See above

**Desktop (please complete the following information):**
Chrome v111

**Smartphone (please complete the following information):**
HA Android Companion app same result

**Comment by RomRider** [comment]
Clear your browser's cache, it's fixed in 2.0.3.
Check you javascript console, you'll see you're probably still running 2.0.2.

**Comment by hmmbob** [comment]
I did clear cache, Console shows 2.0.3: 
![image](https://user-images.githubusercontent.com/33529490/229372180-987f13e3-49e7-4087-b523-94976aab658d.png)

Beta 4 is running.

**Comment by RomRider** [comment]
try to hard refresh the page while having the javascript console opened (CTRL + R on windows or Command + R on mac)

**Comment by hmmbob** [comment]
Tried all that 😄 

![image](https://user-images.githubusercontent.com/33529490/229372342-841c0483-d2ff-414a-bd05-50929d74c4cc.png)

**Comment by RomRider** [comment]
Nevermind... my fault, I've not updated the source of the function... will fix it in 10sec :)

**Comment by hmmbob** [comment]
Jep, 2.0.4-dev fixes the issue for me
