### ISSUE TITLE
Formatting of tooltip bug

### ISSUE THREAD

**Issue by jchasey** [RomRider/apexcharts-card#53]
I have a graph for the forthcoming year and have used

```
xaxis:
  labels:
    format: 'MMM'

```
which displays the date as Jan/Feb/Mar etc along the x axis.

However when mouse overing the graph the tooltips comes out as

Feb 1st, 00:00:00

I’d like to change the format of the tooltip to simply Feb in this case. Using the below does not appear to work.

```
tooltip:
  x:
    format: 'MMM'
```

**Comment by RomRider** [comment]
I'll look into this!

**Comment by RomRider** [comment]
That works now:
```yaml
tooltip:
  x:
    format: 'MMM'
```
