### ISSUE TITLE
Update data from home-assistant database

### ISSUE THREAD

**Issue by BostonDanPhD** [RomRider/apexcharts-card#534]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I modify data within home-assistant_v2.db due to sensor latency (reading from aquahawk website to ingest the data, but the data is not real-time due to exfiltration of the data from my municipality) but this is not reflected in the lovelace card. If I edit the dashboard, the correct data is displayed, however exiting edit mode, the original (unaltered data from initial ingestion) is displayed.

**Describe the solution you'd like**
A capability to set a flag (switch) to update the apexchart card by re-reading the home-assistant_v2.db sensor data.

**Describe alternatives you've considered**
none

**Additional context**

![image](https://user-images.githubusercontent.com/67473840/229823710-a0d7b4a1-aad6-4ffb-81f7-7ac86d298aea.png)

![image](https://user-images.githubusercontent.com/67473840/229824017-c3079eb3-55e4-4d0a-b265-491b4158f7a8.png)

**Comment by RomRider** [comment]
You can disable the cache for this specific card or clear the persistant storage of your browser.
