### ISSUE TITLE
Be able the configure the amount of decimals to show with the data.

### ISSUE THREAD

**Issue by fa-ve** [RomRider/apexcharts-card#54]
There is a hard limit on 1 decimal behind the dot now,  in a lot of cases 2 decimals are very useful to have, for example if you graph costs: $10,00 instead of $10.0

would be great to have a option to configure this.
for example:
0,1,2 or so same concet as this:

  yaxis:
    decimalsInFloat: 0

**Comment by jchasey** [comment]
I used 

`float_precision: 2
`
in the series configuration to get 2 decimals

**Comment by RomRider** [comment]
Yes, but this doesn't apply on the datapoints if you enable them. I'll update that :)

**Comment by fa-ve** [comment]
> float_precision: 2

for now working as I want, not using the data labels at the moment but I'm sure that it will be appreciated if that's also working

**Comment by commentsonly** [comment]
@RomRider .... way back on 4th of Feb 21 ...... "Yes, but this doesn't apply on the dataLabels if you enable them. I'll update that if possible :)"

Looks as if it "wasn't possible". :-)

Tried to do the following:

return (Math.round(x *100) / 100).toFixed(2);

assuming I'll see 2 decimals even if the value is 1 (without decimals) on the datalabels.
But it looks to me as if only .toFixed(0) and .toFixed(1) does work ...
