### ISSUE TITLE
Now options - place label at the right side

### ISSUE THREAD

**Issue by heinemannj** [RomRider/apexcharts-card#546]
**Checklist**
- [x ] I am running the latest version of the card
- [x ] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
The Now label is hiding important actual information of the graph.

**Describe the solution you'd like**
Option to place the Now label at the right side don't hide actual information.

**Describe alternatives you've considered**
Deactivation of the Now feature is an option, but in general  this feature is really useful and helpful.

**Additional context**
![image](https://user-images.githubusercontent.com/3251642/234810236-52c7bb2a-dd9b-4ac0-9451-819957149844.png)

    type: custom:apexcharts-card
    header:
      show: true
      standard_format: true
      show_states: true
      colorize_states: true
    apex_config:
      chart:
        height: 220px
      tooltip:
        enabled: true
        shared: true
        followCursor: true
    graph_span: 4d
    now:
      show: true
      color: grey
      label: Now
    span:
      start: day
      offset: '-1day'
    all_series_config:
      type: area
      opacity: 0.3
      stroke_width: 1
    series:
      - entity: sensor.battery_state_of_capacity
        name: Battery
        float_precision: 0
        type: line
        color: '#f06292'
        opacity: 0.6
        yaxis_id: capacity
        extend_to: now
        show:
          legend_value: true
          in_header: false
        group_by:
          func: last
          duration: 5m
      - entity: sensor.house_consumption_power
        name: House Power
        float_precision: 3
        type: line
        color: MediumAquaMarine
        opacity: 0.8
        yaxis_id: kWh
        unit: kW
        transform: return x/1000;
        extend_to: now
        show:
          legend_value: true
          in_header: false
        group_by:
          func: avg
          duration: 5m
      - entity: sensor.inverter_input_power
        name: Solar Power
        float_precision: 3
        color: '#ff9800'
        yaxis_id: kWh
        unit: kW
        transform: return x/1000;
        extend_to: now
        show:
          legend_value: true
          in_header: false
        group_by:
          func: avg
          duration: 5m
      - entity: sensor.solcast_forecast_today
        name: Solar Forecast (D1)
        extend_to: false
        color: grey
        opacity: 0.3
        stroke_width: 0
        yaxis_id: kWh
        show:
          legend_value: false
          in_header: false
        data_generator: |
          return entity.attributes.forecast.map((entry) => {
                return [new Date(entry.period_start), entry.pv_estimate];
              });
      - entity: sensor.solcast_forecast_tomorrow
        name: Solar Forecast (D2)
        float_precision: 3
        extend_to: false
        color: grey
        opacity: 0.3
        stroke_width: 0
        yaxis_id: kWh
        show:
          legend_value: false
          in_header: false
        data_generator: |
          return entity.attributes.forecast.map((entry) => {
                return [new Date(entry.period_start), entry.pv_estimate];
              });
      - entity: sensor.solcast_forecast_d3
        name: Solar Forecast (D3)
        float_precision: 3
        extend_to: false
        color: grey
        opacity: 0.3
        stroke_width: 0
        yaxis_id: kWh
        show:
          legend_value: false
          in_header: false
        data_generator: |
          return entity.attributes.forecast.map((entry) => {
                return [new Date(entry.period_start), entry.pv_estimate];
              });
      - entity: sensor.solcast_forecast_today
        yaxis_id: header_only
        name: Solar Forecast (D1)
        color: grey
        show:
          legend_value: true
          in_header: true
          in_chart: false
      - entity: sensor.solcast_forecast_remaining_today_every_minute
        yaxis_id: header_only
        name: Forecast (D1 Remaining)
        color: grey
        show:
          legend_value: true
          in_header: true
          in_chart: false
      - entity: sensor.solcast_forecast_tomorrow
        yaxis_id: header_only
        name: Forecast (D2)
        color: grey
        show:
          legend_value: true
          in_header: true
          in_chart: false
      - entity: sensor.solcast_forecast_d3
        yaxis_id: header_only
        name: Solar Forecast (D3)
        color: grey
        show:
          legend_value: true
          in_header: true
          in_chart: false
      - entity: sensor.solcast_api_last_polled
        yaxis_id: header_only
        name: Forecast (Last Update)
        color: grey
        unit: ' min.'
        transform: return ((Date.now()) - (new Date(x).getTime())) / 60 / 60 / 24
        show:
          legend_value: true
          in_header: true
          in_chart: false
    yaxis:
      - id: capacity
        show: true
        opposite: true
        decimals: 0
        max: 100
        min: 0
        apex_config:
          tickAmount: 5
      - id: kWh
        show: true
        min: 0
        apex_config:
          tickAmount: 5
      - id: header_only
        show: false

**Comment by heinemannj** [comment]
Just a comment to reopen.

**Comment by webmogul1** [comment]
a +1 to the request

It would be nice to have the option to choose the side of the label. The way it is now, it might get in the way of the last point.

![image](https://github.com/RomRider/apexcharts-card/assets/5225701/dee61213-e716-4dfd-b7dd-4724286c8556)
