### ISSUE TITLE
issue in cumulative bar for zero value

### ISSUE THREAD

**Issue by saniho** [RomRider/apexcharts-card#56]
Hello, I have an issue, for zero value, one pixel is visible instead of no pixel-bar
![image](https://user-images.githubusercontent.com/52693545/106955318-5f9d3d00-6735-11eb-8691-8c2409bc9073.png)
can you check the problem ?

**Comment by RomRider** [comment]
Config? :)

**Comment by saniho** [comment]
type: 'custom:apexcharts-card'
graph_span: 24h
header:
  show: false
stacked: true
series:
  - entity: sensor.myenedis_history_yyy_hc
    type: column
    name: kWh(HC)
    group_by:
      func: avg
      duration: 60min
  - entity: sensor.myenedis_history_xxx_hp
    type: column
    name: kWh(HP)
    group_by:
      func: avg
      duration: 60min

**Comment by RomRider** [comment]
That's how the library I use works, there's not much I can do unfortunately.

**Comment by saniho** [comment]
Do you have made something, since few days, this is correct 
![image](https://user-images.githubusercontent.com/52693545/107861444-fbb9f900-6e45-11eb-80ad-0837a959c34f.png)

**Comment by RomRider** [comment]
I've forced the line width for column charts which apparently has fixed the issue. I still believe it's a bug on ApexCharts's side. If you're happy with how it works now, please close the issue and if it reappears, feel free to reopen an new one :)

**Comment by saniho** [comment]
work fine
