### ISSUE TITLE
Opacity being overwritten by default

### ISSUE THREAD

**Issue by DavidFW1960** [RomRider/apexcharts-card#57]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser
- [ x] I verified that I'm really running the lastest version in my browser console
- [ x] I checked if there is another issue opened with the same problem

**Describe the bug**
as per https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/255?u=davidfw1960
and Romrider comment Ah right, I forgot I override the values in the code. :expressionless:
Might want to open a bug :slight_smile:
**Version of the card**
Version: 1.5

**To Reproduce**
This is the configuration I used:
```yaml
  fill:
    type: solid
    opacity:
      - 0.2
      - 0.2
```

**Screenshots**
as per forum link
**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
In the latest beta, I've added an `opacity` parameter to each serie. Easier to configure 😉
