### ISSUE TITLE
Statistics (LTS) to support weekly buckets 

### ISSUE THREAD

**Issue by jata1** [RomRider/apexcharts-card#589]
hey @RomRider - I really love this card. Thank you. It is so powerful and very addictive. My wife is getting very annoyed as she thinks I love this card more than her...

I am on the latest version but not sure how to check the dev branch (sorry)

I use the statistics function in apexcharts and the history_stats integration of HA to create LTS for a number of entities. They track daily and weekly and monthly usage for my gas heater. It is easy to use axpexcharts and statistics to generate a daily and monthly views. 

I notice in the built-in statistics graph card of home assistant supports weekly as a time bucket but not apexcharts

I'd like the statistics function of apexcharts to include a weekly time bucket together with some clever formatting to make the weekly labels / grouping to be flexible  (e.g. supporting the align function)

I can use my daily sensor and then combine group_by sum for 7 day duration together with statistics max by day but it would be much nicer to not have to do this and get the xaxis to show the weeks nicely

**Comment by PlayFaster** [comment]
Hi There. I just wanted to add my support for this feature request, please - weekly statistics and also to echo the thanks for a very very powerful card for Home Assistant. Thanks!
