### ISSUE TITLE
Date with offset option

### ISSUE THREAD

**Issue by saniho** [RomRider/apexcharts-card#59]
**Checklist**
- [x ] I am running the latest version of the card
- [x ] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add an offset for the date/time

**Describe alternatives you've considered**
I have a sensor that's containts date, but the data is only available 2 days after the real data, so the timestamp is wrong, can we have an option with an offset to resynchronize data and graph date

**Additional context**

**Comment by RomRider** [comment]
`offset` is already available in `span` and in each `series` entry. I'm pretty sure you can do what you want with that.

What does your sensor look like?

**Comment by saniho** [comment]
@RomRider , yes, I have seen this, but the span is applicable to the sensor date.
But the problem is because I can create the sensor data on real time, my sensor created date is 48h late after the information
for exemple, the current information for my sensor at 2021/02/06 09:43 pm is for the 2021/02/04 0943 pm
that's why I search a solution to apply an offset of the date value in the graph

**Comment by RomRider** [comment]
As I said in my first comment, `offset` exists at the serie level. That will solve your issue. Set it to `+2d`

**Comment by saniho** [comment]
I have made the test and I seen the (2d), but the result is not correct as I expected
![image](https://user-images.githubusercontent.com/52693545/107129477-dff2a800-68c5-11eb-9ec0-5023e3ea399f.png)

exemple : 
my sensor value : 
![image](https://user-images.githubusercontent.com/52693545/107129503-0adcfc00-68c6-11eb-8072-b2b13d9a460e.png)

and I want to see this ( 4th and not 6th ): 
![image](https://user-images.githubusercontent.com/52693545/107129562-76bf6480-68c6-11eb-943c-1368354945df.png)

**Comment by RomRider** [comment]
I've written `+2d` not `-2d`... When asking for help, at least read the answers and try them...

**Comment by RomRider** [comment]
That should work:

```yaml
span:
  offset: - 2d
series:
  - entity: sensor.x
     offset: +2d
```

**Comment by saniho** [comment]
@RomRider thanks for the time, I don't have understand, that you asked me to combine the 2 values( global and in the series ) thanks for your time, this work as expected
