### ISSUE TITLE
chart_type "bar" not available

### ISSUE THREAD

**Issue by sonnstein** [RomRider/apexcharts-card#598]
**Checklist**
- [X] I am running the latest version of the card --> v2.0.4
- [X] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
For Home Assistant, there are following chart_types available: line / scatter / pie / donut / radialbar
I want to have the chart_type "bar" (as [available in the JS Version](https://apexcharts.com/javascript-chart-demos/column-charts/basic/)).

**Describe the solution you'd like**
Introduce chart_type "bar"

**Additional context**
I have 25 solar panels - I want a 25 column chart for visual power comparison (no time reference - just absolut value)

**Comment by travisterrell** [comment]
I'd love to bump this issue. According to documentation, many formats are supported, but I'm only able to select line, column, or area (as in a much much older version). I've re-downloaded the latest version and restarted HA. Are those formats actually working?

 /// apexcharts-card version 2.0.4 /// value.series[0] is not a ChartCardSeriesExternalConfig; value.series[0].type is none of "line", "column", "area"

**Comment by asjp** [comment]
Such a shame that categorised column/bar charts are not supported yet, despite being available in [various ways in ApexCharts](https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/)

It does limit the usefulness of this chart tool in HA.

Graphing the current value of many sensors, where a time series chart would just be far too congested, in a single bar chart, would be great to have.
