### ISSUE TITLE
Choose default toggle configuration

### ISSUE THREAD

**Issue by Toukite** [RomRider/apexcharts-card#60]
Hello,
First of all, thank you, because this card is just awesome !!!!

Now, I would like to be able to do something like that:
![image](https://user-images.githubusercontent.com/42780622/107026951-c6f5d400-67ab-11eb-98c2-b79ec862c322.png)

Meaning, by default (when opening screen), to be able to choose which of the series are toggled on (Extérieur and Garage in the image above) and which of the series are toggled off (Salon in the image above).

I found a way to completely hide a series (which I don't understand because then, why add it in the first place ?) but not to do this.
Did I miss this possibility in the docs ? If no, do you know if this could be implemented ?
Thanks !!

**Comment by RomRider** [comment]
> I found a way to completely hide a series (which I don't understand because then, why add it in the first place ?)

Because you can still display it in the header and not the graph ;)

> Did I miss this possibility in the docs ? If no, do you know if this could be implemented ?

What you want doesn't exist so far, I'll think about it.

**Comment by RomRider** [comment]
So I have made some experiment with that and I'm not so much satisfied with the result. If an entity is disabled, everytime the data is refreshed the scale of the y-axis reverts back to as-if everything was displayed (even if it's not) making the graph jump around. That seems to be an issue with the library I use unfortunately.

**Comment by Toukite** [comment]
Ok thank you for trying !
Maybe a suggestion that could work even if not optimized: on HA give the possilility to list toggledOff series. 
And on js, just load everything normally, then when everything loaded wait a few milliseconds to be sure and then call toggle off on the list of series, as if the user clicked
What do you think ?

**Comment by RomRider** [comment]
If you are speaking about this: https://apexcharts.com/docs/methods/#toggleSeries

It is what I've done, the result being what I put in my last comment.

**Comment by Toukite** [comment]
I am speaking about calling the exact same method as the one called when the user manually click on one of the series in order to show/hide it, and doing it programatically once everything is fully loaded. 
And yes when you toggle the axis recalculate but it displays fine when done manually (at least for me), I'm not really getting the issue you encounter

**Comment by RomRider** [comment]
The above is what is called when you click in the legend.

You're probably not getting the issue because all your data are probably close in range. It happens when the hidden series would extend the range of the y-axis if displayed.

**Comment by Toukite** [comment]
But is it a different behavior as the one that occurs on manual call ?
I do have another card where values are more spread, and indeed, when hiding an extreme one, the height of the chart recalculates, but from what I observed, it's a good thing because you see better the remaining lines
 This is actually what I asked for
Could you show a screen of what's bothering you ?

In anycase, if people don't use the option they won't have an issue so it can be nice to release it anyway for those who are happy with that behavior, no ?

**Comment by RomRider** [comment]
> I do have another card where values are more spread, and indeed, when hiding an extreme one, the height of the chart recalculates, but from what I observed, it's a good thing because you see better the remaining lines

The scale recalculates yes, and then on next data refresh, it jump back to as if everything was displayed but not everything is displayed.

![broken](https://user-images.githubusercontent.com/21064206/107151376-8d1afe00-6962-11eb-89b4-67c9f2dfa3a6.gif)

> In anycase, if people don't use the option they won't have an issue so it can be nice to release it anyway for those who are happy with that behavior, no ?

It's not a problem of releasing the feature, it's a problem of users opening issues because of the broken behavior described above.

**Comment by Toukite** [comment]
Do you have the same issue with lines ?
If no, maybe it can be limited to only a few graph type

If yes, well then if this small issue (for me it's still a lot better than nothin) is documented as a limited behavior in the option description, it should limit people opening issues, and if they do, you can simply say what you told me: that it's due to apex lib

**Comment by Toukite** [comment]
Hello,
Thanks again for releasing this so quickly !!
I tried to use this config as described in the documentation (after upgrade and reboot), but I have following errors:

```
value.series[0] is not a ChartCardSeriesExternalConfig;
value.series[0].show.hidden_by_default is extraneous
```
First error is regarding the experimental config at root level
Second error is regarding the experimental config at series level

I don't understand what I missed, could you please help me ?

**Comment by RomRider** [comment]
Clear your cache! :)

**Comment by Toukite** [comment]
... I thought I did, but indeed this was the issue, sorry to have disturbed you for this !!!
