### ISSUE TITLE
Chart size bug

### ISSUE THREAD

**Issue by donagrejja** [RomRider/apexcharts-card#603]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When i refresh the browser initially it doesn't show the whole timeline but if i switch between tabs back and forth it shows correctly. Not actually sure this is a apexcharts-card bug or home assistant frontend bug.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```
type: custom:apexcharts-card
graph_span: 24h
experimental:
  color_threshold: true
header:
  title: Electricity Price Total (24h)
  show: true
apex_config:
  yaxis:
    min: 0
hours_12: false
span:
  start: hour
  offset: '-9h'
now:
  show: true
series:
  - entity: sensor.nordpool_kwh_se2_sek_total
    type: column
    name: price
    data_generator: |
      return (entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
      })).concat(entity.attributes.raw_tomorrow.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];
      }));
    color_threshold:
      - value: 0
        color: green
      - value: 165
        color: yellow
      - value: 265
        color: orange
      - value: 365
        color: red
      - value: 465
        color: darkred
```

**Screenshots**
After refresh/reload it looks like this.
![image](https://github.com/RomRider/apexcharts-card/assets/14802028/ceafa973-084f-408c-8d02-0fea397831c2)
After switching tabs back and forth it looks as it should again.
![image](https://github.com/RomRider/apexcharts-card/assets/14802028/019addf6-084c-4112-92b7-489ee329070e)

**Expected behavior**
Should display correctly even directly after browser refresh/reload

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge
 - Version: 116.0.1938.62 (Official build) (64-bit)

**Comment by donagrejja** [comment]
This is still an issue for me using latest version of HA and this addon.

**Comment by donagrejja** [comment]
Still an issue.

**Comment by michaelpiron** [comment]
Same issue here:
![image](https://github.com/RomRider/apexcharts-card/assets/4469877/1801b238-878d-4065-a2a2-cac4500f939c)

**Comment by michaelpiron** [comment]
Still an issue

**Comment by RomRider** [comment]
What is the father card of those cards ?
