### ISSUE TITLE
Apex Charts bricks my system

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [RomRider/apexcharts-card#610]
**Describe the bug**
So I'm partially fault at this for setting 3 of my devices to PowerDelta 101 resulting with 5 value entries a second per device. Each second there were 15 entries saved to the Home Assistant database.

ApexChart Area Graph works amazing sadly it looks like the frontend is pulling data and not the server itself. So I'm unable to access Home Assistant because the Graph is loading more than 1800000 entries or 1.8mil.

I think it is pulling all data from the whole database and no clue why as I have set it to show data from 5min ago.

**Version of the card**
Version: latest (can't tell because no access to HA and I installed the card 24.09.23

**Expected behavior**
I think the card should have some data aggregation but on the backend side, where the data is getting compressed into a single value or something... So all values from 5min ago are compressed into a single value. I have changed the PowerDelta to 103 so it only updates the state if it changed more than 3W not each 1W.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Latest

**Comment by weavel** [comment]
I second this observation, my browser locks up if using this chart. I use it for graphing my home energy usage which also has a data point every 30 seconds. I tried mitigating this by setting the update interval to 15 minutes but when browsing from or to the page or when trying to edit this generates a chart update. 

Didn't have this issue (or perhaps noticing it) until a few weeks ago so maybe some update created a performance hit?

**Comment by Claudio1L** [comment]
same here

**Comment by johntdyer** [comment]
yea, I had to give up on this card... shame... loved the look of it

**Comment by Killerherts** [comment]
Same and this started with an update around September with no new graphs added.
