### ISSUE TITLE
First X-Axis label disappears if formatted as 'ddd' when the Y-Axis is hidden

### ISSUE THREAD

**Issue by cokecan72** [RomRider/apexcharts-card#639]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the latest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
With a simple column type chart that displays daily usage data (e.g. gas usage, electricity usage, heating duration etc), if I format the X-Axis labels as 'ddd' to display the shorthand day of the week for each column (e.g. Mon, Tue, Wed) and also hide the Y-Axis, the very first X-axis label disappears along with it's tick. Changing the X-axis label format to 'dd' or 'd' to display the day of the month instead (e.g. 16, 17, 18) displays the very first X-axis label and tick as expected even with the Y-axis still hidden. Likewise, leaving the X-Axis labels format as 'ddd' and showing the Y-axis again also makes the first X-Axis label display again. This same behaviour is present if I use the 'yaxis' options (as per the code example below) or the 'apex_config' options to hide the Y-Axis.

I have also tried this with multiple different types of data collecting sensors to try and rule out questionable data including household gas and electricity usage, TRV heating duration and energy consumption from an individual device.

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml
- type: custom:apexcharts-card
  apex_config:
    xaxis:
      labels:
        format: ddd
  graph_span: 3d
  span:
    end: day
  yaxis:
    - show: false
  series:
    - entity: sensor.gas_import_today
      type: column
      unit: kWh
      statistics:
        type: state
        period: day
        align: start
```

**Screenshots**
X-Axis labels format set to 'ddd' with Y-Axis hidden:
<img width="372" alt="Screenshot 2023-12-18 at 1 57 01 pm" src="https://github.com/RomRider/apexcharts-card/assets/109978326/4105db41-03a3-40e7-b4a8-20e4bee4d5d2">

X-Axis labels format set to 'dd' with Y-Axis hidden:
<img width="368" alt="Screenshot 2023-12-18 at 1 57 15 pm" src="https://github.com/RomRider/apexcharts-card/assets/109978326/93821a09-ef89-47b5-9979-07423a7a75d8">

X-Axis labels format set to 'ddd' with Y-Axis shown:
<img width="366" alt="Screenshot 2023-12-18 at 1 57 34 pm" src="https://github.com/RomRider/apexcharts-card/assets/109978326/7914ef44-b3c7-4cb0-b146-992bbe2dfe49">

X-Axis labels format set to 'dd' with Y-Axis shown:
<img width="378" alt="Screenshot 2023-12-18 at 2 08 59 pm" src="https://github.com/RomRider/apexcharts-card/assets/109978326/f3d09e3d-ec03-4cdb-bb2b-cc9c41599cb5">

**Expected behavior**
Regardless of X-Axis label format or Y-Axis visibility, I'd expect the first X-Axis label to display consistently

**Desktop (please complete the following information):**
 - Browser: Safari
 - Version: 17.0

- Browser: Google Chrome
- Version: 119.0.6045.199

**Smartphone (please complete the following information):**
N/A

**Additional context**
Home Assistant Core: 2023.12.3
Home Assistant Supervisor: 2023.11.6
Home Assistant Operating System: 11.2
Home Assistant Frontend: 20231208.2

**Comment by cokecan72** [comment]
Just to add, my work around so far is to show the Y-Axis using the yaxis options as per the original post, but then hide it using CSS with Lovelace Card-Mod (display: none;). I've also tweaked the padding in apex_chart grid options to get the columns displayed more centrally and uniformly for my use case. 

Here is an example of the finished result:
<img width="197" alt="Screenshot 2023-12-18 at 2 45 04 pm" src="https://github.com/RomRider/apexcharts-card/assets/109978326/2650ad18-2c5b-42ae-9139-ba138caa0a49">

**Comment by wixoff** [comment]
I'd like to see this reopened because the workaround is messy and I haven't seen anything that suggests it's not a bug.  My example is a weather forecast:

![Image](https://github.com/user-attachments/assets/9a7e8846-eb0d-4af2-ae51-e1f0f2e9a45e)

It's the exact same scenario as @cokecan72 describes: **ddd** X-axis labels, Y-axis hidden.

I think it must have something to do with the calculated width of that one text field at the left, because while "dd" works and "ddd" does not, "MM/dd" also does not and "xdd" (just the letter "x" before the two-char date number) disappears in that first slot like the other longer strings.
