### ISSUE TITLE
Use a home assistant entity as color threshold value

### ISSUE THREAD

**Issue by noelie88** [RomRider/apexcharts-card#657]
**Checklist**
- [x ] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I have a dynamic price contract and would like to set the color threshold at a percentage of the maximum price of today. At the moment I can only set a static value.

**Describe the solution you'd like**
I would like to be able to use a variable (home assistant entity) as the color threshold value

**Describe alternatives you've considered**
none

**Additional context**

**Comment by CraigHutchinson** [comment]
I think I will be facing the same issue.  Just started out with HA this week and presently hard-coded thresholds for unit-price costs. I just uploaded it here https://github.com/CraigHutchinson/HA_OctopusAgileCard for a visual reference to this issue.... when the prices all go up or down the colour will be wrong!

**Comment by RomRider** [comment]
You can use the https://github.com/iantrich/config-template-card for that.

**Comment by txespirito** [comment]
I think noelie88 is referring to the fact that if, for example, the series value is the price of a stock, the color of the limit is marked, for example, if the attribute or entity that represents the trend of the price (up/down)

**Comment by txespirito** [comment]
Please keep open. Thanks
