### ISSUE TITLE
Support `columnWidth` option for bar charts (i.e Histogram Plot that doens't have gaps you get on a Bar-Chart)

### ISSUE THREAD

**Issue by CraigHutchinson** [RomRider/apexcharts-card#658]
**Checklist**
- [ x] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Check this image for a time series. 
![image](https://github.com/RomRider/apexcharts-card/assets/54269136/a1dc90f4-b633-4486-a95a-0d8a3d1ca2ab)

**Describe the solution you'd like**
To be able to specify the bar-width as a percentage. As in this solution for react-apexcharts https://stackoverflow.com/questions/74419893/make-a-histogram-in-apexcharts-js
```
plotOptions:{
            bar: {
                columnWidth: "95%",
            }
        },
```

**Describe alternatives you've considered**
Using a line-chart  with stepped line but colour thresholds are not supported for lines as far as I can see

**Additional context**
Card source is here  https://github.com/CraigHutchinson/HA_OctopusAgileCard/tree/main

**Comment by dykandDK** [comment]
This is already supported, if you use the apex_config option and add the following code:

```
  apex_config:
    plotOptions:
      bar:
        columnWidth: 90%
```

Many of the Apex Chart configuration options are supported, if you added this way:

![image](https://github.com/RomRider/apexcharts-card/assets/59793798/971f5f1d-85ad-4ded-ab10-4938ec89e6c1)
