### ISSUE TITLE
High memory usage in Firefox and Tab crash(Previous such issues were closed without resolution)

### ISSUE THREAD

**Issue by Mrsash2020** [RomRider/apexcharts-card#662]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
 I had installed ApexCharts card about six months ago and never had an issue until I updated to latest Firefox. As soon as navigated to the page with the chart, the memory usage goes through the roof crashing that tab. If I access the same page in Edge it doesn’t have this problem.

I removed all but one chart which did not help in Firefox. Then I visited hacs to check if I am missing something. To my amazement ApexCharts card is no longer installed. So I go through and download/install it again which does not fix the issue.

Is anyone else encountered any issues with latest Firefox?

**Version of the card**
Version: 2.0.4

**To Reproduce**
This is the configuration I used:
```yaml

I downloaded it from hacs but also verified the manual steps confirming js file in local folder etc. 
One interesting issue I faced, tried to add the following in Configuration.yaml resulted in error with check in developer tools

resources:
  - url: /local/apexcharts-card.js?v=2.0.4
    type: module

![image](https://github.com/RomRider/apexcharts-card/assets/62192773/ed850328-c28a-437f-97f4-0fe04b6c2c9f)

screenshot of my resources

![image](https://github.com/RomRider/apexcharts-card/assets/62192773/c78c9930-628e-4292-aebd-b67454b5ba94)

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Tested in Firefox and Edge. Firefox crashes
 - Version [e.g. 22] 122

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cloudbr34k84** [comment]
Oh man! im getting this on Chrome as well! Anytime i try and load the dashboard that has an APEX chart it crashes.
On Mobile Its fine though.

**Comment by Mrsash2020** [comment]
> Oh man! im getting this on Chrome as well! Anytime i try and load the dashboard that has an APEX chart it crashes. On Mobile Its fine though. [ha.cloudbr34k.xyz-1707186351447.log](https://github.com/RomRider/apexcharts-card/files/14173947/ha.cloudbr34k.xyz-1707186351447.log)

So are you experiencing this in Firefox as well?

**Comment by cloudbr34k84** [comment]
> > Oh man! im getting this on Chrome as well! Anytime i try and load the dashboard that has an APEX chart it crashes. On Mobile Its fine though. [ha.cloudbr34k.xyz-1707186351447.log](https://github.com/RomRider/apexcharts-card/files/14173947/ha.cloudbr34k.xyz-1707186351447.log)
> 
> So are you experiencing this in Firefox as well?

Nah in chrome.

**Comment by neuhausf** [comment]
I noticed this too. Related to HA 2024.2.
Similar issue in another card: https://github.com/kalkih/mini-media-player/issues/831

**Comment by Tadies** [comment]
Confirmed!!!
It drains ram Usage!!!!!
It does do that a long time now....
But was unable to find it
So thanks!!!!
This should be fixed...

**Comment by Mrsash2020** [comment]
Ok I am running the lovelace dash on Firefox and Edge. Its barely responding after a few minutes in Firefox. It is not effecting Edge. The companion app on Android also not effected. For me not sure its mini player

**Comment by willia0** [comment]
Hi there, same issue here using both Edge 122.0.2365.80 and Chrome 122.0.6261.112, with high CPU usage and frozen tab. iOS Companion App and Safari works butter smooth. 

P.S.: A temporary solution I found is by reducing the graph_span and hence reducing the sample points and then browser seems can handle that. I am now applying limits to sensors update interval to every 30s and observing the outcome.

**Comment by ackstorm23** [comment]
Same problem here.  Firefire rapidly consumes memory until the tab is killed.

**Comment by LukaszBrzyszkiewicz** [comment]
Same issue - Mobile can't handle viewing Apex charts - it's just crashing. On PC loading Apex charts for 24h time span from single sensor update each 5 seconds took abou 2minutes and CPU usage is sky rocket :) After finishing memory usage for tab is about 32GB RAM ! Same data viewed whole week time span is instant on Grafana. Soemthing is very wrong in ApexCharts and currently is almost unusable.

**Comment by lymanepp** [comment]
Issue still present in HA 2024.5. Loading a tab that has 3 charts--with 3 days each--rapidly consumes 10GB or more. The page becomes non-responsive and occasionally will crash the tab or Firefox. Setting a 5 minute interval usually allows the tab to load and be stable, at least until it refreshes.

**Comment by ackstorm23** [comment]
This guy's fork has been updated and is not causing my memory issues.  Just download the .js from his release and over-write it in your existing installation (same as manual instructions for installation) and now it's working fine again.

https://github.com/georgepauna/apexcharts-card

**Comment by RomRider** [comment]
I've updated the library in the latest dev version, performance has improved quite a lot. You should try it.
