### ISSUE TITLE
Support of statistics without state entities

### ISSUE THREAD

**Issue by hindseb** [RomRider/apexcharts-card#663]
Enhance Apexchart to allow to use of statistics data in Home Assistant without state entities.

For example, the Opower integration collects from electricity vendors the power consumption. The integration creates statistics without state entities.  It does that because utilities don't provide real time data. 
See also here: https://github.com/home-assistant/core/issues/110731

Thank you for considering this feature request.

**Comment by smarg120** [comment]
+1 for this request
