### ISSUE TITLE
Y axis ‘auto’ with stacked columns

### ISSUE THREAD

**Issue by man010** [RomRider/apexcharts-card#666]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**
When using stacked columns with y-axis max value configured to « auto » it looks like the y-axis is sized only the max of all the values, not taking into account that in stacked columns, the y-axis should be sized with the sum of all the series.
As a workaround I have created a series with the sum of all the values but i don’t show it in the chart

**Desktop (please complete the following information):**
 - safari, kiosk, Firefox 
 
**Smartphone (please complete the following information):**
 - Device: iPhone, android, windows
 
**Additional context**

**Comment by redfusion83** [comment]
Came here to report the same problem. Thanks for the workaround, I will try that too

**Comment by man010** [comment]
Hello. Has there been any improvement on this issue ?
