### ISSUE TITLE
Wrong Columns height on first y-axis when a second y-axis is defined

### ISSUE THREAD

**Issue by man010** [RomRider/apexcharts-card#669]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
I have defined 6 stacked series on a first y-axis. As I wanted to display an additional information in the header (not in the chart), I have added a second y-axis with the follow series config :
        - entity: sensor.conso_electrique_totale
          type: line
          yaxis_id: second
          name: CUMUL JOUR
          color: red
          group_by:
            func: diff
            duration: 1d
            start_with_last: true
            fill: last
          show:
            in_header: true
            in_chart: false

and with this extra series, the height of some of the series on the first axis is wrong. As you see, the series « Buanderie » should have a value of 0.8kWh, while the column value seems to be around 0.2kWh

Here is the code of the y-axis and series (note the the second series is for the workaround of the other bug I reported yesterday, to get the y-axis automatically scaled with all the stacked values and not only the biggest one) :
      yaxis:
        - id: first
          min: 0
          max: auto
          decimals: 1
          apex_config:
            tickAmount: 5
        - id: second
          min: 0
          max: auto
          show: false
          decimals: 1
          apex_config:
            tickAmount: 5
      series:
        - entity: sensor.conso_electrique_totale
          type: line
          yaxis_id: second
          name: CUMUL JOUR
          color: red
          group_by:
            func: diff
            duration: 1d
            start_with_last: true
            fill: last
          show:
            in_header: true
            in_chart: false
        - entity: sensor.conso_electrique_totale
          yaxis_id: first
          name: CUMUL JOUR
          color: yellow
          show:
            in_header: false
            in_chart: false
        - entity: sensor.conso_electrique_buanderie
          yaxis_id: first
          name: BUANDERIE
          color: green
        - entity: sensor.prise_congelateur_energy
          yaxis_id: first
          name: CONGÉLATEUR
          color: dodgerblue
        - entity: sensor.conso_electrique_multimedia
          yaxis_id: first
          name: MULTIMÉDIA
          color: lime
        - entity: sensor.chauffage_sdb_energy
          yaxis_id: first
          name: CHAUFF. SDB
          color: tomato
        - entity: sensor.pac_alixan_tank_accumulated_consumption
          yaxis_id: first
          name: EAU CHAUDE
          color: pink
        - entity: sensor.pac_alixan_heating_accumulated_consumption
          yaxis_id: first
          name: CHAUFF. PAC
          color: grey

**Version of the card**
Version:

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by man010** [comment]
I answer to myself. This issue occurs when the series are not configured in the same order as the corresponding yaxis : 

WORKING 
========
yaxis : 
  - id: first
yaxis : 
  - id: second
Series : 
  - entity: a
     yaxis_id: first
  - entity: b
     yaxis_id: first
  - entity: c
     yaxis_id: second
  - entity: d
     yaxis_id: second
  
NOT WORKING 
============
yaxis : 
  - id: first
yaxis : 
  - id: second
Series : 
  - entity: c
     yaxis_id: second
  - entity: d
     yaxis_id: second
  - entity: a
     yaxis_id: first
  - entity: b
     yaxis_id: first

**Comment by stepir** [comment]
Thanks - had exactly the same issue and found this thread
