### ISSUE TITLE
Allow calculation of a new series from grouped values of two (or more) other series

### ISSUE THREAD

**Issue by evilphish** [RomRider/apexcharts-card#675]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I would like to be able to create a graph based on an operation between two entities. As an example:
- My electric car has charging cycles that use a certain amount of kWh
- Whenever it is charging, I am getting the current odometer value
- Using ApexCharts I can plot the kWh spent and km driven per week as bar charts
- I now need a way to calculate the kWh per 100 km multiplied by the cost per kWh so I get that weeks cost normalized to 100 km driven

**Describe the solution you'd like**
The possibility to use the transform function or something similar to do math utilizing two data series grouped on the time axis. So for example: Divide weekly value of sensor A by weekly value of sensor B

**Describe alternatives you've considered**
- Setting up various template sensors that don't give me the desired outcome or are only available for short term statistics
- Trying the existing transform function and using the state object of another entitity. This however only uses the same and latest value of that entity for every week so it is not usable

**Additional context**
![image](https://github.com/RomRider/apexcharts-card/assets/19637718/a4b01ec1-546a-48a0-ae59-b5e29ddbf24b)
This is how the current statistics look. In addition I would now like to be able to calculate the cost per 100 km for each week as outlined above and show it in the chart. For that I need to divide the weekly value of *Used energy* (sensor A) by *km driven* (sensor B) and multiply by *100 km* (constant) and the associated *cost per kWh* (constant). 

There is a similar request here but the issue was closed: https://github.com/RomRider/apexcharts-card/issues/461

**Comment by i00** [comment]
I want this too
