### ISSUE TITLE
Documentation for state mapping of non numerical entities

### ISSUE THREAD

**Issue by loeffelpan** [RomRider/apexcharts-card#678]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Non numerical entities are stated as supported. But I can't find any documentation for that.

**Describe the solution you'd like**
Please describe how to use that feature.

**Comment by loeffelpan** [comment]
I'm still interested in such a documentation.

**Comment by RomRider** [comment]
Please have a look at https://github.com/RomRider/apexcharts-card?tab=readme-ov-file#transform-option
