### ISSUE TITLE
Add support for multiple series pie / donut charts

### ISSUE THREAD

**Issue by i00** [RomRider/apexcharts-card#691]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Support should be added for multiple series on pie / donut charts that allow them to be "stacked" on each other.

**Describe the solution you'd like**
Add support for multiple series.

**Comment by RieCo432** [comment]
I second this. For some applications, it would be really useful to have a stacked donut chart.
