### ISSUE TITLE
Show another entity as secondary info

### ISSUE THREAD

**Issue by fusionstream** [RomRider/apexcharts-card#696]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
I am drawing a graph of WiFi strength of various devices. I can see that some devices have a weak signal but I am unable to see what AP they are connected to.

**Describe the solution you'd like**
Have the ability to show another entity (or an attribute) as secondary info in the legend

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by RomRider** [comment]
In the legend below the chart or in the header ?

**Comment by fusionstream** [comment]
In the header. The footer is too cramped to fit more information

**Comment by pikim** [comment]
In combination with the donut or the pie chart this would allow to show, for example, the power from grid and the solar power directly in the chart and the sum of both in the header.

**Comment by fusionstream** [comment]
up

**Comment by fusionstream** [comment]
Awwww :(
