### ISSUE TITLE
Expand entity type range.

### ISSUE THREAD

**Issue by Spamfast** [RomRider/apexcharts-card#706]
**Checklist**
- [X ] I am running the latest version of the card - v2.0.4
- [X ] I checked if there isn't another feature request opened with the same request
- [X ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Yes, I believe. I could have sworn that I used to be able to use a switch entity with a suitable `transform: "return x === 'on' ? 1 : 0;"` to show a switch on the graph but now it always displays as N/A in the states legend and doesn't show up on the plot.

**Describe the solution you'd like**
Can we please use arbitrary entity types provided they have a 'state' property so we don't have to create template sensor/binary_sensor entities for the sole purpose of graphing?

**Describe alternatives you've considered**
I'm using a template binary sensor now which works but is not very elegant as it loads the HA server unnecessarily even when I'm not viewing the graph.

**Additional context**
Nothing to declare.

**Comment by RomRider** [comment]
Did you disable history for this entity or the whole switch domain? That would be the only reason that I can think of.

**Comment by Spamfast** [comment]
At one point I think I did. I'll close this.
