### ISSUE TITLE
Support of statistics without state entities

### ISSUE THREAD

**Issue by vingerha** [RomRider/apexcharts-card#707]
Enhance Apexchart to allow the use of statistics data in Home Assistant without state entities.

Re-trying on the ticket @hindseb opened earlier

There are quite a few integrations that collect statistics externally and HA (core) then requires this to have a statistics_id with a colon, alike opower:consumption.... I am assuming that this prevents the Energy dashboard to complain.

All these integrations create statistics without state entities because utilities don't provide real time data. 
Examples are opower (see https://github.com/RomRider/apexcharts-card/issues/663), french electricity (myelectricaldata) and gas (gazpar_2_mqtt) and likely many more. 

HA regular statistics card can deal with these stats but that does not allow to add the super functionality that ApexC offers.

**Comment by vingerha** [comment]
@RomRider 
it is not too easy to get to the details of HA as there is no (di.e. I id not find it) documentation on this topic. 
When diving in the core/recorder/etc. python stuff one finds out that the external statistics are stored with a (for-me) very odd naming convention wrt to their statistics_id (statistics_meta), e.g. for my gas sensors, they look like: ```gazpar:gazpar_thuis_consumption```
 ... especially the use of  a colon in the name was surprising. 
By using this 'convention' (no clue who invented this), it does not check (?) for the energy dashboard but it also does not allow to provide dummy sensors to circumvent apexcharts needs/shortcommings in this case.

I am not at all up to speed with the tech stuff behind your apecharts solution but if you see light at the end of this tunnel and may provide direction, I am am happy to further investigate/test/etc. :)

**Comment by hindseb** [comment]
Hi @vingerha 

If it is of any help, I am copying the documentation from Home Assistant on the naming convention.
Please see here: https://data.home-assistant.io/docs/statistics/

Here you can see that colons are used if the data is imported from an external source. 

I hope that helps a bit further. I would highly appreciate it if the apex chart could be enhanced. I would love to use the tool to show data from my long-term statistics. Thanks for the efforts in advance.

**Comment by vingerha** [comment]
Hi, I am aware of that and the design (logic?) escapes me but even though I want to understand how/why HA does things, I am on low expectation that this gets fixed. I tried with dummy entities and normal (non ':' ) named statistics, apex works but then the energy board (a.o.) starts complaining. 
In any case... the request is to have Apexcharts ignore the 'normal' entity and allow statistics entities ...which is the actual source of the statistics data so not too bad as a entry point :)

**Comment by RomRider** [comment]
Where do you find this `statistics_id` with the `:` in the name ?

**Comment by vingerha** [comment]
After the import you would only find this in the statistics_meta table
Here is a visual example of mine for two integrations that use this load, they both use data extracted from the provider with a day or more delay in the availability. There are quite a few other areas on where this is used.

![image](https://github.com/RomRider/apexcharts-card/assets/44190435/94aabbf2-d013-4942-a683-9db263caaac4)

**Comment by smarg120** [comment]
hi, sorry to review this, but  are there any plans for such support?  I too have statistics data inject from external source (integration with local electric company), and the entities are in form of x:y.....HA built in statistics card knows to show them, but its inferior with regards to what apexcharts can do.....both UX and UI wise.....so now the situation is that in my dashboard i have a mix of cool apexcharts and ugly ha statistics card...

**Comment by Gandulf78** [comment]
Could you please reopen this feature request? It would be very cool for external data as electrical and gas consumption.

**Comment by vingerha** [comment]
It has been asked before so my guesswork is that it is quite complex.
@RomRider (apologies for directness)... if (!) you believe this is is at all feasible, maybe some directions for dev's could help to create a PR?

**Comment by vingerha** [comment]
After quite a while.... I found a ugly(?) workaround based on some postings in the the forum

In below sensor.0c414c7e_b64a8a9a_browser_user is just a random entity as Apexcharts demands an existing entity …it is a dummy entry but has to be an existing one
the stat_entity has to be added twice and then it works.
Note that for my statistic data, I am using the ‘state’ value, you may want ‘sum’ or 'mean’ or anything else IF that exists for your entity (check via the HA statistics graph)
```
type: custom:apexcharts-card
graph_span: 100d
series:
  - entity: sensor.0c414c7e_b64a8a9a_browser_user
    name: current
    color: red
    stroke_width: 1.3
    data_generator: |
      const stat_entity = 'gazpar:gazpar_thuis_consumption_stat';
      var statistics = await hass.callWS({
          type: 'recorder/statistics_during_period',
          start_time: new Date(start).toISOString(),
          end_time: new Date(end).toISOString(),
          statistic_ids: [stat_entity],
          period: "hour",
      });
      var stats = statistics[stat_entity];
      var result = [];
      var len = stats.length;
      for (let i = 0; i < len; i++) {
        let stat = stats[i].state;
        result.push([(new Date(stats[i].end).getTime()),stat]);
        }
      return result;
```

**Comment by Erpiovra87** [comment]
Hi! how do you create dummy entity sensor.0c414c7e_b64a8a9a_browser_user ??

**Comment by vingerha** [comment]
> Hi! how do you create dummy entity sensor.0c414c7e_b64a8a9a_browser_user ??

ANY entity will do

**Comment by Erpiovra87** [comment]
this is my configuration
sensor in configuration.yaml

- platform: template
  sensors:
    enel_consumption:
        friendly_name: "enelgrid"
        unit_of_measurement: "kWh"
        device_class: Energy

apex chart

type: custom:apexcharts-card
graph_span: 100d
series:
  - entity: sensor.enel_consumption  ******UNABLE TO FIND ENTITY*******"
    name: current
    color: red
    stroke_width: 1.3
    data_generator: |
      const stat_entity = 'sensor:enelgrid_it002e0177172a_consumption';
      var statistics = await hass.callWS({
          type: 'recorder/statistics_during_period',
          start_time: new Date(start).toISOString(),
          end_time: new Date(end).toISOString(),
          statistic_ids: [stat_entity],
          period: "hour",
      });
      var stats = statistics[stat_entity];
      var result = [];
      var len = stats.length;
      for (let i = 0; i < len; i++) {
        let stat = stats[i].state;
        result.push([(new Date(stats[i].end).getTime()),stat]);
        }
      return result;

**Comment by Erpiovra87** [comment]
where is the problem?

**Comment by vingerha** [comment]
No clue, **the entity needs to exist**...can be weather/sensor/input_number/ANYTIHING

**Comment by Erpiovra87** [comment]
ok right. it still doesn't work even if I use an existing sensor

**Comment by vingerha** [comment]
past a screenshot and do FORMAT your code please, this is unreadable

**Comment by Erpiovra87** [comment]
dummy sensor in configuration.yaml

`
- platform: template
  sensors:
    enel_consumption:
        friendly_name: "enelgrid"
        unit_of_measurement: "kWh"
        device_class: Energy`

apex chart

`
type: custom:apexcharts-card
graph_span: 100d
series:
  - entity: sensor.enel_consumption
    name: current
    color: red
    stroke_width: 1.3
    data_generator: |
      const stat_entity = 'sensor:enelgrid_it002e0177172a_consumption';
      var statistics = await hass.callWS({
          type: 'recorder/statistics_during_period',
          start_time: new Date(start).toISOString(),
          end_time: new Date(end).toISOString(),
          statistic_ids: [stat_entity],
          period: "hour",
      });
      var stats = statistics[stat_entity];
      var result = [];
      var len = stats.length;
      for (let i = 0; i < len; i++) {
        let stat = stats[i].state;
        result.push([(new Date(stats[i].end).getTime()),stat]);
        }
      return result;`

**Comment by Erpiovra87** [comment]
[configuraation.txt](https://github.com/user-attachments/files/20100908/configuraation.txt)

**Comment by Erpiovra87** [comment]
can you read?

**Comment by vingerha** [comment]
Same issues, use 3 backticks .. if there is no error then your sensor is probable not containing any stats.

**Comment by vingerha** [comment]
in other words, my code works clearly for me and a few others, so you must either be doing something wrong or you have a odd case.

**Comment by Erpiovra87** [comment]
in my energy dashboard i can see the graph "sensor:enelgrid_it002e0177172a_consumption"
Also when i create a statistics graph via home assistant. So data is ok.

I think the problem is with the entity that i create. I understand that i've to create an empty sensor right??

**Comment by vingerha** [comment]
No and not sure why this is so hard to communicate, the entity that goes with series can be ANY entity as long as it exists. Your error shows that the entity sensor.enel_consumption does not exist, pick something else

**Comment by Erpiovra87** [comment]
so i can pick a sensor that already measures data??

**Comment by vingerha** [comment]
Copying: "In below sensor.0c414c7e_b64a8a9a_browser_user is just a random/dummy entity as Apexcharts demands an existing entity, the stat_entity has to be added twice and then it works....so ANY entity will do"

**Comment by Erpiovra87** [comment]
it works!!!! the problem was the ‘state’ value. I used change

**Comment by Erpiovra87** [comment]
![Image](https://github.com/user-attachments/assets/4bbacca4-db82-4ce9-8e06-e3e9d70ab612)

i was noting that the data is translated

I've the 6-May data on the 7-May x axis.... is it normal??

**Comment by Erpiovra87** [comment]
![Image](https://github.com/user-attachments/assets/0bc2ae5b-226d-484c-bd69-1f9b01470698)

**Comment by vingerha** [comment]
this is not a general support apex post, please remove an place this in HA forum so other can help

**Comment by timwiegand** [comment]
Note that [Plotly Graph Card](https://github.com/dbuezas/lovelace-plotly-graph-card) aslo supports external statistics entities, so you could always give that a try if the built-in Statistics Graph doesn't work for you.

A lot of cards have trouble with these entities.  The most common problem is that they try to validate that the entity exists by querying it's state. If there's no state, they assume they've been given a bad entity id. 

@RomRider The simplest implementation would be to use a different validity check if the series has a `statistics` object, such as querying statistics for the entity id and seeing if anything comes back. Or just skip the check entirely if the id has a ":" in it.

If you rely on metadata from the state like name/unit, use a default value (""/none) if there is no state. The caller can define explicit series options if they don't like the default.

**Comment by vingerha** [comment]
@timwiegand if you read the thread above, I already posted a solution on how to get statistics from other sensors. This one is specifically interesting if you are importing data into stats without having an actual sensor as their basis.
