### ISSUE TITLE
Allow transform to work across series

### ISSUE THREAD

**Issue by i00** [RomRider/apexcharts-card#710]
**Checklist**
- [ ] I am running the latest version of the card
- [ ] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

It would be good to be able to access other series values from a transformation.

**Describe the solution you'd like**
e.g
transform: x - series.ev_power;

**Comment by RomRider** [comment]
That is impossible as they are all updated in parallel (and also would require all the datapoints to be aligned).
