### ISSUE TITLE
Add func options: last not null and/or last > 0

### ISSUE THREAD

**Issue by Toukite** [RomRider/apexcharts-card#72]
Hello,
Regarding this:
![image](https://user-images.githubusercontent.com/42780622/107425407-39a1df00-6b1f-11eb-835b-989f040b07a5.png)

Would it be possible to have a function quite equivalent to last, but that would take the last not null/empty or even the last > 0 value ?

Usecase is that we can have a value that is evaluated by a WS. Sometimes, the WS fails and the value is not returned or is evaluated to zero. In this case, the last function isn't working and shows zero instead of a previous correct value.

**Comment by RomRider** [comment]
What about using `fill_raw: last`? This would fill missing data, and group by would give you the last state for each bucket.

**Comment by Toukite** [comment]
OK thank you, I think this should work !

**Comment by RomRider** [comment]
I'm thinking about introducing the same as `transform` but for buckets. This would give another kind of latitude.
