### ISSUE TITLE
I suffer from graphs now updating the values since introduction of HA 2024.7

### ISSUE THREAD

**Issue by commentsonly** [RomRider/apexcharts-card#720]
This is pretty strange. Got a bunch of diagrams which do work lets say half of the day.
Then at 1 moment all seem to loose track of their values and the graph end with a horizontal line.
(likely no new data seen).
But if looking at the sensors in developertools>tools new values are avalaible

a rollback to 2024.6 cured the issue.
reinstalling 2024.7 (or even 2024.7.1) brought back the issue

Cleared te browser cache even hard restarted HA .... can't get it solved.
And yes, sure latest versions, ...worked since more but a year but now something got broken.

Oh yes and it's all apexcharts in various dashboards/various sensor sources let it be modbus, esp devices and such like .... all do fail at the very same second and sometimes all do restart plotting values some hours later.

gimme a hint please

**Comment by daylehouse** [comment]
Same for me too. 
<img width="382" alt="Screenshot 2024-07-07 at 10 23 30" src="https://github.com/RomRider/apexcharts-card/assets/59344494/1fa6662b-3c20-465e-859e-352868d7175a">

**Comment by commentsonly** [comment]
A complete restart of HA solves it, but only until the problem starts again. I first thought somethings wrong with the entities themselves but by now I'd say its a apex charts issue loosing sync somehow.Am 07.07.2024 11:26 schrieb daylehouse ***@***.***>:
Same for me too.
Screenshot.2024-07-07.at.10.23.30.png (view on web)

**Comment by daylehouse** [comment]
Looks more fundamental as my home assistant energy dashboard does the same thing, it’s not directly an issue with Apex Charts.

Regards,

Dayle
________________________________

**Comment by daylehouse** [comment]
Here’s a link to the bug

https://github.com/home-assistant/core/issues/121485

Regards,

Dayle
________________________________

**Comment by rrooggiieerr** [comment]
https://github.com/home-assistant/core/issues/121164

**Comment by sebastian-bugajny** [comment]
I'm affecting the same issue on HA 2024.7.1 with all my Apex charts

**Comment by RomRider** [comment]
The issue is because of  https://github.com/home-assistant/core/issues/117263.

It needs to be fixed in core.

**Comment by commentsonly** [comment]
2024.8 ....... a long time then. Rushed through the hyperlink you posted. Any idea what exactly affects apexcharts? Is it a problem resulting from the recorder, eg. would preventing purge also solve the apex charts issue?
I wouldn't mind since the HDD is mostly empty.
Good to know anyway I didn't miss a breaking change of apex

**Comment by RomRider** [comment]
Disabling purge would make it work again for apexcharts and any other card or module relying on the recorder module (default energy dashboard, default history card, etc...).
