### ISSUE TITLE
V2.1.x series kindof broke y axis grid

### ISSUE THREAD

**Issue by Floppe** [RomRider/apexcharts-card#728]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser
- [X] I verified that I'm really running the lastest version in my browser console
- [X] I checked if there is another issue opened with the same problem

**Describe the bug**
I've tested 2.1.0, 2.1.1 and 2.1.2. All versions do not show Y axis grid lines when using 2 axes. Only min and max line is shown.

**Screenshots**
Before upgrade
![image](https://github.com/RomRider/apexcharts-card/assets/238729/0bb19000-6ba4-43c5-aeea-72d0322344f2)
After upgrade
![image](https://github.com/RomRider/apexcharts-card/assets/238729/227ea927-7f1a-4c4b-a4b9-fa8f6d8ba1c8)

**Desktop:**
 - Browser [Chrome]
 - Version [126.0.6478.127 (Official Build) (64-bit)]

**Comment by Floppe** [comment]
Thanks. Did not help with forceNiceScale though.

I also noted a another issue in another graph. So I reverted to 2.0.4 for now.

![image](https://github.com/RomRider/apexcharts-card/assets/238729/5991e519-6cc0-40d1-9d32-bf91067eb3c7)

Before if was like this:
![image](https://github.com/RomRider/apexcharts-card/assets/238729/1a179093-aafc-467a-b6c2-aed8e5017953)

Note the y-axis 0 line. And of course the columns width.

**Comment by jhemak** [comment]
I am also having several different issues with V2.1.x that are not present in 2.0.4.  I have worked around most of those problems, however the one I cannot seem to solve is needing to change forceNiceScale to false since the scale is indeed no longer nice.  Any openness to rolling this back in the repo and making 2.1.x a beta until these issues can be addressed?

**Comment by wejto** [comment]
I also found some issues with the y-axis after upgrading from 2.0.4 (the last version not having this different behaviour).

2.0.4

![image](https://github.com/RomRider/apexcharts-card/assets/35685467/8591c3b4-fee4-40dc-88b0-95d6617817a4)

any newer version

![image](https://github.com/RomRider/apexcharts-card/assets/35685467/9a975d85-47be-4fbe-bddc-a3590294b7ca)

Note: the stacking works again even in the newer versions but the yaxis section has to go away at all which I would prefer not to.

The config in my scenario looks like following

`yaxis:
  - min: 0
    max: ~15
    decimals: 0
    apex_config:
      tickAmount: 5`

**Comment by del13r** [comment]
> I am also having several different issues with V2.1.x that are not present in 2.0.4. I have worked around most of those problems, however the one I cannot seem to solve is needing to change forceNiceScale to false since the scale is indeed no longer nice. Any openness to rolling this back in the repo and making 2.1.x a beta until these issues can be addressed?

I initially thought I was downgrading, however I was too impatient and fast with the interface.
I had to wait a few seconds after choosing 2.0.4 before pressing the download button.
![image](https://github.com/user-attachments/assets/88d9a7dc-10b9-44ce-b07c-bf8ba9141fb0)

**Comment by Floppe** [comment]
Still pending
