### ISSUE TITLE
Does not support visibility settings

### ISSUE THREAD

**Issue by freeDom-** [RomRider/apexcharts-card#759]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Visibility settings do not work for the card. When one tried to add the visibility property the following error is thrown:

```/// apexcharts-card version 2.1.2 /// value.visibility is extraneous```

**Version of the card**
Version: 2.1.2

**To Reproduce**
This is the configuration I used:
```yaml
visibility:
  - condition: state
    entity: binary_sensor.night_time
    state: "off"
```

**Expected behavior**
Visibility settings should work the same way as for any other card.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 129.0.1

**Comment by sebastian-bugajny** [comment]
Would be nice to have support for visibility functionality added in HA few month ago

**Comment by cyberdreamandroid** [comment]
Agree, this would be highly appreciated. As a workaround, you can put it in a horizontal-stack which supports conditional visibility settings.

**Comment by realwizzard** [comment]
Agree, this would be highly appreciated. As a workaround, you can put it in a horizontal-stack which supports conditional visibility settings.
