### ISSUE TITLE
Animation when the card shows up for the first time

### ISSUE THREAD

**Issue by r-jean-pierre** [RomRider/apexcharts-card#79]
**Checklist**
- [X] I am running the latest version of the card
- [X] I checked if there isn't another feature request opened with the same request
- [X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No not a problem but a cool useless nice to have! There is already a spinning icon but having an animation of lines (e.g. left to right drawing) would be the cherry on the cake

**Describe the solution you'd like**
Each line is drawn slowly, one after each other, and each pixel of a line is displayed from left to right until the display is complete 

**Describe alternatives you've considered**
Well, when you never saw it, you don't consider. But when you already saw, too late, you cannot live without! I do not see something else which can enhance a nice introduction of graphs
BTW there are some animations when you select/deselect a line on a plot, but maybe too fast and the kind of zoom/translation/bouncing is not as pleasant as a speed constant and peaceful point after point line drawing

**Additional context**
like the animation parameter on mini-graph card

**Comment by RomRider** [comment]
That is not a feature of the library I use. The only one available is the bouncing effect and I've disabled it for the initial display because it's broken in many cases. 

Nothing I can do there.

**Comment by r-jean-pierre** [comment]
Okay thank for sharing the technical details and thank you again for the great job you did with apexcharts

**Comment by RomRider** [comment]
It seems that this has been answered, so I'll close it.
