### ISSUE TITLE
Efficiency in displaying multiple attributes from the same entity

### ISSUE THREAD

**Issue by andrewdolphin** [RomRider/apexcharts-card#80]
**Checklist**
- [ x] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Firstly, want to say thanks for the card -fantastic work, it's the only graph card I've found that is able to graph attributes as well as the state of an entity. I have found however that when graphing multiple attributes from the same entity, for example the current and set temperature from a climate entity (I also graph another entity) then this can cause quite a delay in rendering the graph (there are over 5,000 data points for each attribute).

Having profiled the page the delay is spread fairly evenly between the three API calls and three runs through of the updatehistory function.

**Describe the solution you'd like**
Would it be possible to recode the function to deal with multiple attributes from the same entity more efficiently? In theory only one API call should be necessary but it would also be possible to only loop through the data once also.

Thanks again!

**Comment by RomRider** [comment]
Thanks, I know it's not perfect but I won't do that. I would have to rewrite most of the logic and I won't. I chose maintainability over performance.
