### ISSUE TITLE
Allow javascript functions in chart options for parameters that need it

### ISSUE THREAD

**Issue by andrewdolphin** [RomRider/apexcharts-card#81]
**Checklist**
- [ x] I am running the latest version of the card
- [ x] I checked if there isn't another feature request opened with the same request
- [ x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Several apexchart options require being passed a javascript function, for example a axis label formatter (https://apexcharts.com/docs/formatting-axes-labels/). 

**Describe the solution you'd like**
Allow users to define a javascript function within a template to be passed into the chart options. I've seen another card work for this and whilst it requires use of eval() works well.

**Comment by RomRider** [comment]
I'll think about a way to make this possible. Eval of course, but I don't want to have to indentify every single field which supports a function 😉

So probably by identifying if the string starts with `function(` for eg?
`field_name: function(x, y, z) {...}`

**Comment by pauln** [comment]
@RomRider Have you had any more thoughts on this?  I'd also like to use label axis formatters - so even an initial implementation limited to label axis formatters would be helpful to at least a few people (myself and @andrewdolphin included).

**Comment by pauln** [comment]
@RomRider Thanks!  I'll give it a go tonight.

**Comment by pauln** [comment]
@RomRider Thanks again - I can confirm that this is working for me in 1.9.0-dev.1!
