### ISSUE TITLE
Header to provide option to show entity value at current time

### ISSUE THREAD

**Issue by markcocker** [RomRider/apexcharts-card#86]
**Checklist**
- [x] I am running version 1.6 of the card (the latest version at the time of raising)
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
In the card header, the value for the entity is always the last entry in the array of entity values, even if that time is in the future.

**Describe the solution you'd like**
In the card header, the value for the entity is chosen based on the current time.
For example, step through the entity array to find the last time period before now and use that value.

**Describe alternatives you've considered**
In the card header, an option is provided to show the entity value for the first entry in the array of entity values.

Another alternative is to require the entity to have the desired value to be displayed. Only issue with this approach is that the entity is created by https://github.com/markgdev/home-assistant_OctopusAgile#octopusagilerates so will need to get that project updated.

**Additional context**
Example use case including screen shots are in the [Home Assisant community](https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/493?u=markcocker)

**Comment by RomRider** [comment]
So I'm thinking to make it happen this way:
```yaml
series:
  - entity: x.y
    show:
      in_header: now # other values are true and raw currently
```
if set to `now`, it will:
* Take the first available value **before** now
* If it doesn't exist, it will take the first value **after** now

Does that make sense?

**Comment by torkelsson** [comment]
IMHO, it might be better to show NaN (or -) if a value before now does not exist. Maybe two options; before_now and after_now so you can choose which value to show?

Would it also make sense to also add first/last as options? I.e be able to choose if you want to show the first or last value in the series? Last being the current behaviour.

**Comment by RomRider** [comment]
Makes sense for `before_now`/`after_now`, however, I'm wondering what would be the use case to show the first data from the chart?

**Comment by markcocker** [comment]
> I'm wondering what would be the use case to show the first data from the chart?

I only need the `before_now/after_now` - I only mentioned the first data item as an alternative as in my scenario it is the same as 'before_now'.

**Comment by torkelsson** [comment]
> Makes sense for `before_now`/`after_now`, however, I'm wondering what would be the use case to show the first data from the chart? (not that I don't want to implement it, I'm just curious)

I had a use case in mind when writing my reply, but of course I have forgotten it now. The only reason I can think of is to have matching first/last, before_now/after_now, etc.
