### ISSUE TITLE
graph_span v1.1.0 value.graph_span is extraneous, make sure to clear browser cache if you are using 1.1.0-dev-1

### ISSUE THREAD

**Issue by deepcoder** [RomRider/apexcharts-card#9]
Chrome on MacOS did not seem to detect the change with either a 'refresh' in HA UI or a page reload. I had to clear the cache in Chrome.

FYI.

**Comment by RomRider** [comment]
You always have to clear the cache or change the URL in your resources if installed manually.
If installed through HACS, this is done automatically and a double browser refresh will fix the issue.

**Comment by deepcoder** [comment]
Good to know. I have about 20 Lovelace custom resources installed all manually via configuration.yaml and this was the first time I remember having to do more that 'refresh'  in the HA web page and reload the page in Chrome.

Keep up the great work, thanks!
