### ISSUE TITLE
Group by exact hout

### ISSUE THREAD

**Issue by wormiedk** [RomRider/apexcharts-card#93]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [x] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
group by exact hour e.g. 11-12, 12-13, 13-14 instead of by current e.g. 11.42-12.42, 12.42-13.42 ...

**Comment by RomRider** [comment]
That is already possible if you make your graph end at the hour/start at the hour
```
span:
  end: hour
```

**Comment by wormiedk** [comment]
Thanks!
