### ISSUE TITLE
Extremas for inverted series showing in wrong location

### ISSUE THREAD

**Issue by johnsdixon** [RomRider/apexcharts-card#96]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
When enabling extremas for an inverted series, the extrema flags are located at the non-inverted peak and trough. These y position for these should be inverted prior to display.

**Version of the card**
Version: 1.7.1

**To Reproduce**
This is the configuration I used:
```type: 'custom:apexcharts-card'
cache: true
header:
  show: true
  title: Network Bandwidth
  show_states: true
  colorize_states: true
all_series_config:
  type: area
  show:
    extremas: true
series:
  - entity: sensor.wan_bandwidth_in
  - entity: sensor.wan_bandwidth_out
    invert: true
graph_span: 2h
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26306852/108373423-c9b6e700-71f7-11eb-802e-b228f8429019.png)

**Expected behavior**
Extrema for inverted series to be displayed below the 0 line on the y axis

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 88.0.4324.150 / 88.0.4324.182

**Smartphone (please complete the following information):**
Phone: Huawei Mate 20 Pro
OS: Android (EMUI 10.1.0.328)
Browser: Firefox
Version: 85.1.3

**Additional context**

**Comment by RomRider** [comment]
Good catch! Forgot about that one :)

**Comment by johnsdixon** [comment]
That fixed the inverted point placement, but I also didn't notice the -ve sign on the value in the legend. (My bad, sorry!) The expected value is in the header, but the legend shows with a preceding -ve.
